### ISSUE TITLE
Error while analyzing xxxxxx.class

### ISSUE THREAD

**Issue by fumeng0330** [jacoco/jacoco#1069]
https://www.jacoco.org/jacoco/trunk/doc/faq.html

https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Thank you!

jacoco：0.8.4
asm:7.2

```
java.io.IOException: Error while analyzing /home/jenkins/data/jenkinsHome/workspace/Server-Reader-Coverage/reading-expert-server-backend/target/classes/com/netease/readingexpert/server/backend/factory/vo/VestAccountVO.class.
        at org.jacoco.core.analysis.Analyzer.analyzerError(Analyzer.java:162)
        at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:133)
        at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:156)
        at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:192)
        at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:225)
        at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:220)
        at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:220)
        at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:220)
        at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:220)
        at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:220)
        at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:220)
        at com.netease.bjxiongwenjia.webhook.user.service.login.ReportGenerator.analyzeStructure(ReportGenerator.java:148)
        at com.netease.bjxiongwenjia.webhook.user.service.login.ReportGenerator.create$sentryProxy2(ReportGenerator.java:87)
        at com.netease.bjxiongwenjia.webhook.user.service.login.ReportGenerator.create(ReportGenerator.java)
        at com.netease.bjxiongwenjia.webhook.user.service.login.ReportGenerator.diff$sentryProxy4(ReportGenerator.java:196)
        at com.netease.bjxiongwenjia.webhook.user.service.login.ReportGenerator.diff(ReportGenerator.java)
        at com.netease.bjxiongwenjia.webhook.user.web.api.DiffCoverageController.getUserInfo$sentryProxy2(DiffCoverageController.java:54)
        at com.netease.bjxiongwenjia.webhook.user.web.api.DiffCoverageController.getUserInfo(DiffCoverageController.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke$sentryProxy(StandardContextValve.java:96)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null
        at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
        at org.jacoco.core.internal.flow.ClassProbesVisitor.<init>(ClassProbesVisitor.java:37)
        at org.jacoco.core.internal.flow.ClassProbesVisitor.<init>(ClassProbesVisitor.java:27)
        at org.jacoco.core.internal.analysis.ClassAnalyzer.<init>(ClassAnalyzer.java:55)
        at org.jacoco.core.analysis.Analyzer$1.<init>(Analyzer.java:94)
        at org.jacoco.core.analysis.Analyzer.createAnalyzingVisitor(Analyzer.java:93)
        at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:113)
        at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:131)
```

**Comment by marchof** [comment]
Please provide this class file:

/home/jenkins/data/jenkinsHome/workspace/Server-Reader-Coverage/reading-expert-server-backend/target/classes/com/netease/readingexpert/server/backend/factory/vo/VestAccountVO.class

**Comment by marchof** [comment]
Also: Are you using a custom version of JaCoCo? JaCoCo 0.8.4 depends on asm 7.1

**Comment by fumeng0330** [comment]
yes ,I'm using a custom version of JaCoCo.  I modified asm 7.1 but it still return this error

**Comment by Godin** [comment]
@marchof I believe there is no need to look at a class file and this ticket can be closed as invalid because of usage of incorrect ASM version:

in stacktrace provided by @fumeng0330 

> ```
> Caused by: java.lang.IllegalArgumentException: null
>        at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
> ```

there is no message (`IllegalArgumentException: null`), whereas `ClassVisitor` in ASM `7.1` might throw `IllegalArgumentException` only with message `"Unsupported api"` - see https://gitlab.ow2.org/asm/asm/-/blob/ASM_7_1/asm/src/main/java/org/objectweb/asm/ClassVisitor.java#L70

and there is no debug information (`ClassVisitor.<init>(Unknown Source)`), whereas official ASM `7.1` distribution has debug information.

**Comment by marchof** [comment]
@fumeng0330 We cannot analyze issues with custom versions, sorry.
