### ISSUE TITLE
Jacoco 0.8.5 is incompatible with Firebase Test Lab

### ISSUE THREAD

**Issue by ZacSweers** [jacoco/jacoco#1072]
### Steps to reproduce 

* JaCoCo version:  0.8.5
* Operating system: Android (API 23)
* Tool integration: Gradle
* Complete executable reproducer: Cannot put up a public repo considering our repro case is a paid service, but we're happy to hop on a private call to pair on it or do any extra debugging/information collection!
* Steps: When we update jacoco from 0.8.4 to 0.8.5, it no longer works on Firebase Test Lab devices and crashes

### Expected behaviour

It does not crash and continues to work as normal

### Actual behaviour

It crashes during its initialization

```
java.lang.RuntimeException: Unable to instantiate application com.Slack.SlackApp: java.lang.RuntimeException: Failed to initialize JaCoCo.
     FATAL EXCEPTION: main
Process: com.Slack.internal.debug, PID: 6085
java.lang.RuntimeException: Unable to instantiate application com.Slack.SlackApp: java.lang.RuntimeException: Failed to initialize JaCoCo.
	at android.app.LoadedApk.makeApplication(LoadedApk.java:578)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680)
	at android.app.ActivityThread.-wrap1(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.RuntimeException: Failed to initialize JaCoCo.
	at org.jacoco.agent.rt.internal_43f5073.Offline.getRuntimeData(Offline.java:41)
	at org.jacoco.agent.rt.internal_43f5073.Offline.getProbes(Offline.java:60)
	at com.Slack.SlackApp.$jacocoInit(SlackApp.java)
	at com.Slack.SlackApp.<init>(SlackApp.java)
	at java.lang.Class.newInstance(Native Method)
	at android.app.Instrumentation.newApplication(Instrumentation.java:996)
	at android.app.Instrumentation.newApplication(Instrumentation.java:981)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:573)
	... 9 more
Caused by: java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)
	at libcore.io.IoBridge.open(IoBridge.java:452)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
	at org.jacoco.agent.rt.internal_43f5073.output.FileOutput.openFile(FileOutput.java:68)
	at org.jacoco.agent.rt.internal_43f5073.output.FileOutput.startup(FileOutput.java:50)
	at org.jacoco.agent.rt.internal_43f5073.Agent.startup(Agent.java:129)
	at org.jacoco.agent.rt.internal_43f5073.Agent.getInstance(Agent.java:54)
	at org.jacoco.agent.rt.internal_43f5073.Offline.getRuntimeData(Offline.java:39)
	... 16 more
Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:438)
	... 22 more
```

**Comment by ZacSweers** [comment]
Nevermind, found #968
