### ISSUE TITLE
Using --xml option of jacococli report fails if the folder does not exist

### ISSUE THREAD

**Issue by wlad** [jacoco/jacoco#1100]
### Steps to reproduce

* JaCoCo version: 0.8.6.202009150832
* Operating system: Ubuntu 19.10 eoan
* Tool integration: CLI 
* Complete executable reproducer: see failing step "Generate SDK IT Coverage Report" in CircleCI build:  https://app.circleci.com/pipelines/github/ehrbase/ehrbase/1273/workflows/6689b8e5-f276-4c14-ab24-c8676dfab5b0/jobs/15005

* Steps: 

  - Call `jacococli report` to generate a report with `--xml` option (below example is shortened for readability)
```
java -jar ~/jacoco/lib/jacococli.jar report test-coverage/target/jacoco-sdk-it-coverage.exec \
  --classfiles api/target/classes/ \
  --sourcefiles api/src/main/java/ \
  --html test-coverage/sdk-it-coverage-report \
  --xml test-coverage/sdk-it-coverage-report/jacoco.xml \
  --name "EHRbase Code Coverage w/ SDK Integration Tests"
```

### Expected behaviour
```
[INFO] Loading execution data file /home/wlad/projects/ec/ehrbase/test-coverage/target/jacoco-sdk-it-coverage.exec.
[INFO] Analyzing 519 classes.
```
No exception.
And **jacoco.xml** file created inside **test-coverage/sdk-it-coverage-report/**

> NOTE:
> when using `--xml jacoco.xml`  without a path, the file is created outside the html folder, which is not desired behaviour
> So intuitively I'd expect that either --xml can take a filename with relative or absolut path or place the file inside html folder defined by --html if filename is provided without a path

### Actual behaviour
```
[INFO] Loading execution data file /home/circleci/projects/test-coverage/target/jacoco-sdk-it-coverage.exec.
[INFO] Analyzing 519 classes.
Exception in thread "main" java.io.FileNotFoundException: test-coverage/sdk-it-coverage-report/jacoco.xml
(No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at org.jacoco.cli.internal.commands.Report.createReportVisitor(Report.java:148)
	at org.jacoco.cli.internal.commands.Report.writeReports(Report.java:136)
	at org.jacoco.cli.internal.commands.Report.execute(Report.java:86)
	at org.jacoco.cli.internal.Main.execute(Main.java:90)
	at org.jacoco.cli.internal.Main.main(Main.java:105)
```

### Workaround
Create the folder, where jacoco.xml will be written to before calling `jacococli report`
```
mkdir -p test-coverage/sdk-it-coverage-report/
```

**Comment by marchof** [comment]
The same hold true for the CSV output. Missing parent files are not created. Also the same happens with our Maven goal and Ant task.

**Comment by the-end-sea-of-the-world** [comment]
Hello, I want to fix this. I added checks on input path and would create if it does not exist.
