### ISSUE TITLE
StackOverflowError with Maven/Sonar

### ISSUE THREAD

**Issue by Zlika** [jacoco/jacoco#112]
Hello !
I have a StackOverflowError caused by JaCoCo (v 0.6.1) when using the sonar:sonar Maven goal :

[INFO] --- sonar-maven-plugin:2.0:sonar (default-cli) @ project ---
[INFO] Sonar version: 3.5.1
[INFO] [17:20:33.790] Load batch settings
[INFO] [17:20:33.992] User cache: C:\Users\Thomas.sonar\cache
[INFO] [17:20:34.008] Install plugins
[INFO] [17:20:37.658] -------------  Executing Project Scan
[INFO] [17:20:39.390] Install JDBC driver
[INFO] [17:20:39.406] Apply project exclusions
[WARN] [17:20:39.406] H2 database should be used for evaluation purpose only
[INFO] [17:20:39.406] Create JDBC datasource for jdbc:h2:tcp://localhost/sonar
[INFO] [17:20:39.640] Initializing Hibernate
[INFO] [17:20:46.207] -------------  Inspecting library
[INFO] [17:20:46.207] Load module settings
[INFO] [17:20:46.956] Quality profile : [name=Sonar way,language=java]
[INFO] [17:20:47.018] Excluded tests: 
[INFO] [17:20:47.018]   *_/package-info.java
[INFO] [17:20:47.206] Configure Maven plugins
[INFO] [17:20:47.299] Compare to previous analysis
[INFO] [17:20:47.346] Compare over 5 days (2013-06-07)
[INFO] [17:20:47.362] Compare over 30 days (2013-05-13)
[INFO] [17:20:47.580] Deleting C:\Users\Thomas\Desktop\project\project-lib\target\jacoco.exec
[INFO] [17:20:47.642] JaCoCo agent (version 0.6.2.201302030002) extracted: C:\Users\Thomas\AppData\Local\Temp\jacocoagent4280349415394585371.jar
[INFO] [17:20:47.642] JVM options: -javaagent:C:\Users\Thomas\AppData\Local\Temp\jacocoagent4280349415394585371.jar=destfile=target/jacoco.exec,excludes=__javassist_\* ${coverageAgent}
[INFO] [17:20:47.736] Initializer FindbugsMavenInitializer...
[INFO] [17:20:47.752] Initializer FindbugsMavenInitializer done: 16 ms
[INFO] [17:20:47.752] Execute maven plugin maven-surefire-plugin...
[INFO] [17:20:47.752] Execute org.apache.maven.plugins:maven-surefire-plugin:2.15:test...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building library 0.7-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-surefire-plugin:2.15:test (default-cli) @ project-lib ---
[INFO] Surefire report directory: C:\Users\Thomas\Desktop\project\project-lib\target\surefire-reports

---
##  T E S T S

java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:382)
    at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:397)
Caused by: java.lang.StackOverflowError
    at org.jacoco.agent.rt_6l8m50.core.data.ExecutionDataStore.$jacocoInit(ExecutionDataStore.java)
    at org.jacoco.agent.rt_6l8m50.core.data.ExecutionDataStore.get(ExecutionDataStore.java)
    at org.jacoco.agent.rt_6l8m50.core.runtime.ExecutionDataAccess.getExecutionData(ExecutionDataAccess.java:64)
    at org.jacoco.agent.rt_6l8m50.core.runtime.ExecutionDataAccess.equals(ExecutionDataAccess.java:162)
    at org.jacoco.agent.rt_6l8m50.core.data.ExecutionData.$jacocoInit(ExecutionData.java)
    at org.jacoco.agent.rt_6l8m50.core.data.ExecutionData.<init>(ExecutionData.java)
    at org.jacoco.agent.rt_6l8m50.core.data.ExecutionDataStore.get(ExecutionDataStore.java:114)

```
(... lots of lines ...)

at org.jacoco.agent.rt_6l8m50.core.runtime.ExecutionDataAccess.equals(ExecutionDataAccess.java:162)
at org.jacoco.agent.rt_6l8m50.core.data.ExecutionData.$jacocoInit(ExecutionData.java)
at org.jacoco.agent.rt_6l8m50.core.data.ExecutionData.<init>(ExecutionData.java)
at org.jacoco.agent.rt_6l8m50.core.data.ExecutionDataStore.get(ExecutionDataStore.java:114)
at org.jacoco.agent.rt_6l8m50.core.runtime.ExecutionDataAccess.getExecutionData(ExecutionDataAccess.java:64)
at org.jacoco.agent.rt_6l8m50.core.runtime.ExecutionDataAccess.equals(ExecutionDataAccess.java:162)
```

FATAL ERROR in native method: processing of -javaagent failed
Exception in thread "main"

**Comment by tmaus** [comment]
Thanks for your help guys .. appreciated. 
I disabled Jacoco coverage in TC and triggered its execution in the Gradle build script as this one is more versatile. 
That did the job
