### ISSUE TITLE
Allow wildcard in report with command line

### ISSUE THREAD

**Issue by ridKnight** [jacoco/jacoco#1128]
### Scenario

* JaCoCo version: 0.8.6
* Operating system: MacOS 10.14
* Tool integration: Command Line

### Current Behaviour
Command:
```text
java -jar jacococli.jar report jacoco.exec  --classfiles arius*/target/classes --sourcefiles arius*/src/main/java
```
Returns: 
```text
Exception in thread "main" java.io.FileNotFoundException: arius-admin-common/target/classes (It's a directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.jacoco.cli.internal.core.tools.ExecFileLoader.load(ExecFileLoader.java:72)
	at org.jacoco.cli.internal.commands.Report.loadExecutionData(Report.java:99)
	at org.jacoco.cli.internal.commands.Report.execute(Report.java:83)
	at org.jacoco.cli.internal.Main.execute(Main.java:90)
	at org.jacoco.cli.internal.Main.main(Main.java:105)
```
When I specify --classfiles or --sourcefiles with a '*', it returned such a FileNotFoundException. It may be helpful if
I can batch include or exclude files or directories with command line.
### Wanted Behaviour
Allow using wildcards or provide `--includes` or `--excludes` in command line just like the usage of 'jacocoagent.jar'.

#### Thanks!

**Comment by marchof** [comment]
Because the wildcard is expanded by the shell and `--classfiles` expects a single value only.

I'm sure there is some shell magic to prefix every expanded value with `--classfiles`. The same hold true for `--sourcefiles`.
