### ISSUE TITLE
An error occurred in the report phase using Jacobo Maven plugin

### ISSUE THREAD

**Issue by afreetgo** [jacoco/jacoco#1159]
jacoco-maven-plugin:0.8.6
org.jacoco.agent:0.8.6
junit:4.13
hamcrest:1.3
mockito:2.28.2
powermock:2.0.7

pom.xml
```
...
   <dependencies>
       ...
                <dependency>
			<groupId>org.jacoco</groupId>
			<artifactId>org.jacoco.agent</artifactId>
			<version>0.8.6</version>
			<classifier>runtime</classifier>
			<scope>test</scope>
		</dependency>
	</dependencies>
                         <plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19.1</version>
				<configuration>
					<systemPropertyVariables>
						<jacoco-agent.destfile>${project.build.directory}/jacoco.exec</jacoco-agent.destfile>
					</systemPropertyVariables>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>0.8.6</version>
				<executions>
					<execution>
						<id>default-instrument</id>
						<goals>
							<goal>instrument</goal>
						</goals>
					</execution>
					<execution>
						<id>default-restore-instrumented-classes</id>
						<goals>
							<goal>restore-instrumented-classes</goal>
						</goals>
					</execution>
					<execution>
						<id>pre-unit-test</id>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
						<configuration>
						    <append>false</append>
							<destFile>${basedir}/target/jacoco.exec</destFile>
							<propertyName>surefireArgLine</propertyName>
						</configuration>
					</execution>
					<execution>
						<id>post-unit-test</id>
						<phase>test</phase>
						<goals>
							<goal>report</goal>
						</goals>
						<configuration>
							<dataFile>${basedir}/target/jacoco.exec</dataFile>
						</configuration>
					</execution>
				</executions>
			</plugin>
...
```

error message:

```
Results :

Tests run: 167, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.6:report (post-unit-test) @ vems_unicorn_routing ---
[DEBUG] Configuring mojo org.jacoco:jacoco-maven-plugin:0.8.6:report from plugin realm ClassRealm[plugin>org.jacoco:jacoco-maven-plugin:0.8.6, parent: sun.misc.Launcher$AppClassLoader@4e25154f]
[DEBUG] Setting property: classpath.resource.loader.class => 'org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader'.
[DEBUG] Setting property: site.resource.loader.class => 'org.codehaus.plexus.velocity.SiteResourceLoader'.
[DEBUG] Setting property: velocimacro.messages.on => 'false'.
[DEBUG] Setting property: resource.loader => 'classpath,site'.
[DEBUG] Setting property: runtime.log.invalid.references => 'false'.
[DEBUG] Setting property: resource.manager.logwhenfound => 'false'.
[DEBUG] Setting property: velocimacro.permissions.allow.inline.to.replace.global => 'true'.
[DEBUG] *******************************************************************
[DEBUG] Starting Apache Velocity v1.5 (compiled: 2007-02-22 08:52:29)
[DEBUG] RuntimeInstance initializing.
[DEBUG] Default Properties File: org\apache\velocity\runtime\defaults\velocity.properties
[DEBUG] LogSystem has been deprecated. Please use a LogChute implementation.
[DEBUG] Default ResourceManager initializing. (class org.apache.velocity.runtime.resource.ResourceManagerImpl)
[DEBUG] ResourceLoader instantiated: org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader
[DEBUG] ResourceLoader instantiated: org.codehaus.plexus.velocity.SiteResourceLoader
[DEBUG] ResourceCache: initialized (class org.apache.velocity.runtime.resource.ResourceCacheImpl)
[DEBUG] Default ResourceManager initialization complete.
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Literal
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Macro
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Parse
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Include
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Foreach
[DEBUG] Created '20' parsers.
[DEBUG] Velocimacro : initialization starting.
[DEBUG] Velocimacro : allowInline = true : VMs can be defined inline in templates
[DEBUG] Velocimacro : allowInlineToOverride = true : VMs defined inline may replace previous VM definitions
[DEBUG] Velocimacro : allowInlineLocal = false : VMs defined inline will be global in scope if allowed.
[DEBUG] Velocimacro : autoload off : VM system will not automatically reload global library macros
[DEBUG] Velocimacro : Velocimacro : initialization complete.
[DEBUG] RuntimeInstance successfully initialized.
[DEBUG] Configuring mojo 'org.jacoco:jacoco-maven-plugin:0.8.6:report' with basic configurator -->
[DEBUG]   (f) dataFile = D:\gitworkspace\xxxx\target\jacoco.exec
[DEBUG]   (f) outputDirectory = D:\gitworkspace\xxxx\target\site\jacoco
[DEBUG]   (f) outputEncoding = UTF-8
[DEBUG]   (f) project = MavenProject: com.xxx.xxx:xxxx:0.5.2 @ D:\gitworkspace\xxxx\pom.xml
[DEBUG]   (f) skip = false
[DEBUG]   (f) sourceEncoding = UTF-8
[DEBUG]   (f) title = xxxx
[DEBUG] -- end configuration --
[INFO] Loading execution data file D:\gitworkspace\xxxx\target\jacoco.exec
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:34 min
[INFO] Finished at: 2021-03-04T09:44:30+08:00
[INFO] Final Memory: 73M/1014M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.6:report (post-unit-test) on project xxxx: An error has occurred in JaCoCo report generation. Error while creating report: Error while analyzing D:\gitworkspace\xxxx\target\classes\com\xxx\xxx\App.class. Cannot process instrumented class com/xxx/xxx/App. Please supply original non-instrumented classes. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.6:report (post-unit-test) on project vems_unicorn_routing: An error has occurred in JaCoCo report generation.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An error has occurred in JaCoCo report generation.
	at org.jacoco.maven.AbstractReportMojo.execute(AbstractReportMojo.java:168)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.apache.maven.reporting.MavenReportException: Error while creating report: Error while analyzing D:\gitworkspace\xxxx\target\classes\com\xxx\xxx\App.class.
	at org.jacoco.maven.AbstractReportMojo.executeReport(AbstractReportMojo.java:184)
	at org.jacoco.maven.AbstractReportMojo.execute(AbstractReportMojo.java:166)
	... 22 more
Caused by: java.io.IOException: Error while analyzing D:\gitworkspace\xxxx\target\classes\com\xxx\xxx\App.class.
	at org.jacoco.core.analysis.Analyzer.analyzerError(Analyzer.java:162)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:134)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:157)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:193)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:226)
	at org.jacoco.maven.ReportSupport.processProject(ReportSupport.java:202)
	at org.jacoco.maven.ReportSupport.processProject(ReportSupport.java:185)
	at org.jacoco.maven.ReportMojo.createReport(ReportMojo.java:74)
	at org.jacoco.maven.AbstractReportMojo.executeReport(AbstractReportMojo.java:181)
	... 23 more
Caused by: java.lang.IllegalStateException: Cannot process instrumented class com/xxx/xxx/App. Please supply original non-instrumented classes.
	at org.jacoco.core.internal.instr.InstrSupport.assertNotInstrumented(InstrSupport.java:238)
	at org.jacoco.core.internal.analysis.ClassAnalyzer.visitField(ClassAnalyzer.java:135)
	at org.objectweb.asm.ClassVisitor.visitField(ClassVisitor.java:339)
	at org.objectweb.asm.ClassReader.readField(ClassReader.java:1111)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:713)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:116)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:132)
	... 30 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

The project uses powermock. If you remove the report phase and compile with Jenkins + sonar, you can collect coverage information. This is the report phase of Jacobo Maven plugin. Does powermock not support it?

**Comment by marchof** [comment]
See error message:

> Cannot process instrumented class com/xxx/xxx/App. Please supply original non-instrumented classes.

If you decide to instrument the class files in disk (which we do not recommend) you cannot use the instrumented classes for report generation. You need the original classes for this.

The documentation comes with two working Maven examples: https://www.jacoco.org/jacoco/trunk/doc/

**Comment by Godin** [comment]
Notice that in your log there is no execution of `org.jacoco:jacoco-maven-plugin:0.8.6:restore-instrumented-classes` between tests and generation of reports

In your `pom.xml`

```
					<execution>
						<id>post-unit-test</id>
						<phase>test</phase>
						<goals>
							<goal>report</goal>
						</goals>
						<configuration>
							<dataFile>${basedir}/target/jacoco.exec</dataFile>
						</configuration>
					</execution>
```

goal `report` is bound to phase `test`,

whereas

```
					<execution>
						<id>default-restore-instrumented-classes</id>
						<goals>
							<goal>restore-instrumented-classes</goal>
						</goals>
					</execution>
```

goal `restore-instrumented-classes` uses default phase, which is `prepare-package` as described in documentation at https://www.jacoco.org/jacoco/trunk/doc/restore-instrumented-classes-mojo.html

Phase `prepare-package` is after phase `test` - see also https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html
