### ISSUE TITLE
Support Java 18-EA

### ISSUE THREAD

**Issue by garydgregory** [jacoco/jacoco#1199]
JaCoCo on Java 18-EA fails with errors like:

```
[INFO] -------------------------------------------------------

[INFO]  T E S T S

[INFO] -------------------------------------------------------

java.lang.instrument.IllegalClassFormatException: Error while instrumenting javax/sql/DataSource.

	at org.jacoco.agent.rt.internal_3570298.CoverageTransformer.transform(CoverageTransformer.java:94)

	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)

	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)

	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)

	at java.base/java.lang.ClassLoader.defineClass2(Native Method)

	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1103)

	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:182)

	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:821)

	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:741)

	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:665)

	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:700)

	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:669)

	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)

	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)

	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

	at java.base/java.lang.ClassLoader.defineClass1(Native Method)

	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)

	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)

	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)

	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)

	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)

	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)

	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)

	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)

	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)

	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)

	at org.junit.platform.commons.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:1455)

	at org.junit.platform.commons.util.ReflectionUtils.findMethod(ReflectionUtils.java:1304)

	at org.junit.platform.commons.util.ReflectionUtils.isMethodPresent(ReflectionUtils.java:1205)

	at org.junit.jupiter.engine.discovery.predicates.IsTestClassWithTests.hasTestOrTestFactoryOrTestTemplateMethods(IsTestClassWithTests.java:50)

	at org.junit.jupiter.engine.discovery.predicates.IsTestClassWithTests.test(IsTestClassWithTests.java:46)

	at org.junit.jupiter.engine.discovery.ClassSelectorResolver.resolve(ClassSelectorResolver.java:67)

	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:134)

	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)

	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)

	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)

	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)

	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)

	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)

	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)

	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)

	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:185)

	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:125)

	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:91)

	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:82)

	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)

	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:46)

	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)

	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:168)

	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:155)

	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:120)

	at org.apache.maven.surefire.junitplatform.TestPlanScannerFilter.accept(TestPlanScannerFilter.java:56)

	at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:102)

	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.scanClasspath(JUnitPlatformProvider.java:143)

	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)

	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)

	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)

	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)

	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

Caused by: java.io.IOException: Error while instrumenting javax/sql/DataSource.

	at org.jacoco.agent.rt.internal_3570298.core.instr.Instrumenter.instrumentError(Instrumenter.java:160)

	at org.jacoco.agent.rt.internal_3570298.core.instr.Instrumenter.instrument(Instrumenter.java:110)

	at org.jacoco.agent.rt.internal_3570298.CoverageTransformer.transform(CoverageTransformer.java:92)

	... 60 more

Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 62

	at org.jacoco.agent.rt.internal_3570298.asm.ClassReader.<init>(ClassReader.java:196)

	at org.jacoco.agent.rt.internal_3570298.asm.ClassReader.<init>(ClassReader.java:177)

	at org.jacoco.agent.rt.internal_3570298.asm.ClassReader.<init>(ClassReader.java:163)

	at org.jacoco.agent.rt.internal_3570298.core.internal.instr.InstrSupport.classReaderFor(InstrSupport.java:280)

	at org.jacoco.agent.rt.internal_3570298.core.instr.Instrumenter.instrument(Instrumenter.java:76)

	at org.jacoco.agent.rt.internal_3570298.core.instr.Instrumenter.instrument(Instrumenter.java:108)

	... 61 more
```

**Comment by marchof** [comment]
@Godin is already working on it! See #1198
