### ISSUE TITLE
Missing line coverage for several examples

### ISSUE THREAD

**Issue by andre15silva** [jacoco/jacoco#1223]
### Steps to reproduce

* JaCoCo version:  `0.8.7.202105040129`
* Operating system: Linux
* Tool integration: Maven
* Complete executable reproducer: https://github.com/andre15silva/jacoco-bugs/tree/main/cm1
* Steps:
```bash
cd cm1/
mvn clean -Dtest="org.apache.commons.math.stat.univariate.rank.PercentileTest#testFailingExample" test
mvn jacoco:report
```

### Expected behaviour

Class `org.apache.commons.math.stat.univariate.rank.Percentile`'s coverage should include lines `143` to `151` (this excludes line `152` where an exception is thrown during the test execution).

### Actual behaviour

Coverage stops at line `142`.

![pic-selected-210922-1318-17](https://user-images.githubusercontent.com/31904862/134342101-d7a3b4b8-62fe-4655-a79c-5c1c1bb118dc.png)

We know that these lines should be covered, otherwise the exception that ends the test wouldn't be thrown.

**Comment by marchof** [comment]
Are you sure `System.arraycopy()` does not throw an Exception?

**Comment by andre15silva** [comment]
Hi!

> Are you sure `System.arraycopy()` does not throw an Exception?

Yes. Otherwise the test stack trace wouldn't include line `152`:
```
Running org.apache.commons.math.stat.univariate.rank.PercentileTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.011 sec <<< FAILURE!
testHighPercentile(org.apache.commons.math.stat.univariate.rank.PercentileTest)  Time elapsed: 0.009 sec  <<< ERROR!
java.lang.ArrayIndexOutOfBoundsException: 3
	at org.apache.commons.math.stat.univariate.rank.Percentile.evaluate(Percentile.java:152)
	at org.apache.commons.math.stat.univariate.rank.Percentile.evaluate(Percentile.java:105)
	at org.apache.commons.math.stat.univariate.AbstractUnivariateStatistic.evaluate(AbstractUnivariateStatistic.java:71)
	at org.apache.commons.math.stat.univariate.rank.PercentileTest.testHighPercentile(PercentileTest.java:105)
```

Adding to that, when I run the intellij-coverage agent through IntellIJ these lines are included. 
When I run the Jacoco agent either through IntellIJ or through Maven they are not included.

**Comment by andre15silva** [comment]
A similar issue happens in a different project too:

### Steps to reproduce

* JaCoCo version:  `0.8.7.202105040129`
* Operating system: Linux
* Tool integration: Maven
* Complete executable reproducer: https://github.com/andre15silva/jacoco-bugs/tree/main/cl4
* Steps:
```bash
cd cm1/
mvn clean -Dtest="org.apache.commons.lang.text.StrBuilderTest" test
mvn jacoco:report
```

### Expected behaviour

Class `org.apache.commons.lang.text.StrBuilder`'s coverage should include line `1460` (this excludes line `1463` where an exception is thrown during the test execution).

### Actual behaviour

Coverage stops at line `1459`.

![pic-selected-210922-1823-15](https://user-images.githubusercontent.com/31904862/134391762-50b46708-b3b2-4943-b32a-48e16624e67a.png)

We know that these lines should be covered, otherwise the exceptions that the tests thrown wouldn't include line `1463`:
```
testIndexOfString_10(org.apache.commons.lang.text.StrBuilderTest)  Time elapsed: 0.011 sec  <<< ERROR!
java.lang.NullPointerException
	at org.apache.commons.lang.text.StrBuilder.indexOf(StrBuilder.java:1463)
	at org.apache.commons.lang.text.StrBuilder.indexOf(StrBuilder.java:1445)
	at org.apache.commons.lang.text.StrBuilderTest.testIndexOfString_10(StrBuilderTest.java:80)

testIndexOfStringInt_12(org.apache.commons.lang.text.StrBuilderTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NullPointerException
	at org.apache.commons.lang.text.StrBuilder.indexOf(StrBuilder.java:1463)
	at org.apache.commons.lang.text.StrBuilderTest.testIndexOfStringInt_12(StrBuilderTest.java:85)
```

**Comment by andre15silva** [comment]
Again, similar issue in another version with a different test, now with JUnit4:

### Steps to reproduce

* JaCoCo version:  `0.8.7.202105040129`
* Operating system: Linux
* Tool integration: Maven
* Complete executable reproducer: https://github.com/andre15silva/jacoco-bugs/tree/main/cl2
* Steps:
```bash
cd cl2/
mvn clean -Dtest="org.apache.commons.lang.StringUtilsTest" test
mvn jacoco:report
```

### Expected behaviour

Class `org.apache.commons.lang.StringUtils`'s coverage should include lines `1550` and `1551` (excluding line `1554`, where the exception is thrown)

### Actual behaviour

No coverage for that method is returned.

![pic-selected-210924-1435-32](https://user-images.githubusercontent.com/31904862/134683713-985533b3-0731-4285-b5ff-0395d7646e0f.png)

We know that these lines should be covered, otherwise the exceptions that the tests thrown wouldn't include line `1554`. The coverage agent of IntellIJ returns all these 3 lines as covered.:
```
testChopNewLine_8(org.apache.commons.lang.StringUtilsTest)  Time elapsed: 0.012 sec  <<< ERROR!
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.charAt(String.java:658)
	at org.apache.commons.lang.StringUtils.chopNewline(StringUtils.java:1054)
	at org.apache.commons.lang.StringUtilsTest.testChopNewLine_8(StringUtilsTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:35)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:146)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:145)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
```

**Comment by andre15silva** [comment]
If you have any tip or suggestion on where to start debugging I'd very much appreciate! I want to try to fix these bugs.

**Comment by marchof** [comment]
Hi @andre15silva we assume this is a known limitation, see [FAQ](https://www.jacoco.org/jacoco/trunk/doc/faq.html):

> **Source code lines with exceptions show no coverage. Why?**
>
> JaCoCo determines code execution with so called probes. Probes are inserted into the control flow at certain positions. Code is considered as executed when a subsequent probe has been executed. In case of exceptions such a sequence of instructions is aborted somewhere in the middle and the corresponding line of source code is not marked as covered.

As all the red lines do not call methods we don't add additional probes between the lines.

In addition we have open issue #321 where we are reluctant to merge because it will break exec file compatibility.

**Comment by andre15silva** [comment]
Thanks for the useful info.

Two questions:

- Is the website collaborative? If so, could you point me to it? I was not able to find it. I wanted to contribute with a clarification of that FAQ.
- Do you think it is feasible to instrument every line of code? If so, do you think you could point me, in the source code, where I can do that modification?

Thank you for your time! :)

**Comment by marchof** [comment]
The source code of the Website is included in this repository. Here is the FAQ: https://github.com/jacoco/jacoco/blob/master/org.jacoco.doc/docroot/doc/faq.html

In general JaCoCo works without debug information (line numbers). Instrumentation is always a trade-off between granularity and runtime performance. Therefore we decided against probes after every line. You can read details about instrumentation used in JaCoCo here: https://www.jacoco.org/jacoco/trunk/doc/flow.html
