### ISSUE TITLE
JaCoCo randomly fails to generate report

### ISSUE THREAD

**Issue by ed-devops-d2** [jacoco/jacoco#1225]
Greetings, 

I'm using quarkus-jacoco plugin with Maven. Although most of times it generates the report under target/jacoco-report/jacoco.xml, a few times randomly it fails and results in target/jacoco-report/error.txt

The error.txt results:

`Failed to generate Jacoco reports
java.io.EOFException
	at java.base/java.io.DataInputStream.readUnsignedShort(DataInputStream.java:345)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:594)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:569)
	at org.jacoco.core.data.ExecutionDataReader.readExecutionData(ExecutionDataReader.java:149)
	at org.jacoco.core.data.ExecutionDataReader.readBlock(ExecutionDataReader.java:116)
	at org.jacoco.core.data.ExecutionDataReader.read(ExecutionDataReader.java:93)
	at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:60)
	at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:74)
	at io.quarkus.jacoco.runtime.ReportCreator.run(ReportCreator.java:72)
	at java.base/java.lang.Thread.run(Thread.java:829)`

I did search and found out other guys talking about EOFException, which indicates that exec file is truncated, but I'm not sure if that's my case here. Any suggestions? 

Thanks in advance!

**Comment by Godin** [comment]
Quoting https://github.com/jacoco/jacoco/issues/980

> `EOFException` indicates that exec file is truncated, i.e. wasn't fully written by an agent. Agent writes exec file at JVM shutdown using `Runtime.addShutdownHook()` API. So please remove existing files and make sure that JVM terminates gracefully and shutdown hooks are executed when you execute your test.
