### ISSUE TITLE
Socket is not finally closed in org.jacoco.examples.ExecutionDataServer

### ISSUE THREAD

**Issue by ganxiyun** [jacoco/jacoco#1243]
### Steps to reproduce

* JaCoCo version:  0.8.8
* Operating system: `5.11.0-38-generic #42~20.04.1-Ubuntu SMP`
* Tool integration: JaCoCo API Usage Examples
* Complete executable reproducer: GitHub Repo
* Steps: 
1. Run `ExecutionDataServer` to receive execution data from TcpClient. 
```
java -cp org.jacoco.core/target/org.jacoco.core-0.8.8-SNAPSHOT.jar:org.jacoco.examples/target/org.jacoco.examples-0.8.8-SNAPSHOT.jar  org.jacoco.examples.ExecutionDataServer
```

2. After a relatively long-term period, we may see following Exceptions (reason unknown)

```
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.net.SocketInputStream.read(SocketInputStream.java:224)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at org.jacoco.core.data.ExecutionDataReader.read(ExecutionDataReader.java:84)
        at org.jacoco.examples.ExecutionDataServer$Handler.run(ExecutionDataServer.java:83)
```

3. Check the connections 
```
netstat -aon | grep 6300
```

### Expected behaviour

No `CLOSE_WAIT` status connection

### Actual behaviour

We could see 

```
tcp6      10      0 127.0.0.1:6300          127.0.0.1:36616         CLOSE_WAIT  off (0.00/0/0)
```

The Socket in `ExecutionDataServer` hasn't been closed.

**Comment by marchof** [comment]
As this example code we want to keep it simple and readable.
