### ISSUE TITLE
Error while instrumenting  xx/xx

### ISSUE THREAD

**Issue by StackRui** [jacoco/jacoco#1304]
I received such an error when using Jenkins + spring boot 2.6.3 + JDK8 + jacoco 0.8.8

```
java.lang.instrument.IllegalClassFormatException: Error while instrumenting io/lettuce/core/event/connection/JfrDisconnectedEvent.
14:38:25  	at org.jacoco.agent.rt.internal_3570298.CoverageTransformer.transform(CoverageTransformer.java:94)
14:38:25  	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
14:38:25  	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
14:38:25  	at java.lang.ClassLoader.defineClass1(Native Method)
14:38:25  	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
14:38:25  	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
14:38:25  	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
14:38:25  	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
14:38:25  	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
14:38:25  	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
14:38:25  	at java.security.AccessController.doPrivileged(Native Method)
14:38:25  	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
14:38:25  	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
14:38:25  	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
14:38:25  	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
14:38:25  	at io.lettuce.core.internal.LettuceClassUtils.forName(LettuceClassUtils.java:99)
14:38:25  	at io.lettuce.core.internal.LettuceClassUtils.findClass(LettuceClassUtils.java:80)
14:38:25  	at io.lettuce.core.event.jfr.JfrEventRecorder.getEventConstructor(JfrEventRecorder.java:82)
14:38:25  	at io.lettuce.core.event.jfr.JfrEventRecorder.createEvent(JfrEventRecorder.java:102)
14:38:25  	at io.lettuce.core.event.jfr.JfrEventRecorder.record(JfrEventRecorder.java:48)
14:38:25  	at io.lettuce.core.event.DefaultEventBus.publish(DefaultEventBus.java:55)
14:38:25  	at io.lettuce.core.ChannelGroupListener.channelInactive(ChannelGroupListener.java:66)
14:38:25  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
14:38:25  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
14:38:25  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
14:38:25  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
14:38:25  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
14:38:25  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
14:38:25  	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
14:38:25  	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
14:38:25  	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
14:38:25  	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
14:38:25  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
14:38:25  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
14:38:25  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
14:38:25  	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
14:38:25  	at java.lang.Thread.run(Thread.java:750)
14:38:25  Caused by: java.io.IOException: Error while instrumenting io/lettuce/core/event/connection/JfrDisconnectedEvent.
14:38:25  	at org.jacoco.agent.rt.internal_3570298.core.instr.Instrumenter.instrumentError(Instrumenter.java:160)
14:38:25  	at org.jacoco.agent.rt.internal_3570298.core.instr.Instrumenter.instrument(Instrumenter.java:110)
14:38:25  	at org.jacoco.agent.rt.internal_3570298.CoverageTransformer.transform(CoverageTransformer.java:92)
14:38:25  	... 36 more
14:38:25  Caused by: java.lang.IllegalStateException: Cannot process instrumented class io/lettuce/core/event/connection/JfrDisconnectedEvent. Please supply original non-instrumented classes.
14:38:25  	at org.jacoco.agent.rt.internal_3570298.core.internal.instr.InstrSupport.assertNotInstrumented(InstrSupport.java:238)
14:38:25  	at org.jacoco.agent.rt.internal_3570298.core.internal.instr.ClassInstrumenter.visitField(ClassInstrumenter.java:56)
14:38:25  	at org.jacoco.agent.rt.internal_3570298.asm.ClassVisitor.visitField(ClassVisitor.java:338)
14:38:25  	at org.jacoco.agent.rt.internal_3570298.asm.ClassReader.readField(ClassReader.java:1114)
14:38:25  	at org.jacoco.agent.rt.internal_3570298.asm.ClassReader.accept(ClassReader.java:716)
14:38:25  	at org.jacoco.agent.rt.internal_3570298.asm.ClassReader.accept(ClassReader.java:401)
14:38:25  	at org.jacoco.agent.rt.internal_3570298.core.instr.Instrumenter.instrument(Instrumenter.java:90)
14:38:25  	at org.jacoco.agent.rt.internal_3570298.core.instr.Instrumenter.instrument(Instrumenter.java:108)
14:38:25  	... 37 more
14:38:25  java.lang.instrument.IllegalClassFormatException: Error while instrumenting io/lettuce/core/event/connection/JfrConnectionDeactivatedEvent.
14:38:25  	at org.jacoco.agent.rt.internal_3570298.CoverageTransformer.transform(CoverageTransformer.java:94)
14:38:25  	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
14:38:25  	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
14:38:25  	at java.lang.ClassLoader.defineClass1(Native Method)
14:38:25  	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
14:38:25  	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
14:38:25  	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
14:38:25  	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
14:38:25  	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
14:38:25  	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
14:38:25  	at java.security.AccessController.doPrivileged(Native Method)
14:38:25  	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
14:38:25  	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
14:38:25  	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
14:38:25  	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
14:38:25  	at io.lettuce.core.internal.LettuceClassUtils.forName(LettuceClassUtils.java:99)
14:38:25  	at io.lettuce.core.internal.LettuceClassUtils.findClass(LettuceClassUtils.java:80)
14:38:25  	at io.lettuce.core.event.jfr.JfrEventRecorder.getEventConstructor(JfrEventRecorder.java:82)
14:38:25  	at io.lettuce.core.event.jfr.JfrEventRecorder.createEvent(JfrEventRecorder.java:102)
14:38:25  	at io.lettuce.core.event.jfr.JfrEventRecorder.record(JfrEventRecorder.java:48)
14:38:25  	at io.lettuce.core.event.DefaultEventBus.publish(DefaultEventBus.java:55)
14:38:25  	at io.lettuce.core.ConnectionEventTrigger.channelInactive(ConnectionEventTrigger.java:65)
14:38:25  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
14:38:25  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
14:38:25  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
14:38:25  	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
14:38:25  	at io.lettuce.core.protocol.CommandHandler.channelInactive(CommandHandler.java:371)
14:38:25  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
14:38:25  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
14:38:25  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
14:38:25  	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
14:38:25  	at io.lettuce.core.protocol.RedisHandshakeHandler.channelInactive(RedisHandshakeHandler.java:89)
14:38:25  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
14:38:25  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
14:38:25  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
14:38:25  	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
14:38:25  	at io.lettuce.core.ChannelGroupListener.channelInactive(ChannelGroupListener.java:69)
14:38:25  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
14:38:25  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
14:38:25  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
14:38:25  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
14:38:25  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
14:38:25  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
14:38:25  	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
14:38:25  	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
14:38:25  	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
14:38:25  	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
14:38:25  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
14:38:25  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
14:38:25  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
14:38:25  	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
14:38:25  	at java.lang.Thread.run(Thread.java:750)
14:38:25  Caused by: java.io.IOException: Error while instrumenting io/lettuce/core/event/connection/JfrConnectionDeactivatedEvent.
14:38:25  	at org.jacoco.agent.rt.internal_3570298.core.instr.Instrumenter.instrumentError(Instrumenter.java:160)
14:38:25  	at org.jacoco.agent.rt.internal_3570298.core.instr.Instrumenter.instrument(Instrumenter.java:110)
14:38:25  	at org.jacoco.agent.rt.internal_3570298.CoverageTransformer.transform(CoverageTransformer.java:92)
14:38:25  	... 51 more
14:38:25  Caused by: java.lang.IllegalStateException: Cannot process instrumented class io/lettuce/core/event/connection/JfrConnectionDeactivatedEvent. Please supply original non-instrumented classes.
14:38:25  	at org.jacoco.agent.rt.internal_3570298.core.internal.instr.InstrSupport.assertNotInstrumented(InstrSupport.java:238)
14:38:25  	at org.jacoco.agent.rt.internal_3570298.core.internal.instr.ClassInstrumenter.visitField(ClassInstrumenter.java:56)
14:38:25  	at org.jacoco.agent.rt.internal_3570298.asm.ClassVisitor.visitField(ClassVisitor.java:338)
14:38:25  	at org.jacoco.agent.rt.internal_3570298.asm.ClassReader.readField(ClassReader.java:1114)
14:38:25  	at org.jacoco.agent.rt.internal_3570298.asm.ClassReader.accept(ClassReader.java:716)
14:38:25  	at org.jacoco.agent.rt.internal_3570298.asm.ClassReader.accept(ClassReader.java:401)
14:38:25  	at org.jacoco.agent.rt.internal_3570298.core.instr.Instrumenter.instrument(Instrumenter.java:90)
14:38:25  	at org.jacoco.agent.rt.internal_3570298.core.instr.Instrumenter.instrument(Instrumenter.java:108)
14:38:25  	... 52 more
```

----------------------->
Why did I receive such an error? I can't understand it at all. Is it the reason for JDK? My current JDK version is jdk8

**Comment by Godin** [comment]
You're trying to apply JaCoCo instrumentation twice on the same classes, which is misconfiguration - hence error

```
Caused by: java.lang.IllegalStateException:
Cannot process instrumented class io/lettuce/core/event/connection/JfrConnectionDeactivatedEvent.
Please supply original non-instrumented classes.
```

**Comment by wapkch** [comment]
@StackRui Hi! Has this problem been solved? I am also facing the same problem now when upgrading springboot 2.6.x. Can you provide some suggestions?

**Comment by coolbeevip** [comment]
> @StackRui Hi! Has this problem been solved? I am also facing the same problem now when upgrading springboot 2.6.x. Can you provide some suggestions?

same issue
