### ISSUE TITLE
Jacoco reports error after changing Gradle version

### ISSUE THREAD

**Issue by manymonsters** [jacoco/jacoco#1319]
THIS IS A BUG TRACKER ONLY. FOR QUESTIONS PLEASE CHECK FAQ OR USE FORUM:

http://www.jacoco.org/jacoco/trunk/doc/faq.html

https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Please understand that
ISSUES WITHOUT FOLLOWING INFORMATION WILL BE CLOSED WITHOUT COMMENTS!
Thank you for filling bug report!

### Steps to reproduce

* JaCoCo version: 0.8.2
* Operating system: Android
* Tool integration: Gradle
* Complete executable reproducer: (e.g. GitHub Repo)
* Steps: (what exactly are you doing with the above reproducer?)

When I was using Gradle 7.2, there was no problem with code coverage, but after I recently upgraded Gradle to 7.3.3, the .ec files are all 0 Bytes

### Actual behaviour

java.lang.reflect.InvocationTargetException
Caused by: java.lang.IllegalStateException: JaCoCo agent not started.
        at org.jacoco.agent.rt.internal_3570298.Agent.getInstance(Agent.java:77)
        at org.jacoco.agent.rt.RT.getAgent(RT.java:33)

(In case of exceptions provide FULL STACKTRACE)

**Comment by marchof** [comment]
Can you please provide the *full* stacktrace?

**Comment by manymonsters** [comment]
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.monster.test.appium.espresso.TestApplication.onTestFinished(TestApplication.kt:60)
        at com.monster.test.appium.espresso.jacoco.UITestBroadcastReceiver.onReceive(UITestBroadcastReceiver.kt:19)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1558)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at com.monster.libcrashhandler.CrashHandler.setCrashHandler$lambda-6(CrashHandler.kt:230)
        at com.monster.libcrashhandler.CrashHandler.$r8$lambda$QnsRQAjU9rzH-m6zacxgeGWFy5Y(Unknown Source:0)
        at com.monster.libcrashhandler.CrashHandler$$ExternalSyntheticLambda1.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.IllegalStateException: JaCoCo agent not started.
        at org.jacoco.agent.rt.internal_3570298.Agent.getInstance(Agent.java:77)
        at org.jacoco.agent.rt.RT.getAgent(RT.java:33)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.monster.test.appium.espresso.TestApplication.onTestFinished(TestApplication.kt:60) 
        at com.monster.test.appium.espresso.jacoco.UITestBroadcastReceiver.onReceive(UITestBroadcastReceiver.kt:19) 
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1558) 
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:224) 
        at com.monster.libcrashhandler.CrashHandler.setCrashHandler$lambda-6(CrashHandler.kt:230) 
        at com.monster.libcrashhandler.CrashHandler.$r8$lambda$QnsRQAjU9rzH-m6zacxgeGWFy5Y(Unknown Source:0) 
        at com.monster.libcrashhandler.CrashHandler$$ExternalSyntheticLambda1.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7562) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by manymonsters** [comment]
> Can you please provide the _full_ stacktrace?

java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.monster.test.appium.espresso.TestApplication.onTestFinished(TestApplication.kt:60)
at com.monster.test.appium.espresso.jacoco.UITestBroadcastReceiver.onReceive(UITestBroadcastReceiver.kt:19)
at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1558)
at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:224)
at com.monster.libcrashhandler.CrashHandler.setCrashHandler$lambda-6(CrashHandler.kt:230)
at com.monster.libcrashhandler.CrashHandler.$r8$lambda$QnsRQAjU9rzH-m6zacxgeGWFy5Y(Unknown Source:0)
at com.monster.libcrashhandler.CrashHandler$$ExternalSyntheticLambda1.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:224)
at android.app.ActivityThread.main(ActivityThread.java:7562)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.IllegalStateException: JaCoCo agent not started.
at org.jacoco.agent.rt.internal_3570298.Agent.getInstance(Agent.java:77)
at org.jacoco.agent.rt.RT.getAgent(RT.java:33)
at java.lang.reflect.Method.invoke(Native Method) 
at com.monster.test.appium.espresso.TestApplication.onTestFinished(TestApplication.kt:60) 
at com.monster.test.appium.espresso.jacoco.UITestBroadcastReceiver.onReceive(UITestBroadcastReceiver.kt:19) 
at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1558) 
at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2) 
at android.os.Handler.handleCallback(Handler.java:883) 
at android.os.Handler.dispatchMessage(Handler.java:100) 
at android.os.Looper.loop(Looper.java:224) 
at com.monster.libcrashhandler.CrashHandler.setCrashHandler$lambda-6(CrashHandler.kt:230) 
at com.monster.libcrashhandler.CrashHandler.$r8$lambda$QnsRQAjU9rzH-m6zacxgeGWFy5Y(Unknown Source:0) 
at com.monster.libcrashhandler.CrashHandler$$ExternalSyntheticLambda1.run(Unknown Source:2) 
at android.os.Handler.handleCallback(Handler.java:883) 
at android.os.Handler.dispatchMessage(Handler.java:100) 
at android.os.Looper.loop(Looper.java:224) 
at android.app.ActivityThread.main(ActivityThread.java:7562) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by marchof** [comment]
Ok, looks like this is a Android project. Please note that the JaCoCo Gradle plugin-in and the the Android tools are not developed by us. Please report the issue to these projects. Thx
