### ISSUE TITLE
The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?

### ISSUE THREAD

**Issue by BruceZu** [jacoco/jacoco#1322]
THIS IS A BUG TRACKER ONLY. FOR QUESTIONS PLEASE CHECK FAQ OR USE FORUM:

http://www.jacoco.org/jacoco/trunk/doc/faq.html

https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Please understand that
ISSUES WITHOUT FOLLOWING INFORMATION WILL BE CLOSED WITHOUT COMMENTS!
Thank you for filling bug report!

### Steps to reproduce

* JaCoCo version:  (from right bottom corner of JaCoCo report)
0.8.8

* Operating system: Mac OS Monterey 12.2.1
* Tool integration: Maven / Ant / CLI / API (for others please report to respective project)
Maven and CLI

* Complete executable reproducer: (e.g. GitHub Repo)

* Steps: (what exactly are you doing with the above reproducer?)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <artifactId>sudi</artifactId>
    <groupId>com.bytedance.ad</groupId>
    <version>${release.version}</version>
  </parent>

  <artifactId>report</artifactId>
  <name>Jacoco Report</name>
  <version>${release.version}</version>

  <dependencies>
    <dependency>
      <groupId>com.bytedance.ad</groupId>
      <artifactId>trigger-core</artifactId>
      <version>${release.version}</version>

    </dependency>
    <dependency>
      <groupId>com.bytedance.ad</groupId>
      <version>${release.version}</version>
      <artifactId>trigger-management</artifactId>

    </dependency>
    <dependency>
      <artifactId>trigger-master</artifactId>
      <groupId>com.bytedance.ad.sudi</groupId>
      <version>${release.version}</version>

    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.8.8</version>
        <configuration>
          <footer>Code Coverage Report for SUDI ${release.version}</footer>
          <excludes>
            <!-- Example of excluding classes
            <exclude>**/com/company/config/AutoConfiguration.class</exclude>
            -->
          </excludes>

        </configuration>
        <executions>
          <execution>
            <id>report-aggregate</id>
            <phase>test</phase>
            <goals>
              <goal>report-aggregate</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <!-- This coverage module should never be deployed -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-deploy-plugin</artifactId>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin> 
    </plugins>
  </build>
   
</project>

```
```bash
$mvn --version
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /usr/local/Cellar/maven/3.8.5/libexec
Java version: 1.8.0_322, vendor: Azul Systems, Inc., runtime: /Users/bytedance/Library/Java/JavaVirtualMachines/azul-1.8.0_322/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

```bash
$ mvn clean   org.jacoco:jacoco-maven-plugin:0.8.8:prepare-agent test org.jacoco:jacoco-maven-plugin:0.8.8:report-aggregate  -X -rf :trigger-core
```

### Expected behaviour
create JaCoCo report

### Actual behaviour

```
 at org.jacoco.agent.rt.internal_b6258fc.core.data.ExecutionData.$jacocoInit(ExecutionData.java)
	at org.jacoco.agent.rt.internal_b6258fc.core.data.ExecutionData.<init>(ExecutionData.java)
	at org.jacoco.agent.rt.internal_b6258fc.core.data.ExecutionDataStore.get(ExecutionDataStore.java:135)
	at org.jacoco.agent.rt.internal_b6258fc.core.runtime.RuntimeData.getExecutionData(RuntimeData.java:121)
 
       < cut a lot of same like lines here>
	 
	at org.jacoco.agent.rt.internal_b6258fc.core.runtime.RuntimeData.getExecutionData(RuntimeData.java:121)
	at org.jacoco.agent.rt.internal_b6258fc.core.runtime.RuntimeData.getProbes(RuntimeData.java:149)
	at org.jacoco.agent.rt.internal_b6258fc.core.runtime.RuntimeData.equals(RuntimeData.java:163)
	at org.jacoco.agent.rt.internal_b6258fc.core.data.ExecutionData.$jacocoInit(ExecutionData.java)
	at org.jacoco.agent.rt.internal_b6258fc.core.data.ExecutionData.<init>(ExecutionData.java)
FATAL ERROR in native method: processing of -javaagent failed
/bin/sh: line 1:  4653 Abort trap: 6           /Users/bytedance/Library/Java/JavaVirtualMachines/azul-1.8.0_322/Contents/Home/jre/bin/java -javaagent:/Users/bytedance/.m2/repository/org/jacoco/org.jacoco.agent/0.8.6/org.jacoco.agent-0.8.6-runtime.jar=destfile=/Users/bytedance/ws/sudi/trigger-core/target/jacoco.exec -javaagent:/Users/bytedance/.m2/repository/org/jacoco/org.jacoco.agent/0.8.8/org.jacoco.agent-0.8.8-runtime.jar=destfile=/Users/bytedance/ws/sudi/trigger-core/target/jacoco.exec -jar /Users/bytedance/ws/sudi/trigger-core/target/surefire/surefirebooter7825075648066282744.jar /Users/bytedance/ws/sudi/trigger-core/target/surefire/surefire8533896980808915611tmp /Users/bytedance/ws/sudi/trigger-core/target/surefire/surefire_04479986500118901910tmp

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for trigger-core 0.0.1:
[INFO]
[INFO] trigger-core ....................................... FAILURE [  4.459 s]
[INFO] trigger-management ................................. SKIPPED
[INFO] trigger-master ..................................... SKIPPED
[INFO] Jacoco Report ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.708 s
[INFO] Finished at: 2022-06-07T12:28:02-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project trigger-core: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project trigger-core: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:306)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:127)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:301)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:127)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.RuntimeException: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
    at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.close (ForkClient.java:257)
    at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork (ForkStarter.java:301)
    at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run (ForkStarter.java:116)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider (AbstractSurefireMojo.java:740)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAllProviders (AbstractSurefireMojo.java:682)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked (AbstractSurefireMojo.java:648)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute (AbstractSurefireMojo.java:586)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:301)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:127)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
 ```

**Comment by BruceZu** [comment]
I have tried many available solutions found by google search, But all do not work.

**Comment by Godin** [comment]
Please provide the beginning of

```
at org.jacoco.agent.rt.internal_b6258fc.core.data.ExecutionData.$jacocoInit(ExecutionData.java)
	at org.jacoco.agent.rt.internal_b6258fc.core.data.ExecutionData.<init>(ExecutionData.java)
	at org.jacoco.agent.rt.internal_b6258fc.core.data.ExecutionDataStore.get(ExecutionDataStore.java:135)
	at org.jacoco.agent.rt.internal_b6258fc.core.runtime.RuntimeData.getExecutionData(RuntimeData.java:121)
 
       < cut a lot of same like lines here>
	 
	at org.jacoco.agent.rt.internal_b6258fc.core.runtime.RuntimeData.getExecutionData(RuntimeData.java:121)
	at org.jacoco.agent.rt.internal_b6258fc.core.runtime.RuntimeData.getProbes(RuntimeData.java:149)
	at org.jacoco.agent.rt.internal_b6258fc.core.runtime.RuntimeData.equals(RuntimeData.java:163)
	at org.jacoco.agent.rt.internal_b6258fc.core.data.ExecutionData.$jacocoInit(ExecutionData.java)
	at org.jacoco.agent.rt.internal_b6258fc.core.data.ExecutionData.<init>(ExecutionData.java)
```

**Comment by BruceZu** [comment]
I do not know what is the meaning of"Complete executable reproducer". Do you mean I have to open my business src code?

**Comment by BruceZu** [comment]
I failed to input all the error messages because GitHub complain my content is too long to exceed the limitation. That is why I cut some lines, you can see the < cut a lot of same like lines here>

**Comment by BruceZu** [comment]
I did not find the root reason for this issue. 
But it disappears after I replace the variable ${release.version} to its value in the <parent> part

**Comment by Godin** [comment]
> I do not know what is the meaning of"Complete executable reproducer". Do you mean I have to open my business src code?

Any project demonstrating exactly the same difficulty.

----

> I failed to input all the error messages because GitHub complain my content is too long to exceed the limitation.

I haven't asked them all, I asked just the beginning.

----

My wild guess: beginning of

> at org.jacoco.agent.rt.internal_b6258fc.core.data.ExecutionData.<init>(ExecutionData.java)
> < cut a lot of same like lines here>
> at org.jacoco.agent.rt.internal_b6258fc.core.data.ExecutionData.<init>(ExecutionData.java)

is `StackOverflowError` and in this case answer is already in FAQ at https://www.jacoco.org/jacoco/trunk/doc/faq.html :

> ### Why do I get a StackOverflowError during code coverage analysis?
> Misconfiguration: If you configure two JaCoCo agents of different releases they will instrument each other and cause a endless recursion. Check the effective java command line and avoid such configurations.

and so check your effective java command line

> /bin/sh: line 1:  4653 Abort trap: 6           /Users/bytedance/Library/Java/JavaVirtualMachines/azul-1.8.0_322/Contents/Home/jre/bin/java -javaagent:/Users/bytedance/.m2/repository/org/jacoco/org.jacoco.agent/0.8.6/org.jacoco.agent-0.8.6-runtime.jar=destfile=/Users/bytedance/ws/sudi/trigger-core/target/jacoco.exec -javaagent:/Users/bytedance/.m2/repository/org/jacoco/org.jacoco.agent/0.8.8/org.jacoco.agent-0.8.8-runtime.jar=destfile=/Users/bytedance/ws/sudi/trigger-core/target/jacoco.exec -jar /Users/bytedance/ws/sudi/trigger-core/target/surefire/surefirebooter7825075648066282744.jar /Users/bytedance/ws/sudi/trigger-core/target/surefire/surefire8533896980808915611tmp /Users/bytedance/ws/sudi/trigger-core/target/surefire/surefire_04479986500118901910tmp

it indeed mentions two JaCoCo agents - one has version `0.8.6` and another has version `0.8.8`.
This is clearly misconfiguration on your side, and there is no way to tell you more about why this happens without **Complete executable reproducer**.

**Comment by BruceZu** [comment]
why it is invalid?

**Comment by Godin** [comment]
> why it is invalid?

As explained in https://github.com/jacoco/jacoco/issues/1322#issuecomment-1149228055

**Comment by BruceZu** [comment]
@Godin about 2 agents issue.   

in my pom.xml I specify the version 0.8.8, and in command, I also specify the version 0.8.8. 
but the generated bash still uses 2 agents.

```bash
/bin/sh: line 1:  4653 Abort trap: 6           /Users/bytedance/Library/Java/JavaVirtualMachines/azul-1.8.0_322/Contents/Home/jre/bin/java -javaagent:/Users/bytedance/.m2/repository/org/jacoco/org.jacoco.agent/0.8.6/org.jacoco.agent-0.8.6-runtime.jar=destfile=/Users/bytedance/ws/sudi/trigger-core/target/jacoco.exec -javaagent:/Users/bytedance/.m2/repository/org/jacoco/org.jacoco.agent/0.8.8/org.jacoco.agent-0.8.8-runtime.jar=destfile=/Users/bytedance/ws/sudi/trigger-core/target/jacoco.exec -jar /Users/bytedance/ws/sudi/trigger-core/target/surefire/surefirebooter7825075648066282744.jar /Users/bytedance/ws/sudi/trigger-core/target/surefire/surefire8533896980808915611tmp /Users/bytedance/ws/sudi/trigger-core/target/surefire/surefire_04479986500118901910tmp
```

I wonder if there is some way to avoid it if you do not think it is a bug. 
from the user side, except I do in pom.xml and command line, is there another way need to configure the agent version?
Thank you!

**Comment by Godin** [comment]
> I wonder if there is some way to avoid it if you do not think it is a bug

let me repeat

> This is clearly misconfiguration on your side, and there is no way to tell you more about why this happens without Complete executable reproducer.

e.g. maybe

> but the generated bash still uses 2 agents

comes from your parent pom.xml

> ```
>  <parent>
>    <artifactId>sudi</artifactId>
>    <groupId>com.bytedance.ad</groupId>
>    <version>${release.version}</version>
>  </parent>
> ```

**Comment by BruceZu** [comment]
@Godin JaCaCa is only used and configured in the current submodule pom.xml
I restore the <version>${release.version}</version> but the issue can not be reproduced.
The only difference is I have deleted the 0.8.6 from the maven home repository ~/.m2.

If  pom.xml and command line are all places I need to specify the version of JaCaCa. Then the generated bash should strictly be according to it, no matter what old version exists under ~/.m2. 
I will watch if the issue can happen later and share further information here.
