### ISSUE TITLE
reflection will affect the report result? 

### ISSUE THREAD

**Issue by BruceZu** [jacoco/jacoco#1324]
THIS IS A BUG TRACKER ONLY. FOR QUESTIONS PLEASE CHECK FAQ OR USE FORUM:

http://www.jacoco.org/jacoco/trunk/doc/faq.html
```
My code uses reflection. Why does it fail when I execute it with JaCoCo?
To collect execution data JaCoCo instruments the classes under test which adds two members to the classes: A private static field $jacocoData and a private static method $jacocoInit(). Both members are marked as synthetic.

Please change your code to ignore synthetic members. This is a good practice anyways as also the Java compiler creates synthetic members in certain situation.
```

https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Please understand that
ISSUES WITHOUT FOLLOWING INFORMATION WILL BE CLOSED WITHOUT COMMENTS!
Thank you for filling bug report!

### Steps to reproduce

* JaCoCo version: (from right bottom corner of JaCoCo report)
0.8.8

Operating system: Mac OS Monterey 12.2.1

Tool integration: Maven / Ant / CLI / API (for others please report to respective project)
Maven and CLI

Complete executable reproducer: (e.g. GitHub Repo)

Steps: (what exactly are you doing with the above reproducer?)
```mvn clean org.jacoco:jacoco-maven-plugin:0.8.8:prepare-agent   test  org.jacoco:jacoco-maven-plugin:0.8.8:report```
### Expected behaviour
no error log 

### Actual behaviour
```
Running com.x.ad.sudi.thrift.aop.ThriftServiceAspectTest
2022-06-07 15:34:30.917  INFO   --- [           main] c.b.a.s.thrift.aop.ThriftServiceAspect   : Start to handle with Object.AspectTest(). args = {test=param1}
2022-06-07 15:34:30.979 ERROR   --- [           main] c.b.a.s.thrift.aop.ThriftServiceAspect   : Thrift Service Aspect around error

java.lang.RuntimeException: test
	at com.x.ad.sudi.thrift.aop.ThriftServiceAspect.around(ThriftServiceAspect.java:52)
	at com.x.ad.sudi.thrift.aop.ThriftServiceAspectTest.around_Exception_RespondErrorCode(ThriftServiceAspectTest.java:50)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

2022-06-07 15:34:30.990 ERROR   --- [           main] c.b.a.s.thrift.aop.ThriftServiceAspect   : getRequestInfo error

java.lang.NoSuchMethodException: java.lang.String.getBase()
	at java.lang.Class.getDeclaredMethod(Class.java:2130)
	at com.x.ad.sudi.thrift.aop.ThriftServiceAspect.getRequestInfo(ThriftServiceAspect.java:97)
	at com.x.ad.sudi.thrift.aop.ThriftServiceAspect.around(ThriftServiceAspect.java:63)
	at com.x.ad.sudi.thrift.aop.ThriftServiceAspectTest.around_Exception_RespondErrorCode(ThriftServiceAspectTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

2022-06-07 15:34:30.992  INFO   --- [           main] c.b.a.s.thrift.aop.ThriftServiceAspect   : Start to handle with Object.AspectTest(). args = {test=param1}
2022-06-07 15:34:30.997  INFO   --- [           main] c.b.a.s.thrift.aop.ThriftServiceAspect   : Handling with Object.AspectTest() succeeded. args = {test=param1} result = AuthQueryResponse(BaseResp:BaseResp(StatusMessage:, StatusCode:0)) latency = 0.003 seconds
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.141 sec
```
```java

import com.x.ad.sudi.common.exception.BaseException;
import com.x.ad.sudi.common.util.ResponseUtils;
import com.x.base.util.RequestIDUtil;
import com.x.thrift.Base;
import com.x.thrift.BaseResp;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Map;
import lombok.Data;
import lombok.extern.slf4j.Slf4j;
import org.aspectj.lang.JoinPoint;
import org.aspectj.lang.ProceedingJoinPoint;
import org.aspectj.lang.annotation.Around;
import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.annotation.Pointcut;
import org.aspectj.lang.reflect.CodeSignature;
import org.aspectj.lang.reflect.MethodSignature;
import org.joda.time.DateTime;
import org.joda.time.Duration;
import org.springframework.stereotype.Component;

@Aspect
@Component
@Slf4j
public class ThriftServiceAspect {

  @Data
  public class RequestInfo {
    private String caller;
    private String logId;
    private String code;
    private String method = Constants.UNKNOWN;  
    private String cluster = Constants.UNKNOWN; 
  }

  @Pointcut("@annotation(ThriftMethodWrapper)")
  private void pointCut() {}

  @Around("pointCut()")
  public Object around(ProceedingJoinPoint joinPoint) throws Throwable {
    Object result;
    log.info(
        "Start to handle with {}.{}(). args = {}",
        getClassName(joinPoint),
        getMethodName(joinPoint),
        getArguments(joinPoint));
    DateTime startTime = DateTime.now();
    try {
      result = joinPoint.proceed();
      log.info(
          "Handling with {}.{}() succeeded. args = {} result = {} latency = {} seconds",
          getClassName(joinPoint),
          getMethodName(joinPoint),
          getArguments(joinPoint),
          result,
          (double) (new Duration(startTime, DateTime.now())).getMillis() / 1000.0D);
    } catch (Exception e) {
      log.error("Thrift Service Aspect around error", e);
      result = buildErrorResponse(joinPoint, e);
      Map<String, String> info = getRequestInfo(joinPoint);
      if (e instanceof BaseException) {
        info.put(Constants.CODE, String.valueOf(((BaseException) e).getCode().getCode()));
      }
      
    }
    return result;
  }

  private static String getClassName(JoinPoint joinPoint) {
    return joinPoint.getTarget().getClass().getSimpleName();
  }

  private static String getMethodName(JoinPoint joinPoint) {
    return joinPoint.getSignature().getName();
  }

  private static Map<String, Object> getArguments(JoinPoint joinPoint) {
    String[] argumentNames = ((CodeSignature) joinPoint.getSignature()).getParameterNames();
    Object[] argumentObjects = joinPoint.getArgs();
    Map<String, Object> map = new HashMap();

    for (int i = 0; i < argumentNames.length; ++i) {
      map.put(argumentNames[i], argumentObjects[i]);
    }

    return map;
  }

  private Map<String, String> getRequestInfo(ProceedingJoinPoint joinPoint) {
    Map<String, String> info = new HashMap<>();
    try {
      Object req = joinPoint.getArgs()[0];
      Method getBase = req.getClass().getDeclaredMethod("getBase");
      Base base = (Base) getBase.invoke(req);
      info.put(Constants.LOGID, RequestIDUtil.getCurrentRequestID());
      info.put(Constants.CALLER, base.getCaller());
      info.put(Constants.METHOD, joinPoint.getSignature().getName());
      info.put(Constants.CLUSTER, System.getenv(Constants.TCE_CLUSTER));
    } catch (Exception e) {
      log.error("getRequestInfo error", e);
    }
    return info;
  }

  private Object buildErrorResponse(ProceedingJoinPoint joinPoint, Exception e)
      throws IllegalAccessException, InstantiationException, NoSuchMethodException,
          InvocationTargetException {
    MethodSignature methodSignature = (MethodSignature) joinPoint.getSignature();
    BaseResp baseResp = ResponseUtils.failBaseResp(e);

    Object response = methodSignature.getReturnType().newInstance();
    Method setBaseResp = response.getClass().getDeclaredMethod("setBaseResp", BaseResp.class);
    setBaseResp.invoke(response, baseResp);

    return response;
  }
}

```
(In case of exceptions provide FULL STACKTRACE)

I read the http://www.jacoco.org/jacoco/trunk/doc/faq.html
```
My code uses reflection. Why does it fail when I execute it with JaCoCo?
To collect execution data JaCoCo instruments the classes under test which adds two members to the classes: A private static field $jacocoData and a private static method $jacocoInit(). Both members are marked as synthetic.

Please change your code to ignore synthetic members. This is a good practice anyways as also the Java compiler creates synthetic members in certain situation.
```
1> 
Firstly I do not think this is my case. 
if this is just my case, then If my understanding is right, I need change my code to  `ignore synthetic members`. but how to do that? 
will yo uplease shed some detailed information.

2> 
I also want to know the failure here will affect the report coverage number? 
Thank you!

**Comment by marchof** [comment]
Ad 1) Please see Java reflection API

https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/reflect/Member.html#isSynthetic()

Ad 2)

If your application code is not executing correctly it will lead to different exdcutions paths and most likely to different coverage data.
