### ISSUE TITLE
Unexpected SMAP line: *S KotlinDebug

### ISSUE THREAD

**Issue by hikuley** [jacoco/jacoco#1343]
I am getting type  `Unexpected SMAP line: *S KotlinDebug` error

When using Kotlin 1.6.0 with Jacoco Command Line Interface, I get this error,

**Steps to reproduce**

- JaCoCo version: 0.8.8
- Tool integration: Command Line Interface with Kotlin 1.6.0

`java -jar jacococli.jar report target/jacoco.exec --classfiles target/classes/ --sourcefiles src/main/java  --html target/jacoco_report/ --xml ./jacoco.xml`

```
[INFO] Loading execution data file /home/circleci/EatWithAva/ava-server/target/jacoco.exec.
Exception in thread "main" java.io.IOException: Error while analyzing target/classes/co/j30/server/avaJms/inne/InneMessageConsumer.class.
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzerError(Analyzer.java:162)
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeClass(Analyzer.java:134)
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeClass(Analyzer.java:157)
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeAll(Analyzer.java:193)
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeAll(Analyzer.java:226)
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeAll(Analyzer.java:221)
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeAll(Analyzer.java:221)
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeAll(Analyzer.java:221)
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeAll(Analyzer.java:221)
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeAll(Analyzer.java:221)
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeAll(Analyzer.java:221)
	at org.jacoco.cli.internal.commands.Report.analyze(Report.java:110)
	at org.jacoco.cli.internal.commands.Report.execute(Report.java:84)
	at org.jacoco.cli.internal.Main.execute(Main.java:90)
	at org.jacoco.cli.internal.Main.main(Main.java:105)
Caused by: java.lang.IllegalStateException: Unexpected SMAP line: *S KotlinDebug
	at org.jacoco.cli.internal.core.internal.analysis.filter.KotlinInlineFilter.getFirstGeneratedLineNumber(KotlinInlineFilter.java:98)
	at org.jacoco.cli.internal.core.internal.analysis.filter.KotlinInlineFilter.filter(KotlinInlineFilter.java:44)
	at org.jacoco.cli.internal.core.internal.analysis.filter.Filters.filter(Filters.java:58)
	at org.jacoco.cli.internal.core.internal.analysis.ClassAnalyzer.addMethodCoverage(ClassAnalyzer.java:119)
	at org.jacoco.cli.internal.core.internal.analysis.ClassAnalyzer.access$100(ClassAnalyzer.java:33)
	at org.jacoco.cli.internal.core.internal.analysis.ClassAnalyzer$1.accept(ClassAnalyzer.java:108)
	at org.jacoco.cli.internal.core.internal.flow.ClassProbesAdapter$2.visitEnd(ClassProbesAdapter.java:91)
	at org.jacoco.cli.internal.asm.ClassReader.readMethod(ClassReader.java:1288)
	at org.jacoco.cli.internal.asm.ClassReader.accept(ClassReader.java:688)
	at org.jacoco.cli.internal.asm.ClassReader.accept(ClassReader.java:400)
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeClass(Analyzer.java:116)
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeClass(Analyzer.java:132)
	... 13 more

Exited with code exit status 1

```

**Comment by marchof** [comment]
Looks like you're not using JaCoCo 8.8.0. Otherwise the exception message would read: "... with JaCoCo 0.8.8.202204050719/5dcf34a." We added the version number in JaCoCo 0.8.8
