### ISSUE TITLE
Using JaCoCo causes CoroutinesTimeout usage in test to fail

### ISSUE THREAD

**Issue by herriojr** [jacoco/jacoco#1357]
### Steps to reproduce

* JaCoCo version:  0.8.7.202105040129
* Operating system: OS X Version 12.5.1
* Tool integration: See sample project
* Complete executable reproducer: See attached tgz for Android Project
* Steps: 
1. tar -xzvf repro.tgz
2. cd MyApplication2/
3. create local.properties file and set sdk.dir to the installed Android SDK location on the file system
4. ./gradlew :app:testDebugUnitTestCoverage
5. Review crash report -- This only fails when jacoco's plugin is enabled.

### Expected behaviour
The test should not fail for using a class in the coroutine debug library when the jacoco plugin is used.

### Actual behaviour
The tests fails if jacoco's plugin is enabled, it does not if you remove the jacoco-specific lines in the app/build.gradle file

[repro.tgz](https://github.com/jacoco/jacoco/files/9465722/repro.tgz)

```
java.lang.IllegalStateException: Error invoking java.lang.instrument.Instrumentation#retransformClasses
	at kotlinx.coroutines.repackaged.net.bytebuddy.dynamic.loading.ClassReloadingStrategy$Dispatcher$ForJava6CapableVm.retransformClasses(ClassReloadingStrategy.java:503)
	at kotlinx.coroutines.repackaged.net.bytebuddy.dynamic.loading.ClassReloadingStrategy$Strategy$2.apply(ClassReloadingStrategy.java:568)
	at kotlinx.coroutines.repackaged.net.bytebuddy.dynamic.loading.ClassReloadingStrategy.load(ClassReloadingStrategy.java:225)
	at kotlinx.coroutines.repackaged.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
	at kotlinx.coroutines.repackaged.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:5707)
	at kotlinx.coroutines.debug.internal.ByteBuddyDynamicAttach.attach(Attach.kt:29)
	at kotlinx.coroutines.debug.internal.ByteBuddyDynamicAttach.invoke(Attach.kt:17)
	at kotlinx.coroutines.debug.internal.ByteBuddyDynamicAttach.invoke(Attach.kt:15)
	at kotlinx.coroutines.debug.internal.DebugProbesImpl.install(DebugProbesImpl.kt:85)
	at kotlinx.coroutines.debug.DebugProbes.install(DebugProbes.kt:72)
	at kotlinx.coroutines.debug.junit4.CoroutinesTimeout.<init>(CoroutinesTimeout.kt:59)
	at kotlinx.coroutines.debug.junit4.CoroutinesTimeout$Companion.seconds(CoroutinesTimeout.kt:83)
	at kotlinx.coroutines.debug.junit4.CoroutinesTimeout$Companion.seconds(CoroutinesTimeout.kt:72)
	at kotlinx.coroutines.debug.junit4.CoroutinesTimeout$Companion.seconds$default(CoroutinesTimeout.kt:67)
	at com.test.memusage.FakeUnitTest.<init>(FakeUnitTest.kt:9)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
	at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.UnsupportedOperationException: class redefinition failed: attempted to delete a method
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at kotlinx.coroutines.repackaged.net.bytebuddy.dynamic.loading.ClassReloadingStrategy$Dispatcher$ForJava6CapableVm.retransformClasses(ClassReloadingStrategy.java:495)
	... 58 more
```

**Comment by marchof** [comment]
Can you please add the failure message or stacktrace? Thx!

**Comment by herriojr** [comment]
@marchof added the stacktrace from the generated report

**Comment by Godin** [comment]
`kotlinx.coroutines.debug.internal.ByteBuddyDynamicAttach.attach` mentioned in your stacktrace [has following implementation](https://github.com/Kotlin/kotlinx.coroutines/blob/1.6.4/kotlinx-coroutines-debug/src/internal/Attach.kt#L20-L30):
```
        val cl = Class.forName("kotlin.coroutines.jvm.internal.DebugProbesKt")
        val cl2 = Class.forName("kotlinx.coroutines.debug.internal.DebugProbesKt")

        ByteBuddy()
            .redefine(cl2)
            .name(cl.name)
            .make()
            .load(cl.classLoader, ClassReloadingStrategy.fromInstalledAgent())
```

* `redefine(cl2)` loads bytes of class `kotlinx.coroutines.debug.internal.DebugProbesKt` **from the disk**
* `name(cl.name).make()` from the loaded bytes creates class named `kotlin.coroutines.jvm.internal.DebugProbesKt`
* `load(cl.classLoader, ClassReloadingStrategy.fromInstalledAgent())` **replaces already loaded by JVM class** `kotlinx.coroutines.debug.internal.DebugProbesKt` by the just created

ByteBuddy agent is after JaCoCo agent, so created replacement class loaded by ByteBuddy won't be instrumented by JaCoCo, whereas class being replaced is instrumented by JaCoCo. This behavior is also described in  https://github.com/raphw/byte-buddy/issues/1248

JaCoCo instrumentation adds field and method to the instrumented classes.

So with OpenJDK >= 13 because of https://bugs.openjdk.org/browse/JDK-8192936 all of this leads to
```
java.lang.UnsupportedOperationException: class redefinition failed: attempted to delete a method
```

To overcome this you can
* either use OpenJDK < 13, e.g. 11
* or with OpenJDK >= 13 use [JVM argument `-XX:+AllowRedefinitionToAddDeleteMethods`](https://bugs.openjdk.org/browse/JDK-8221528)
* or simply exclude involved classes from JaCoCo instrumentation
```
tasks.withType(Test) {
    jacoco.excludes = [
        'kotlin.coroutines.jvm.internal.DebugProbesKt',
        'kotlinx.coroutines.debug.internal.DebugProbesKt',
        'kotlinx.coroutines.debug.internal.NoOpProbesKt',
    ]
```
* or even better - include only your classes
```
tasks.withType(Test) {
    jacoco.includes = ['com.test.memusage.*']
```

Other than documenting this, I can't imagine what else we can do on the JaCoCo side.
