### ISSUE TITLE
seeing IllegalClassFormatException when instrumenting a class within Amazon'sSDK

### ISSUE THREAD

**Issue by SingingBush** [jacoco/jacoco#1370]
I have a project using JDK 17 which makes use of Amazon's 1.12.* SDK dependencies (I think they target JDK 7). It all builds/tests/runs fine but JaCoCo is throwing _IllegalClassFormatException_ on "software/amazon/awssdk/core/retry/conditions/OrRetryCondition"

* JaCoCo version:  0.8.8.202204050719
* Operating system: Linux
* Tool integration: Maven

```
java.lang.instrument.IllegalClassFormatException: Error while instrumenting software/amazon/awssdk/core/retry/conditions/OrRetryCondition with JaCoCo 0.8.8.202204050719/5dcf34a.
	at org.jacoco.agent.rt.internal_b6258fc.CoverageTransformer.transform(CoverageTransformer.java:94)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:480)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:440)
	at software.amazon.awssdk.core.retry.conditions.RetryCondition.defaultRetryCondition(RetryCondition.java:48)
	at software.amazon.awssdk.core.retry.RetryPolicy$BuilderImpl.<init>(RetryPolicy.java:377)
	at software.amazon.awssdk.core.retry.RetryPolicy$BuilderImpl.<init>(RetryPolicy.java:360)
	at software.amazon.awssdk.core.retry.RetryPolicy.builder(RetryPolicy.java:113)
	at software.amazon.awssdk.core.retry.RetryPolicy.forRetryMode(RetryPolicy.java:83)
	at software.amazon.awssdk.awscore.retry.AwsRetryPolicy.forRetryMode(AwsRetryPolicy.java:54)
	at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.resolveAwsRetryPolicy(AwsDefaultClientBuilder.java:372)
	at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeChildConfiguration(AwsDefaultClientBuilder.java:192)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:177)
	at software.amazon.awssdk.services.sqs.DefaultSqsClientBuilder.buildClient(DefaultSqsClientBuilder.java:27)
	at software.amazon.awssdk.services.sqs.DefaultSqsClientBuilder.buildClient(DefaultSqsClientBuilder.java:22)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:145)
	at io.jugo.chargebee.webhook.conf.SQSResource.start(SQSResource.java:45)
	at io.quarkus.test.common.TestResourceManager$TestResourceEntryRunnable.run(TestResourceManager.java:471)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by marchof** [comment]
Please provide the **full** stack trace. The should be a "caused by" section afterwards.

**Comment by SingingBush** [comment]
```
java.lang.instrument.IllegalClassFormatException: Error while instrumenting software/amazon/awssdk/core/retry/conditions/OrRetryCondition with JaCoCo 0.8.8.202204050719/5dcf34a.
	at org.jacoco.agent.rt.internal_b6258fc.CoverageTransformer.transform(CoverageTransformer.java:94)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:480)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:440)
	at software.amazon.awssdk.core.retry.conditions.RetryCondition.defaultRetryCondition(RetryCondition.java:48)
	at software.amazon.awssdk.core.retry.RetryPolicy$BuilderImpl.<init>(RetryPolicy.java:377)
	at software.amazon.awssdk.core.retry.RetryPolicy$BuilderImpl.<init>(RetryPolicy.java:360)
	at software.amazon.awssdk.core.retry.RetryPolicy.builder(RetryPolicy.java:113)
	at software.amazon.awssdk.core.retry.RetryPolicy.forRetryMode(RetryPolicy.java:83)
	at software.amazon.awssdk.awscore.retry.AwsRetryPolicy.forRetryMode(AwsRetryPolicy.java:54)
	at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.resolveAwsRetryPolicy(AwsDefaultClientBuilder.java:372)
	at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeChildConfiguration(AwsDefaultClientBuilder.java:192)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:177)
	at software.amazon.awssdk.services.sqs.DefaultSqsClientBuilder.buildClient(DefaultSqsClientBuilder.java:27)
	at software.amazon.awssdk.services.sqs.DefaultSqsClientBuilder.buildClient(DefaultSqsClientBuilder.java:22)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:145)
	at software.amazon.awssdk.services.sqs.SqsClientBuilder_38d48e5b72c1e6c4e28528206856bbe6892fa962_Synthetic_ClientProxy.build(Unknown Source)
	at io.quarkus.amazon.sqs.runtime.SqsClientProducer.<init>(SqsClientProducer.java:20)
	at io.quarkus.amazon.sqs.runtime.SqsClientProducer_Bean.create(Unknown Source)
	at io.quarkus.amazon.sqs.runtime.SqsClientProducer_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:111)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:32)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:32)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:19)
	at io.quarkus.amazon.sqs.runtime.SqsClientProducer_ClientProxy.arc$delegate(Unknown Source)
	at io.quarkus.amazon.sqs.runtime.SqsClientProducer_ClientProxy.arc_contextualInstance(Unknown Source)
	at io.quarkus.amazon.sqs.runtime.SqsClientProducer_ProducerMethod_client_24ac7b8ada82ac4b22f84052195e7c8e880e0ee7_Bean.create(Unknown Source)
	at io.quarkus.amazon.sqs.runtime.SqsClientProducer_ProducerMethod_client_24ac7b8ada82ac4b22f84052195e7c8e880e0ee7_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:111)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:32)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:32)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:19)
	at software.amazon.awssdk.services.sqs.SqsClientProducer_ProducerMethod_client_24ac7b8ada82ac4b22f84052195e7c8e880e0ee7_ClientProxy.arc$delegate(Unknown Source)
	at software.amazon.awssdk.services.sqs.SqsClientProducer_ProducerMethod_client_24ac7b8ada82ac4b22f84052195e7c8e880e0ee7_ClientProxy.sendMessage(Unknown Source)
	at io.jugo.chargebee.webhook.functions.WebhookLambda.forwardChargebeeRequestToSqs(WebhookLambda.java:93)
	at io.jugo.chargebee.webhook.functions.WebhookLambda.handleRequest(WebhookLambda.java:77)
	at io.jugo.chargebee.webhook.functions.WebhookLambda_Subclass.handleRequest$$superforward1(Unknown Source)
	at io.jugo.chargebee.webhook.functions.WebhookLambda_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
	at io.jugo.chargebee.webhook.interceptor.CatchErrorInterceptor.exceptionConversion(CatchErrorInterceptor.java:25)
	at io.jugo.chargebee.webhook.interceptor.CatchErrorInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.jugo.chargebee.webhook.functions.WebhookLambda_Subclass.handleRequest(Unknown Source)
	at io.jugo.chargebee.webhook.functions.WebhookLambda_ClientProxy.handleRequest(Unknown Source)
	at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder$1.processRequest(AmazonLambdaRecorder.java:192)
	at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:124)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: Error while instrumenting software/amazon/awssdk/core/retry/conditions/OrRetryCondition with JaCoCo 0.8.8.202204050719/5dcf34a.
	at org.jacoco.agent.rt.internal_b6258fc.core.instr.Instrumenter.instrumentError(Instrumenter.java:161)
	at org.jacoco.agent.rt.internal_b6258fc.core.instr.Instrumenter.instrument(Instrumenter.java:111)
	at org.jacoco.agent.rt.internal_b6258fc.CoverageTransformer.transform(CoverageTransformer.java:92)
	... 58 more
Caused by: java.lang.IllegalStateException: Cannot process instrumented class software/amazon/awssdk/core/retry/conditions/OrRetryCondition. Please supply original non-instrumented classes.
	at org.jacoco.agent.rt.internal_b6258fc.core.internal.instr.InstrSupport.assertNotInstrumented(InstrSupport.java:238)
	at org.jacoco.agent.rt.internal_b6258fc.core.internal.instr.ClassInstrumenter.visitField(ClassInstrumenter.java:56)
	at org.jacoco.agent.rt.internal_b6258fc.asm.ClassVisitor.visitField(ClassVisitor.java:338)
	at org.jacoco.agent.rt.internal_b6258fc.asm.ClassReader.readField(ClassReader.java:1137)
	at org.jacoco.agent.rt.internal_b6258fc.asm.ClassReader.accept(ClassReader.java:739)
	at org.jacoco.agent.rt.internal_b6258fc.asm.ClassReader.accept(ClassReader.java:424)
	at org.jacoco.agent.rt.internal_b6258fc.core.instr.Instrumenter.instrument(Instrumenter.java:91)
	at org.jacoco.agent.rt.internal_b6258fc.core.instr.Instrumenter.instrument(Instrumenter.java:109)
	... 59 more
java.lang.instrument.IllegalClassFormatException: Error while instrumenting software/amazon/awssdk/core/retry/conditions/TokenBucketRetryCondition with JaCoCo 0.8.8.202204050719/5dcf34a.
	at org.jacoco.agent.rt.internal_b6258fc.CoverageTransformer.transform(CoverageTransformer.java:94)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:480)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:440)
	at software.amazon.awssdk.core.retry.RetryPolicy$BuilderImpl.<init>(RetryPolicy.java:378)
	at software.amazon.awssdk.core.retry.RetryPolicy$BuilderImpl.<init>(RetryPolicy.java:360)
	at software.amazon.awssdk.core.retry.RetryPolicy.builder(RetryPolicy.java:113)
	at software.amazon.awssdk.core.retry.RetryPolicy.forRetryMode(RetryPolicy.java:83)
	at software.amazon.awssdk.awscore.retry.AwsRetryPolicy.forRetryMode(AwsRetryPolicy.java:54)
	at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.resolveAwsRetryPolicy(AwsDefaultClientBuilder.java:372)
	at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeChildConfiguration(AwsDefaultClientBuilder.java:192)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:177)
	at software.amazon.awssdk.services.sqs.DefaultSqsClientBuilder.buildClient(DefaultSqsClientBuilder.java:27)
	at software.amazon.awssdk.services.sqs.DefaultSqsClientBuilder.buildClient(DefaultSqsClientBuilder.java:22)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:145)
	at software.amazon.awssdk.services.sqs.SqsClientBuilder_38d48e5b72c1e6c4e28528206856bbe6892fa962_Synthetic_ClientProxy.build(Unknown Source)
	at io.quarkus.amazon.sqs.runtime.SqsClientProducer.<init>(SqsClientProducer.java:20)
	at io.quarkus.amazon.sqs.runtime.SqsClientProducer_Bean.create(Unknown Source)
	at io.quarkus.amazon.sqs.runtime.SqsClientProducer_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:111)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:32)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:32)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:19)
	at io.quarkus.amazon.sqs.runtime.SqsClientProducer_ClientProxy.arc$delegate(Unknown Source)
	at io.quarkus.amazon.sqs.runtime.SqsClientProducer_ClientProxy.arc_contextualInstance(Unknown Source)
	at io.quarkus.amazon.sqs.runtime.SqsClientProducer_ProducerMethod_client_24ac7b8ada82ac4b22f84052195e7c8e880e0ee7_Bean.create(Unknown Source)
	at io.quarkus.amazon.sqs.runtime.SqsClientProducer_ProducerMethod_client_24ac7b8ada82ac4b22f84052195e7c8e880e0ee7_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:111)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:32)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:32)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:19)
	at software.amazon.awssdk.services.sqs.SqsClientProducer_ProducerMethod_client_24ac7b8ada82ac4b22f84052195e7c8e880e0ee7_ClientProxy.arc$delegate(Unknown Source)
	at software.amazon.awssdk.services.sqs.SqsClientProducer_ProducerMethod_client_24ac7b8ada82ac4b22f84052195e7c8e880e0ee7_ClientProxy.sendMessage(Unknown Source)
	at io.jugo.chargebee.webhook.functions.WebhookLambda.forwardChargebeeRequestToSqs(WebhookLambda.java:93)
	at io.jugo.chargebee.webhook.functions.WebhookLambda.handleRequest(WebhookLambda.java:77)
	at io.jugo.chargebee.webhook.functions.WebhookLambda_Subclass.handleRequest$$superforward1(Unknown Source)
	at io.jugo.chargebee.webhook.functions.WebhookLambda_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
	at io.jugo.chargebee.webhook.interceptor.CatchErrorInterceptor.exceptionConversion(CatchErrorInterceptor.java:25)
	at io.jugo.chargebee.webhook.interceptor.CatchErrorInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.jugo.chargebee.webhook.functions.WebhookLambda_Subclass.handleRequest(Unknown Source)
	at io.jugo.chargebee.webhook.functions.WebhookLambda_ClientProxy.handleRequest(Unknown Source)
	at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder$1.processRequest(AmazonLambdaRecorder.java:192)
	at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:124)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: Error while instrumenting software/amazon/awssdk/core/retry/conditions/TokenBucketRetryCondition with JaCoCo 0.8.8.202204050719/5dcf34a.
	at org.jacoco.agent.rt.internal_b6258fc.core.instr.Instrumenter.instrumentError(Instrumenter.java:161)
	at org.jacoco.agent.rt.internal_b6258fc.core.instr.Instrumenter.instrument(Instrumenter.java:111)
	at org.jacoco.agent.rt.internal_b6258fc.CoverageTransformer.transform(CoverageTransformer.java:92)
	... 57 more
Caused by: java.lang.IllegalStateException: Cannot process instrumented class software/amazon/awssdk/core/retry/conditions/TokenBucketRetryCondition. Please supply original non-instrumented classes.
	at org.jacoco.agent.rt.internal_b6258fc.core.internal.instr.InstrSupport.assertNotInstrumented(InstrSupport.java:238)
	at org.jacoco.agent.rt.internal_b6258fc.core.internal.instr.ClassInstrumenter.visitField(ClassInstrumenter.java:56)
	at org.jacoco.agent.rt.internal_b6258fc.asm.ClassVisitor.visitField(ClassVisitor.java:338)
	at org.jacoco.agent.rt.internal_b6258fc.asm.ClassReader.readField(ClassReader.java:1137)
	at org.jacoco.agent.rt.internal_b6258fc.asm.ClassReader.accept(ClassReader.java:739)
	at org.jacoco.agent.rt.internal_b6258fc.asm.ClassReader.accept(ClassReader.java:424)
	at org.jacoco.agent.rt.internal_b6258fc.core.instr.Instrumenter.instrument(Instrumenter.java:91)
	at org.jacoco.agent.rt.internal_b6258fc.core.instr.Instrumenter.instrument(Instrumenter.java:109)
	... 58 more
```

**Comment by marchof** [comment]
Here it is:

> Cannot process instrumented class software/amazon/awssdk/core/retry/conditions/OrRetryCondition. Please supply original non-instrumented classes.

This is typically the case when you instrument the classes AND use the agent.
