### ISSUE TITLE
There is a conflict between JaCoCo and Lettuce.

### ISSUE THREAD

**Issue by tomzhang-liang** [jacoco/jacoco#1500]
### Steps to reproduce

* JaCoCo version: 0.8.10.202304240956
* Operating system:
* Tool integration: I am using JaCoCo with agent mode to start.
* Steps: When I start my project with the Jacoco's agent command, I get an error indicating a conflict between Jacoco and Lettuce.
* Lettuce version:lettuce-core-6.1.9.RELEASE
* Exception Logs:
  java.lang.instrument.IllegalClassFormatException: Error while instrumenting io/lettuce/core/event/connection/JfrConnectionCreatedEvent with JaCoCo 0.8.10.202304240956/8ea9668.
	at org.jacoco.agent.rt.internal_4a7f17c.CoverageTransformer.transform(CoverageTransformer.java:94)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)

**Comment by marchof** [comment]
@tomzhang-liang To fix this issue we will need to debug the problem. Can you please provide a GitHub repository with a minimal executable reproducer? Thx!

**Comment by marchof** [comment]
@tomzhang-liang Sorry, if we cannot reproduce this we cannot analyze it.
