### ISSUE TITLE
Class can not be reRead by JDK ClassReader after jacoco transformed in JDK11

### ISSUE THREAD

**Issue by txgj** [jacoco/jacoco#1541]
Some class can not be reRead by JDK ClassReader after jacoco transformed in JDK11 but it is OK in JDK8.

### Steps to reproduce

* JaCoCo version:  0.8.7-0.8.10
* Operating system: macOs  Version 13.5.1  (m1 chip) And Linux version 4.19.91 etc.
* Tool integration:  JAVA API in local or Agent on linux server
* Complete executable reproducer: https://github.com/txgj/jacoco-issue
* 
* Steps:
see the code please:  https://github.com/txgj/jacoco-issue

 // first read and parse
 it is OK 
 // jacoco transform
 it is OK
 // second read and parse
 it is ERROR in JDK 11 

When in JDK8:
java runtime params:
```
/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/bin/java -javaagent:/Users/test/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-1/231.8770.65/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=51531:/Users/test/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-1/231.8770.65/IntelliJ IDEA.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/ext/legacy8ujsse.jar:/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/ext/openjsse.jar:/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/lib/tools.jar:/Users/test/work/qa/test/target/classes:/Users/test/.m2/repository/org/jacoco/org.jacoco.agent.rt/0.8.7/org.jacoco.agent.rt-0.8.7.jar:/Users/test/.m2/repository/org/jacoco/org.jacoco.core/0.8.7/org.jacoco.core-0.8.7.jar:/Users/test/.m2/repository/org/ow2/asm/asm/9.1/asm-9.1.jar:/Users/test/.m2/repository/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar:/Users/test/.m2/repository/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar:/Users/test/.m2/repository/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar:/Users/test/.m2/repository/commons-io/commons-io/2.6/commons-io-2.6.jar com.test.jacoco.JacocoIssue
```

the result is:

```
readAndParseClass before jacoco transform
readAndParseClass className: com/test/jacoco/SimpleClassForJacoco
readAndParseClass reWrite length: 777
before length: 1132
after length:1561
readAndParseClass after jacoco transform
readAndParseClass className: com/test/jacoco/SimpleClassForJacoco
readAndParseClass reWrite length: 1069
reRead length:1561
```

but in JDK11: (jacoco version 0.8.7 ~ 0.8.10)
java runtime params:
```
  /Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home/bin/java -javaagent:/Users/test/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-1/231.8770.65/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=56932:/Users/test/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-1/231.8770.65/IntelliJ IDEA.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Users/test/work/qa/test/target/classes:/Users/test/.m2/repository/org/jacoco/org.jacoco.agent.rt/0.8.7/org.jacoco.agent.rt-0.8.7.jar:/Users/test/.m2/repository/org/jacoco/org.jacoco.core/0.8.7/org.jacoco.core-0.8.7.jar:/Users/test/.m2/repository/org/ow2/asm/asm/9.1/asm-9.1.jar:/Users/test/.m2/repository/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar:/Users/test/.m2/repository/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar:/Users/test/.m2/repository/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar:/Users/test/.m2/repository/commons-io/commons-io/2.6/commons-io-2.6.jar com.test.jacoco.JacocoIssue
```

the result is:

```
readAndParseClass before jacoco transform
readAndParseClass className: com/test/jacoco/SimpleClassForJacoco
readAndParseClass reWrite length: 778
before length: 1133
after length:1633
readAndParseClass after jacoco transform
readAndParseClass className: com/test/jacoco/SimpleClassForJacoco
readAndParseClass after jacoco transform error: java.lang.NullPointerException
java.lang.NullPointerException
	at java.base/jdk.internal.org.objectweb.asm.Item.set(Item.java:262)
	at java.base/jdk.internal.org.objectweb.asm.ClassReader.copyPool(ClassReader.java:380)
	at java.base/jdk.internal.org.objectweb.asm.ClassWriter.<init>(ClassWriter.java:716)
	at com.test.jacoco.JacocoIssue.readAndParseClass(JacocoIssue.java:71)
	at com.test.jacoco.JacocoIssue.main(JacocoIssue.java:55)
```

### Expected behaviour
Class after jacoco transformed should be reReadable for JDK ClassReader 

### Actual behaviour
When use  JDK ClassReader to read and parse the transformed class, it  throws NullPointerException

```
java.lang.NullPointerException
	at java.base/jdk.internal.org.objectweb.asm.Item.set(Item.java:262)
	at java.base/jdk.internal.org.objectweb.asm.ClassReader.copyPool(ClassReader.java:380)
	at java.base/jdk.internal.org.objectweb.asm.ClassWriter.<init>(ClassWriter.java:716)
	at com.test.jacoco.JacocoIssue.readAndParseClass(JacocoIssue.java:71)
	at com.test.jacoco.JacocoIssue.main(JacocoIssue.java:55)
```

**Comment by Godin** [comment]
Stack trace contains

```
java.lang.NullPointerException
	at java.base/jdk.internal.org.objectweb.asm.Item.set(Item.java:262)
```

this JDK 11 class
https://github.com/openjdk/jdk/blob/jdk-11-ga/src/java.base/share/classes/jdk/internal/org/objectweb/asm/Item.java
corresponds to ancient ASM version 6.0 that does not handle correctly Java 11 feature [dynamic constants](https://openjdk.org/jeps/309), which is used by JaCoCo for Java 11+ class files. Support for dynamic constants was added in ASM version 7.0, `jdk.internal.org.objectweb.asm` was updated to ASM 7 in JDK 12 - see  https://github.com/openjdk/jdk/commit/61082e6b256054677fbe3dac5761036b794b5598 And the same reproducer runs fine on JDK 12.
