### ISSUE TITLE
Remove dependency on Sun classloader

### ISSUE THREAD

**Issue by marchof** [jacoco/jacoco#16]
By default the JaCoCo agent excludes the classloader sun.reflect.DelegatingClassLoader. As this classloader does not have access to the Java runtime library itself, therefore instrumented classes failed to load. This is documented in several places and can still be reproduced.  It seems to be related to the following Java bug:

http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6265952

It would be nice to find another mechanism to determine this situation.

**Comment by Godin** [comment]
Just for fun and for the record - here is example that triggers failure in absence of exclusion of `sun.reflect.DelegatingClassLoader`:

``` java
class Example {
  /**
   * Should be greater by 2 than
   * {@link jdk.internal.reflect.ReflectionFactory#inflationThreshold} in JDK 9
   * and {@link sun.reflect.ReflectionFactory#inflationThreshold} in JDK versions lower than 9
   *
   * to trigger usage of {@link jdk.internal.reflect.MethodAccessorGenerator} in JDK 9
   * and {@link sun.reflect.MethodAccessorGenerator} in JDK versions lower than 9.
   *
   * Threshold can be changed using "-Dsun.reflect.inflationThreshold"
   * or disabled by "-Dsun.reflect.noInflation".
   */
  private final static int ITERATIONS = 15 + 2;

  public static void main(String[] args) throws Exception {
    for (int i = 0; i < ITERATIONS; i++) {
      Example.class.getDeclaredConstructors()[0].newInstance();
    }
  }
}
```

```
$ java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

$ java -XX:+UnlockDiagnosticVMOptions -XX:+ShowHiddenFrames -javaagent:jacoco-0.7.9/lib/jacocoagent.jar=exclclassloader=,inclnolocationclasses=true Example
Exception in thread "main" java.lang.NoClassDefFoundError: jdk/internal/reflect/GeneratedConstructorAccessor1
	at jdk.internal.reflect.GeneratedConstructorAccessor1.newInstance(<Unknown>:1000000)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at Example.main(Example.java:17)
Caused by: java.lang.ClassNotFoundException: jdk.internal.reflect.GeneratedConstructorAccessor1
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 4 more
```

**Comment by Godin** [comment]
@marchof 😆  actually `sun.reflect.DelegatingClassLoader` has been renamed into `jdk.internal.reflect.DelegatingClassLoader` in JDK 9 (see [JDK-8137058](https://bugs.openjdk.java.net/browse/JDK-8137058)), so that example above fails even without `exclclassloader=`. Does it mean that JaCoCo users do not use `inclnolocationclasses=true` in combination with JDK 9 and reflection? 😆 

And here is another fun fact, but this time regarding

> classloader sun.reflect.DelegatingClassLoader. As this classloader does not have access to the Java runtime library

actually as shown below classes loaded by `DelegatingClassLoader` can access Java runtime library, in particular `java.util.UUID` and `java.lang.UnknownError` 😉  But for some unknown to me reason, can't invoke own methods:

```
$ mkdir target

$ cat <<END > target/Target.java
public class Target implements Runnable {
	public void run() {
		System.out.println(java.util.UUID.class);
		System.out.println(java.lang.UnknownError.class);
		System.out.println("Trying to call own method");
		method();
	}

	private void method() {
		System.out.println("OK");
	}
}
END

$ cat <<END > Example.java
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.nio.file.Files;
import java.nio.file.Paths;

public class Example {
	public static void main(String[] args) throws Exception {
		Constructor delegatingClassLoaderConstructor = Class
				.forName("sun.reflect.DelegatingClassLoader")
				.getDeclaredConstructor(ClassLoader.class);
		delegatingClassLoaderConstructor.setAccessible(true);
		ClassLoader delegatingClassLoader = (ClassLoader) delegatingClassLoaderConstructor
				.newInstance(Example.class.getClassLoader());

		byte[] bytes = Files.readAllBytes(Paths.get("target/Target.class"));

		Method defineClassMethod = ClassLoader.class.getDeclaredMethod(
				"defineClass", byte[].class, int.class, int.class);
		defineClassMethod.setAccessible(true);
		Class targetClass = (Class) defineClassMethod
				.invoke(delegatingClassLoader, bytes, 0, bytes.length);

		((Runnable) targetClass.newInstance()).run();
	}
}
END

$ javac target/Target.java Example.java

$ java -showversion Example
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

class java.util.UUID
class java.lang.UnknownError
Trying to call own method
Exception in thread "main" java.lang.NoClassDefFoundError: Target
	at Target.run(Target.java:6)
	at Example.main(Example.java:23)
Caused by: java.lang.ClassNotFoundException: Target
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
```

In our case - method `$jacocoInit`.

**Comment by marchof** [comment]
@Godin Thx for looking into this!
For Java 9 we can quick-fix this with excluding class loader `*.reflect.DelegatingClassLoader`

**Comment by dhardtke** [comment]
@Godin Thanks for finding out that the error occurs when using `includeNoLocationClasses=true` - this has caused me some headaches because our project was not working anymore when executing testNG due to Jacoco (for some weird reason).

**Comment by Godin** [comment]
@dhardtke just to clarify - this is not solely/mainly about `inclnolocationclasses`:
* `exclclassloader=sun.reflect.DelegatingClassLoader` (this is default value in agent) and any value of `includeNoLocationClasses`  with JDK versions lower than 9 is OK
* `exclclassloader=jdk.internal.reflect.DelegatingClassLoader` and any value of `inclnolocationclasses` with JDK 9  is OK
* `inclnolocationclasses=false` (this is default value in agent) with any version of JDK is OK

**Comment by Godin** [comment]
For the record: as of today Eclipse EclEmma doesn't allow to change default value of `inclnolocationclasses` and thus this problem doesn't affect it.
