### ISSUE TITLE
Error while instrumenting with JaCoCo 0.8.11.202310140853/f33756c.

### ISSUE THREAD

**Issue by enexusde** [jacoco/jacoco#1607]
THIS IS A BUG TRACKER ONLY. FOR QUESTIONS PLEASE CHECK FAQ OR USE FORUM:

http://www.jacoco.org/jacoco/trunk/doc/faq.html

https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Please understand that
ISSUES WITHOUT FOLLOWING INFORMATION WILL BE CLOSED WITHOUT COMMENTS!
Thank you for filing a useful bug report!

### Steps to reproduce

* JaCoCo version: 0.8.11.202310140853/f33756c. (from right bottom corner of JaCoCo report - no report produced)
* Operating system: Ubuntu
* Tool integration: Maven
* Complete executable reproducer: Internal (will provide jar for representatives)
* Steps: `mvn jacoco:prepare-agent install jacoco:report`

### Expected behaviour

Create Report.

### Actual behaviour

Build Failed.

(In case of exceptions provide FULL STACKTRACE)

```
	java.lang.instrument.IllegalClassFormatException: Error while instrumenting com/release_manager/translation/I8n with JaCoCo 0.8.11.202310140853/f33756c.
	at org.jacoco.agent.rt.internal_4742761.CoverageTransformer.transform(CoverageTransformer.java:94)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.util.ResourceBundle$Control.newBundle0(ResourceBundle.java:3170)
	at java.base/java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:3151)
	at java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1984)
	at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1770)
	at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1722)
	at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1722)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1656)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1586)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1549)
	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:932)
	at XXX.DefaultTranslationContext.<init>(DefaultTranslationContext.java:27)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1295)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1197)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:843)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:88)
	at XXX.TestCpp.<clinit>(TestCpp.java:299)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.apache.maven.surefire.junit.PojoTestSetExecutor.executeTestMethod(PojoTestSetExecutor.java:75)
	at org.apache.maven.surefire.junit.PojoTestSetExecutor.execute(PojoTestSetExecutor.java:63)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:93)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
	Caused by: java.io.IOException: Error while instrumenting com/release_manager/translation/I8n with JaCoCo 0.8.11.202310140853/f33756c.
	at org.jacoco.agent.rt.internal_4742761.core.instr.Instrumenter.instrumentError(Instrumenter.java:161)
	at org.jacoco.agent.rt.internal_4742761.core.instr.Instrumenter.instrument(Instrumenter.java:111)
	at org.jacoco.agent.rt.internal_4742761.CoverageTransformer.transform(CoverageTransformer.java:92)
	... 56 more
	Caused by: org.jacoco.agent.rt.internal_4742761.asm.MethodTooLargeException: Method too large: com/release_manager/translation/I8n.<clinit> ()V
	at org.jacoco.agent.rt.internal_4742761.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2088)
	at org.jacoco.agent.rt.internal_4742761.asm.ClassWriter.toByteArray(ClassWriter.java:512)
	at org.jacoco.agent.rt.internal_4742761.core.instr.Instrumenter.instrument(Instrumenter.java:92)
	at org.jacoco.agent.rt.internal_4742761.core.instr.Instrumenter.instrument(Instrumenter.java:109)
	... 57 more
```

**Comment by Godin** [comment]
@enexusde in future please do the research before opening issue - similarly to https://github.com/jacoco/jacoco/issues/1510#issuecomment-1733010130 and https://github.com/jacoco/jacoco/issues/1369#issuecomment-1266775472 and etc

the cause is at the very bottom of the stack trace

> Caused by: org.jacoco.agent.rt.internal_4742761.asm.MethodTooLargeException: Method too large: com/release_manager/translation/I8n.<clinit> ()V

Compiled Java methods have a maximum size. As JaCoCo adds additional code for instrumentation, **very large** methods might get bigger than allowed. This is a known limitation of JaCoCo.

As this is typically only the case for generated classes I recommend excluding this class from instrumentation.

**Comment by PranayDVigo** [comment]
Hi @Godin
I have faced this same issue and tried to exclude the classes, but it doesn't work. I need some help here, I have been trying to fix this for days. Please guide me, I have checked out the official documentation but couldn't figure out what to do. 


I am trying to run instrumentation tests on Android Studio with JaCoCo after enabling  `testCoverageEnabled`. The build fails with the following error:
```
Caused by: org.objectweb.asm.MethodTooLargeException: Method too large: com/ihealth/communication/ins/POMethod.a ()Ljava/util/HashMap;
``` 

I have followed this https://thsaravana.github.io/blog/jacoco-single-coverage-for-multi-module/ to implement jacoco

My Files:
1. `root/jacoco/project.gradle`
```
apply plugin: 'jacoco'

jacoco {
    toolVersion '0.8.10'
}

tasks.withType(Test) {
    jacoco.includeNoLocationClasses = true
    jacoco.excludes = ['jdk.internal.*', 'com.ihealth.*']
}

project.afterEvaluate {
    def variants = ["qa"]

    tasks.create(name: "generateCoverageReport", type: JacocoReport) {

        group = "Reporting"
        description = "Generate overall Jacoco coverage report for the selected builds."

        reports {
            html.required.set(true)
            xml.required.set(true)
        }

        def excludes = [
                '**/R.class',
                '**/R$*.class',
                '**/BuildConfig.*',
                '**/Manifest*.*',
                '**/*Test*.*',
                'android/**/*.*',
                'androidx/**/*.*',
                '**/*$ViewInjector*.*',
                '**/*Dagger*.*',
                '**/*MembersInjector*.*',
                '**/*_Factory.*',
                '**/*_Provide*Factory*.*',
                '**/*_ViewBinding*.*',
                '**/AutoValue_*.*',
                '**/R2.class',
                '**/R2$*.class',
                '**/*Directions$*',
                '**/*Directions.*',
                '**/*Binding.*'
        ]

        def jClasses = subprojects.collect { proj ->
            variants.collect { variant ->
                "${proj.buildDir}/intermediates/javac/$variant/classes"
            }
        }.flatten()
        def kClasses = subprojects.collect { proj ->
            variants.collect { variant ->
                "${proj.buildDir}/tmp/kotlin-classes/$variant"
            }
        }.flatten()

        def javaClasses = jClasses.collect { path ->
            fileTree(dir: path, excludes: excludes)
        }
        def kotlinClasses = kClasses.collect { path ->
            fileTree(dir: path, excludes: excludes)
        }

        classDirectories.from = files([javaClasses, kotlinClasses])
        def sources = subprojects.collect { proj ->
            variants.collect { variant ->
                ["${proj.projectDir}/src/main/java", "${proj.projectDir}/src/main/kotlin",
                 "${proj.projectDir}/src/$variant/java", "${proj.projectDir}/src/$variant/kotlin"]
            }.flatten()
        }.flatten()
        sourceDirectories.from = files(sources)

        def executions = subprojects.collect { proj ->
            variants.collect { variant ->
                def path = "${proj.buildDir}/jacoco/test${variant.capitalize()}UnitTest.exec"
                if ((new File(path)).exists()) path else null
            }
        }.flatten()
        executions.removeAll([null])

        executionData.from = files(executions)
    }
}
```
2. root/jacoco/modules.gradle
```
apply plugin: 'jacoco'

jacoco {
    toolVersion '0.8.10'
}

tasks.withType(Test) {
    jacoco.includeNoLocationClasses = true
    jacoco.excludes = ['jdk.internal.*', 'com.ihealth.*']
    jacoco.destinationFile = file("$buildDir/jacoco/${name}.exec")
}

project.afterEvaluate {
    (android.hasProperty('applicationVariants') ? android.'applicationVariants' : android.'libraryVariants')
            .all { variant ->
                def variantName = variant.name
                def capVariantName = variantName.capitalize()
                def testTaskName = "test${capVariantName}UnitTest"
                tasks.create(name: "${variantName}Coverage", type: JacocoReport, dependsOn: testTaskName) {

                    group = "Reporting"
                    description = "Generate Jacoco coverage reports for the ${variantName} build."

                    reports {
                        html.required.set(true)
                        xml.required.set(true)
                    }

                    def excludes = [
                            '**/R.class',
                            '**/R$*.class',
                            '**/BuildConfig.*',
                            '**/Manifest*.*',
                            '**/*Test*.*',
                            'android/**/*.*',
                            'androidx/**/*.*',
                            '**/*$ViewInjector*.*',
                            '**/*Dagger*.*',
                            '**/*MembersInjector*.*',
                            '**/*_Factory.*',
                            '**/*_Provide*Factory*.*',
                            '**/*_ViewBinding*.*',
                            '**/AutoValue_*.*',
                            '**/R2.class',
                            '**/R2$*.class',
                            '**/*Directions$*',
                            '**/*Directions.*',
                            '**/*Binding.*'
                    ]

                    def jClasses = "${project.buildDir}/intermediates/javac/${variantName}/classes"
                    def kClasses = "${project.buildDir}/tmp/kotlin-classes/${variantName}"
                    def javaClasses = fileTree(dir: jClasses, excludes: excludes)

                    def kotlinClasses = fileTree(dir: kClasses, excludes: excludes)

                    classDirectories.from = files([javaClasses, kotlinClasses])
                    def sourceDirs = ["${project.projectDir}/src/main/java", "${project.projectDir}/src/main/kotlin",
                                      "${project.projectDir}/src/${variantName}/java", "${project.projectDir}/src/${variantName}/kotlin"]

                    sourceDirectories.from = files(sourceDirs)

                    executionData.from = files(["${project.buildDir}/jacoco/${testTaskName}.exec"])
                }
            }

    tasks.register('coverAllVariants') {
        dependsOn(provider {
            tasks.findAll { task -> task.name.endsWith('Coverage') }
        })
    }
}
```
3. project level build.gradle
```
buildscript {
    ext.kotlin_version = '1.9.10'
    ext.protobufVersion = '3.12.0'
    apply from: 'jacoco/project.gradle'

    repositories {
        google()
...
```
4.  app level build.gradle
```
dependencies {
}

apply plugin: 'com.google.gms.google-services'
apply from: '../jacoco/modules.gradle'

// Exclude the problematic library
configurations.all {
    ...
}
```

5. module level build.gradle
```
plugins {
...
}

apply from: '../jacoco/modules.gradle'

android { ...
```

I have also tried:
`jacoco/modules.gradle`
```
tasks.withType(JavaExec).configureEach {
    jvmArgs += ["-javaagent:${project.buildDir}/jacoco/jacocoagent.jar=excludes=com.ihealth.*"]
}
```

`gradle.properties`
```
jacoco.jvmArgs=-javaagent:jacocoagent.jar=excludes=com.ihealth.*
```

Could you guide me on what to try?
