### ISSUE TITLE
Kt  staitc interface mothod catch an NoSuchMethodError

### ISSUE THREAD

**Issue by SheepYoung** [jacoco/jacoco#1646]
THIS IS A BUG TRACKER ONLY. FOR QUESTIONS PLEASE CHECK FAQ OR USE FORUM:

### Steps to reproduce

click button to open a page of flutter

* JaCoCo version:  0.8.8
* Operating system:  android 14    jdk17

### Actual behaviour
app crash

call:  io.flutter.util.ViewUtils.calculateMaximumDisplayMetrics()

java.lang.NoSuchMethodError: No static method getOrCreate()Landroidx/window/layout/WindowMetricsCalculator; in class Landroidx/window/layout/WindowMetricsCalculator; or its super classes (declaration of 'androidx.window.layout.WindowMetricsCalculator' appears in /data/app/~~vMhR3XWO4jnwyCf4CxBD9w==/com.achievo.vipshop-qtYRhsYEqaSOz8A_st2qtg==/base.apk)
   at io.flutter.util.ViewUtils.calculateMaximumDisplayMetrics(ViewUtils.java:33)
at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:388)

(In case of exceptions provide FULL STACKTRACE)

java.lang.NoSuchMethodError: No static method getOrCreate()Landroidx/window/layout/WindowMetricsCalculator; in class Landroidx/window/layout/WindowMetricsCalculator; or its super classes (declaration of 'androidx.window.layout.WindowMetricsCalculator' appears in 
   at io.flutter.util.ViewUtils.calculateMaximumDisplayMetrics(ViewUtils.java:33)
at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:388)

```java
      WindowMetrics metrics =
          WindowMetricsCalculator.getOrCreate().computeMaximumWindowMetrics(activity);  // call the static mothod `getOrCreate` not exist
```

**see the byteCode of  androdx class:**
```java

package androidx.window.layout;

import android.app.Activity;
import kotlin.Metadata;
import kotlin.jvm.JvmStatic;
import org.jacoco.agent.rt.internal_b6258fc.Offline;

/* compiled from: WindowMetricsCalculator.kt */
@Metadata(d1 = {"\u0000\u0018\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0003\bf\u0018\u0000 \u00072\u00020\u0001:\u0001\u0007J\u0010\u0010\u0002\u001a\u00020\u00032\u0006\u0010\u0004\u001a\u00020\u0005H&J\u0010\u0010\u0006\u001a\u00020\u00032\u0006\u0010\u0004\u001a\u00020\u0005H&¨\u0006\b"}, d2 = {"Landroidx/window/layout/WindowMetricsCalculator;", "", "computeCurrentWindowMetrics", "Landroidx/window/layout/WindowMetrics;", "activity", "Landroid/app/Activity;", "computeMaximumWindowMetrics", "Companion", "window_release"}, k = 1, mv = {1, 5, 1}, xi = 48)
/* loaded from: classes.dex */
public interface WindowMetricsCalculator {
    public static final /* synthetic */ boolean[] $jacocoData;
    public static final Companion Companion;

    /* compiled from: WindowMetricsCalculator.kt */
    /* renamed from: androidx.window.layout.WindowMetricsCalculator$-CC  reason: invalid class name */
    /* loaded from: classes.dex */
    public final /* synthetic */ class CC {
        public static /* synthetic */ boolean[] $jacocoInit() {
            boolean[] zArr = WindowMetricsCalculator.$jacocoData;
            return zArr == null ? Offline.getProbes(-4264975019716910525L, "androidx/window/layout/WindowMetricsCalculator", 2) : zArr;
        }

        static {
            Companion companion = WindowMetricsCalculator.Companion;
        }

        @JvmStatic
        public static WindowMetricsCalculator getOrCreate() {
            boolean[] $jacocoInit = $jacocoInit();
            WindowMetricsCalculator orCreate = WindowMetricsCalculator.Companion.getOrCreate();
            $jacocoInit[0] = true;
            return orCreate;
        }
    }

    static {
        boolean[] probes = Offline.getProbes(-4264975019716910525L, "androidx/window/layout/WindowMetricsCalculator", 2);
        $jacocoData = probes;
        Companion = Companion.$$INSTANCE;
        probes[1] = true;
    }

    WindowMetrics computeCurrentWindowMetrics(Activity activity);

    WindowMetrics computeMaximumWindowMetrics(Activity activity);

    /* compiled from: WindowMetricsCalculator.kt */
    @Metadata(d1 = {"\u0000\u0012\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0000\b\u0086\u0003\u0018\u00002\u00020\u0001B\u0007\b\u0002¢\u0006\u0002\u0010\u0002J\b\u0010\u0003\u001a\u00020\u0004H\u0007¨\u0006\u0005"}, d2 = {"Landroidx/window/layout/WindowMetricsCalculator$Companion;", "", "()V", "getOrCreate", "Landroidx/window/layout/WindowMetricsCalculator;", "window_release"}, k = 1, mv = {1, 5, 1}, xi = 48)
    /* loaded from: classes.dex */
    public static final class Companion {
        static final /* synthetic */ Companion $$INSTANCE;
        private static transient /* synthetic */ boolean[] $jacocoData;

        private static /* synthetic */ boolean[] $jacocoInit() {
            boolean[] zArr = $jacocoData;
            if (zArr == null) {
                boolean[] probes = Offline.getProbes(-3287491637471800736L, "androidx/window/layout/WindowMetricsCalculator$Companion", 3);
                $jacocoData = probes;
                return probes;
            }
            return zArr;
        }

        static {
            boolean[] $jacocoInit = $jacocoInit();
            $$INSTANCE = new Companion();
            $jacocoInit[2] = true;
        }

        private Companion() {
            $jacocoInit()[0] = true;
        }

        @JvmStatic
        public final WindowMetricsCalculator getOrCreate() {
            boolean[] $jacocoInit = $jacocoInit();
            WindowMetricsCalculatorCompat windowMetricsCalculatorCompat = WindowMetricsCalculatorCompat.INSTANCE;
            $jacocoInit[1] = true;
            return windowMetricsCalculatorCompat;
        }
    }
}
```

**Comment by Godin** [comment]
> Steps to reproduce
> click button to open a page of flutter

Where we should click this button?

As requested by our bug report template 

https://github.com/jacoco/jacoco/blob/4f851cae6822289c55aff539786405d2bf473584/.github/ISSUE_TEMPLATE/2_bug_report.md?plain=1#L16-L17

https://github.com/jacoco/jacoco/blob/4f851cae6822289c55aff539786405d2bf473584/.github/ISSUE_TEMPLATE/2_bug_report.md?plain=1#L25

please provide complete executable reproducer.
