### ISSUE TITLE
ArrayIndexOutofBound exception when executing tests with Jmockit framework.

### ISSUE THREAD

**Issue by jitu1983** [jacoco/jacoco#1665]
### Steps to reproduce
* JaCoCo version:  0.8.11
* Jmockit version: 1.37
* Operating system: Windows
* JDK: open-jdk-21
* Tool integration: Maven 
* Complete executable reproducer: 
        try {
            new Expectations(TestHelper.class) {
                {
                    TestHelper.getNumber("Test");
                    result = 1;
                }
            };

        } catch (Exception e) {
            e.printStackTrace();
        }
		
* Steps: Run Junit test with JaCoCo.

java -ea -javaagent:C:\Users\jitendra.agrawal\.m2\repository\org\jmockit\jmockit\1.43\jmockit-1.43.jar -javaagent:C:\\Users\\jitendra.agrawal\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.11\\org.jacoco.agent-0.8.11-runtime.jar=destfile=C:\\EnergyComponent\\repository\\ec-application_14.0.X\\frmw-core\\frmw-core\\target\\jacoco.exec

### Expected behaviour
When running Junit tests using Jmockit framework for mocking objects, we are getting ArrayIndexOutOfBoundsException on initialization of Expectations.
java.lang.ArrayIndexOutOfBoundsException: Index 13578 out of bounds for length 61
	at mockit.asm.util.BytecodeReader.readItem(BytecodeReader.java:466)
	at mockit.asm.util.BytecodeReader.readClass(BytecodeReader.java:436)
	at mockit.asm.classes.ClassReader.<init>(ClassReader.java:63)
	at mockit.internal.ClassFile.createReaderOrGetFromCache(ClassFile.java:95)
	at mockit.internal.expectations.mocking.BaseTypeRedefinition.redefineClassAndItsSuperClasses(BaseTypeRedefinition.java:181)
	at mockit.internal.expectations.mocking.BaseTypeRedefinition.redefineMethodsAndConstructorsInTargetType(BaseTypeRedefinition.java:176)
	at mockit.internal.expectations.mocking.DynamicPartialMocking.applyPartialMockingToGivenClass(DynamicPartialMocking.java:69)
	at mockit.internal.expectations.mocking.DynamicPartialMocking.redefineClassHierarchy(DynamicPartialMocking.java:50)
	at mockit.internal.expectations.mocking.DynamicPartialMocking.redefineTypes(DynamicPartialMocking.java:28)
	at mockit.internal.expectations.RecordAndReplayExecution.applyDynamicPartialMocking(RecordAndReplayExecution.java:102)
	at mockit.internal.expectations.RecordAndReplayExecution.<init>(RecordAndReplayExecution.java:58)
	at mockit.Expectations.<init>(Expectations.java:154)
	at com.ec.eccore.util.date.DateHelperTest$1.<init>(DateHelperTest.java:71)

	
### Actual behaviour
We should get any exception when running Junit tests with JaCoCo and org.jmockit.jmockit enabled.

**Comment by Godin** [comment]
Please perform a search before creating a ticket in the future.
Here are first results of [search by the word "jmockit"](https://github.com/search?q=repo%3Ajacoco%2Fjacoco+jmockit&type=issues&state=closed) - https://github.com/jacoco/jacoco/issues/1419 , https://github.com/jacoco/jacoco/issues/896
