### ISSUE TITLE
Unable to run Maven Jacoco project when in directory with Diacritic characters

### ISSUE THREAD

**Issue by bedla** [jacoco/jacoco#1735]
Hi,
when I have my project in directory with strange characters I get following error. It is also possible to reproduce it with jacoco itself - see steps.

```
C:\Users\IvoŠmíd>cmd.exe /X /C "C:\Users\IvoŠmíd\.jdks\temurin-21.0.4\bin\java -javaagent:C:\\Temp\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.12\\org.jacoco.agent-0.8.12-runtime.jar=destfile=C:\\Users\\IvoŠmíd\\IdeaProjects\\partners\\vulnerability-overview\\target\\jacoco.exec -jar C:\Users\IvoŠmíd\AppData\Local\Temp\surefire4673284890245783090\surefirebooter-20241001172555164_3.jar C:\Users\IvoŠmíd\AppData\Local\Temp\surefire4673284890245783090 2024-10-01T17-25-54_933-jvmRun1 surefire-20241001172555164_1tmp surefire_0-20241001172555164_2tmp"
java.io.FileNotFoundException: C:\Users\Ivo?míd\IdeaProjects\partners\vulnerability-overview\target\jacoco.exe (Systém nemůže nalézt uvedenou cestu)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:289)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:230)
        at org.jacoco.agent.rt.internal_aeaf9ab.output.FileOutput.openFile(FileOutput.java:75)
        at org.jacoco.agent.rt.internal_aeaf9ab.output.FileOutput.startup(FileOutput.java:57)
        at org.jacoco.agent.rt.internal_aeaf9ab.Agent.startup(Agent.java:129)
        at org.jacoco.agent.rt.internal_aeaf9ab.Agent.getInstance(Agent.java:54)
        at org.jacoco.agent.rt.internal_aeaf9ab.PreMain.premain(PreMain.java:47)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:560)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:572)
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:560)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:572)
Caused by: java.io.FileNotFoundException: C:\Users\Ivo?míd\IdeaProjects\partners\vulnerability-overview\target\jacoco.exe (Systém nemůže nalézt uvedenou cestu)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:289)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:230)
        at org.jacoco.agent.rt.internal_aeaf9ab.output.FileOutput.openFile(FileOutput.java:75)
        at org.jacoco.agent.rt.internal_aeaf9ab.output.FileOutput.startup(FileOutput.java:57)
        at org.jacoco.agent.rt.internal_aeaf9ab.Agent.startup(Agent.java:129)
        at org.jacoco.agent.rt.internal_aeaf9ab.Agent.getInstance(Agent.java:54)
        at org.jacoco.agent.rt.internal_aeaf9ab.PreMain.premain(PreMain.java:47)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 3 more
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message Outstanding error when calling method in invokeJavaAgentMainMethod at s\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 627
*** java.lang.instrument ASSERTION FAILED ***: "success" with message invokeJavaAgentMainMethod failed at s\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 466
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at s\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 429
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
```

### Steps to reproduce

* JaCoCo version:  0.8.12
* Operating system: Windows 10
* Tool integration: Maven
* Complete executable reproducer: follow the steps
* Steps: 

1. create directory that contains non-ascii chars eg `IvoŠmíd`
2. clone Jacoco from github into this directorz
3. build with tests and see error above

### Expected behaviour

It works :)

### Actual behaviour

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.1.2:test (default-test) on project vulnerability-overview: 
[ERROR] 
[ERROR] Please refer to C:\Users\IvoŠmíd\IdeaProjects\partners\vulnerability-overview\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C "C:\Users\IvoŠmíd\.jdks\temurin-21.0.4\bin\java -javaagent:C:\\Users\\IvoŠmíd\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.12\\org.jacoco.agent-0.8.12-runtime.jar=destfile=C:\\Users\\IvoŠmíd\\IdeaProjects\\partners\\vulnerability-overview\\target\\jacoco.exec -jar C:\Users\IvoŠmíd\AppData\Local\Temp\surefire17601006454317711390\surefirebooter-20241001175108099_3.jar C:\Users\IvoŠmíd\AppData\Local\Temp\surefire17601006454317711390 2024-10-01T17-51-07_932-jvmRun1 surefire-20241001175108099_1tmp surefire_0-20241001175108099_2tmp"
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C "C:\Users\IvoŠmíd\.jdks\temurin-21.0.4\bin\java -javaagent:C:\\Users\\IvoŠmíd\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.12\\org.jacoco.agent-0.8.12-runtime.jar=destfile=C:\\Users\\IvoŠmíd\\IdeaProjects\\partners\\vulnerability-overview\\target\\jacoco.exec -jar C:\Users\IvoŠmíd\AppData\Local\Temp\surefire17601006454317711390\surefirebooter-20241001175108099_3.jar C:\Users\IvoŠmíd\AppData\Local\Temp\surefire17601006454317711390 2024-10-01T17-51-07_932-jvmRun1 surefire-20241001175108099_1tmp surefire_0-20241001175108099_2tmp"
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:643)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1203)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1055)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:871)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
[ERROR] 	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
[ERROR] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
[ERROR] 	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by marchof** [comment]
It looks like there is an encoding issue with agent parameter. We have a similar report in #1239.

**Comment by bedla** [comment]
I have read the ticket and it seems to me that they are the same. Closing.
