### ISSUE TITLE
Tests fail with java.lang.IndexOutOfBoundsException (jacoco-scala)

### ISSUE THREAD

**Issue by efisant** [jacoco/jacoco#182]
While in coverage profile (jacoco maven plugin with surefire plugin), tests fail with a  java.lang.IndexOutOfBoundsException. Same tests pass in non-coverage profile (surefire plugin only).

Running sample.api.CIMRequestSpec
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.269 sec <<< FAILURE!
A CIM requests  should::contains CreateCIM which is convertable to Map[String, Any](sample.api.CIMRequestSpec)  Time elapsed: 0.422 sec  <<< ERROR!
java.lang.IndexOutOfBoundsException: 3
	at sample.api.CreateCIM.productElement(CIMMessage.scala:13)
	at sample.api.MapRepresentable$$anonfun$getCCParams$1.apply(MapRepresentable.scala:15)
	at sample.api.MapRepresentable$$anonfun$getCCParams$1.apply(MapRepresentable.scala:15)
	at sample.api.MapRepresentable$class.getCCParams(MapRepresentable.scala:15)
	at sample.api.MapRepresentable$class.toMap(MapRepresentable.scala:18)
	at sample.api.CreateCIM.toMap(CIMMessage.scala:13)
	at sample.api.CIMRequestSpec$$anonfun$1$$anonfun$apply$5.apply(CIMRequestSpec.scala:22)
	at sample.api.CIMRequestSpec$$anonfun$1$$anonfun$apply$5.apply(CIMRequestSpec.scala:20)

git@github.com:efisant/jacocoAndScala.git

**Comment by Godin** [comment]
During instrumentation JaCoCo adds additional members to classes, which are not filtered after call "getDeclaredFields" in given example (https://github.com/efisant/jacocoAndScala) leading to IndexOutOfBoundsException. See FAQ "My code uses reflection. Why does it fail when I execute it with JaCoCo?" - http://www.eclemma.org/jacoco/trunk/doc/faq.html

**Comment by marchof** [comment]
@Godin Thx for looking into this!
