### ISSUE TITLE
Offline instrumentation for Android End With Crash

### ISSUE THREAD

**Issue by jamesguo** [jacoco/jacoco#202]
Hi gays,@marchof @Godin @mfriedenhagen @brockj 
I had problem when build apk with jacoco offline-mode,pls help!
**build with** 

```
jacoco-0.7.1-20140326.062324-3
MacOS 10.8.5
JAVA 1.6.0_65(64bit)
ANdroid SDK Build-tools 18.0.1
```

**Step 1**:
add Ant Task 

```
<project name="Example" xmlns:jacoco="antlib:org.jacoco.ant">
    <taskdef uri="antlib:org.jacoco.ant" resource="org/jacoco/ant/antlib.xml">
        <classpath path="MYPATH/lib/jacocoant.jar"/>
    </taskdef>
     <jacoco:instrument destdir="MYPATH/classes-instr">
        <fileset dir="MYPATH/classes" includes="**/*.class"/>
    </jacoco:instrument>
</project>
```

**Step 2**:
 ant -buildfile xxxx.xml
**Step 3**:
build apk with instrument classes & jacocoagent.jar
**Step 4**:
install apk & start, end with crash

```
04-01 16:35:28.855: W/System.err(9327): java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)
04-01 16:35:28.855: W/System.err(9327):     at libcore.io.IoBridge.open(IoBridge.java:416)
04-01 16:35:28.855: W/System.err(9327):     at java.io.FileOutputStream.<init>(FileOutputStream.java:88)
04-01 16:35:28.855: W/System.err(9327):     at org.jacoco.agent.rt.internal_4a442ed.output.FileOutput.openFile(FileOutput.java:67)
04-01 16:35:28.855: W/System.err(9327):     at org.jacoco.agent.rt.internal_4a442ed.output.FileOutput.startup(FileOutput.java:49)
04-01 16:35:28.855: W/System.err(9327):     at org.jacoco.agent.rt.internal_4a442ed.Agent.startup(Agent.java:122)
04-01 16:35:28.855: W/System.err(9327):     at org.jacoco.agent.rt.internal_4a442ed.Agent.getInstance(Agent.java:50)
04-01 16:35:28.855: W/System.err(9327):     at org.jacoco.agent.rt.internal_4a442ed.Offline.<clinit>(Offline.java:31)
04-01 16:35:28.855: W/System.err(9327):     at com.android.view.test.activity.LocalHtmlProvider.$jacocoInit(LocalHtmlProvider.java)
04-01 16:35:28.855: W/System.err(9327):     at com.android.view.test.activity.LocalHtmlProvider.<clinit>(LocalHtmlProvider.java)
04-01 16:35:28.855: W/System.err(9327):     at java.lang.Class.newInstanceImpl(Native Method)
04-01 16:35:28.855: W/System.err(9327):     at java.lang.Class.newInstance(Class.java:1319)
04-01 16:35:28.855: W/System.err(9327):     at android.app.ActivityThread.installProvider(ActivityThread.java:4625)
04-01 16:35:28.855: W/System.err(9327):     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4267)
04-01 16:35:28.855: W/System.err(9327):     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4209)
04-01 16:35:28.855: W/System.err(9327):     at android.app.ActivityThread.access$1300(ActivityThread.java:140)
04-01 16:35:28.855: W/System.err(9327):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1287)
04-01 16:35:28.855: W/System.err(9327):     at android.os.Handler.dispatchMessage(Handler.java:99)
04-01 16:35:28.855: W/System.err(9327):     at android.os.Looper.loop(Looper.java:137)
04-01 16:35:28.855: W/System.err(9327):     at android.app.ActivityThread.main(ActivityThread.java:4898)
04-01 16:35:28.855: W/System.err(9327):     at java.lang.reflect.Method.invokeNative(Native Method)
04-01 16:35:28.855: W/System.err(9327):     at java.lang.reflect.Method.invoke(Method.java:511)
04-01 16:35:28.855: W/System.err(9327):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1008)
04-01 16:35:28.855: W/System.err(9327):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775)
04-01 16:35:28.855: W/System.err(9327):     at dalvik.system.NativeStart.main(Native Method)
04-01 16:35:28.855: W/System.err(9327): Caused by: libcore.io.ErrnoException: open failed: EROFS (Read-only file system)
04-01 16:35:28.855: W/System.err(9327):     at libcore.io.Posix.open(Native Method)
04-01 16:35:28.855: W/System.err(9327):     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
04-01 16:35:28.855: W/System.err(9327):     at libcore.io.IoBridge.open(IoBridge.java:400)
04-01 16:35:28.855: W/System.err(9327):     ... 23 more

```

```
04-01 16:39:48.965: W/dalvikvm(31032): VFY: invoke type does not match method type of Ltest/android/view/home/testSplashActivity;.initFloatBtn
04-01 16:39:48.965: W/dalvikvm(31032): VFY:  rejecting opcode 0x6f at 0x0004
04-01 16:39:48.965: W/dalvikvm(31032): VFY:  rejected Ltest/android/view/home/testSplashActivity;.access$200 (Ltest/android/view/home/testSplashActivity;)V
04-01 16:39:48.965: W/dalvikvm(31032): Verifier rejected class Ltest/android/view/home/testSplashActivity;
04-01 16:39:48.965: W/dalvikvm(31032): Class init failed in newInstance call (Ltest/android/view/home/testSplashActivity;)
04-01 16:39:48.965: D/AndroidRuntime(31032): Shutting down VM
04-01 16:39:48.965: W/dalvikvm(31032): threadid=1: thread exiting with uncaught exception (group=0x41569ba8)
04-01 16:39:48.970: E/AndroidRuntime(31032): FATAL EXCEPTION: main
04-01 16:39:48.970: E/AndroidRuntime(31032): Process: test.android.view, PID: 31032
04-01 16:39:48.970: E/AndroidRuntime(31032): java.lang.VerifyError: test/android/view/home/testSplashActivity
04-01 16:39:48.970: E/AndroidRuntime(31032):    at java.lang.Class.newInstanceImpl(Native Method)
04-01 16:39:48.970: E/AndroidRuntime(31032):    at java.lang.Class.newInstance(Class.java:1208)
04-01 16:39:48.970: E/AndroidRuntime(31032):    at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
04-01 16:39:48.970: E/AndroidRuntime(31032):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2112)
04-01 16:39:48.970: E/AndroidRuntime(31032):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
04-01 16:39:48.970: E/AndroidRuntime(31032):    at android.app.ActivityThread.access$800(ActivityThread.java:135)
04-01 16:39:48.970: E/AndroidRuntime(31032):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
04-01 16:39:48.970: E/AndroidRuntime(31032):    at android.os.Handler.dispatchMessage(Handler.java:102)
04-01 16:39:48.970: E/AndroidRuntime(31032):    at android.os.Looper.loop(Looper.java:136)
04-01 16:39:48.970: E/AndroidRuntime(31032):    at android.app.ActivityThread.main(ActivityThread.java:5017)
04-01 16:39:48.970: E/AndroidRuntime(31032):    at java.lang.reflect.Method.invokeNative(Native Method)
04-01 16:39:48.970: E/AndroidRuntime(31032):    at java.lang.reflect.Method.invoke(Method.java:515)
04-01 16:39:48.970: E/AndroidRuntime(31032):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
04-01 16:39:48.970: E/AndroidRuntime(31032):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
04-01 16:39:48.970: E/AndroidRuntime(31032):    at dalvik.system.NativeStart.main(Native Method)

```

**Comment by kellyfj** [comment]
Quick Question: Is the destfile supposed to be a writable folder on my computer (e.g. /tmp) or on the Android emulator filesystem?

**Comment by Godin** [comment]
@jamesguo @kellyfj Sorry, this is not a QA forum, but an issue tracker. So please switch to https://groups.google.com/forum/#!forum/jacoco where you can get wider audience to help address your questions.

**Comment by youdidut** [comment]
Hi, James!
Have you figured out how to use Jacoco on Android with Ant? I have found out a way with Gradle but I also need to do it with Ant. 
I am also Chinese so we could talk on qq:150484253 if you prefer. 谢谢！

Di
