### ISSUE TITLE
Already instrumented exception when running tests with jmockit

### ISSUE THREAD

**Issue by david-mas** [jacoco/jacoco#273]
When using jacoco together with jmockit, there are many cases were jmockit attempts to reload the class, which in turn causes jacoco to try to instrument it again. This causes an exception like the following.

```
java.lang.instrument.IllegalClassFormatException: Error while instrumenting class org/my/Object.
	at org.jacoco.agent.rt.internal_5d10cad.CoverageTransformer.transform(CoverageTransformer.java:91)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:169)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
	at sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.redefineClasses(InstrumentationImpl.java:150)
	at mockit.internal.startup.Startup.redefineMethods(Startup.java:246)
	at mockit.internal.RedefinitionEngine.redefineClasses(RedefinitionEngine.java:26)
	at mockit.internal.expectations.mocking.BaseTypeRedefinition.applyClassRedefinition(BaseTypeRedefinition.java:235)
	at mockit.internal.expectations.mocking.BaseTypeRedefinition.redefineClass(BaseTypeRedefinition.java:228)
	at mockit.internal.expectations.mocking.BaseTypeRedefinition.redefineClassAndItsSuperClasses(BaseTypeRedefinition.java:199)
	at mockit.internal.expectations.mocking.BaseTypeRedefinition.redefineClassAndItsSuperClasses(BaseTypeRedefinition.java:215)
	at mockit.internal.expectations.mocking.BaseTypeRedefinition.redefineMethodsAndConstructorsInTargetType(BaseTypeRedefinition.java:185)
	at mockit.internal.expectations.mocking.BaseTypeRedefinition.redefineTargetClassAndCreateInstanceFactory(BaseTypeRedefinition.java:268)
	at mockit.internal.expectations.mocking.BaseTypeRedefinition.redefineType(BaseTypeRedefinition.java:67)
	at mockit.internal.expectations.mocking.TypeRedefinition.redefineType(TypeRedefinition.java:19)
	at mockit.internal.expectations.mocking.ParameterTypeRedefinitions.redefineMockedType(ParameterTypeRedefinitions.java:89)
	at mockit.internal.expectations.mocking.ParameterTypeRedefinitions.redefineMockedTypes(ParameterTypeRedefinitions.java:78)
	at mockit.internal.expectations.mocking.ParameterTypeRedefinitions.<init>(ParameterTypeRedefinitions.java:43)
	at mockit.integration.internal.TestRunnerDecorator.createInstancesForMockParameters(TestRunnerDecorator.java:174)
	at mockit.integration.junit4.internal.JUnit4TestRunnerDecorator.executeTestMethod(JUnit4TestRunnerDecorator.java:136)
	at mockit.integration.junit4.internal.JUnit4TestRunnerDecorator.invokeExplosively(JUnit4TestRunnerDecorator.java:71)
	at mockit.integration.junit4.internal.MockFrameworkMethod.invokeExplosively(MockFrameworkMethod.java:40)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:82)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:134)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
Caused by: java.lang.IllegalStateException: Class org/my/Object is already instrumented.
	at org.jacoco.agent.rt.internal_5d10cad.core.internal.instr.ClassInstrumenter.assertNotInstrumented(ClassInstrumenter.java:138)
	at org.jacoco.agent.rt.internal_5d10cad.core.internal.instr.ClassInstrumenter.visitField(ClassInstrumenter.java:81)
	at org.jacoco.agent.rt.internal_5d10cad.asm.ClassVisitor.visitField(Unknown Source)
	at org.jacoco.agent.rt.internal_5d10cad.asm.ClassReader.a(Unknown Source)
	at org.jacoco.agent.rt.internal_5d10cad.asm.ClassReader.accept(Unknown Source)
	at org.jacoco.agent.rt.internal_5d10cad.asm.ClassReader.accept(Unknown Source)
	at org.jacoco.agent.rt.internal_5d10cad.core.instr.Instrumenter.instrument(Instrumenter.java:74)
	at org.jacoco.agent.rt.internal_5d10cad.core.instr.Instrumenter.instrument(Instrumenter.java:87)
	at org.jacoco.agent.rt.internal_5d10cad.CoverageTransformer.transform(CoverageTransformer.java:89)
```

I know this is something complex and jacoco by nature does not work well with mocking, but let's think about the possibility: 
What if (by using a parameter in the maven plugin), the user had the option to make the "already instrumented" check be lenient. By lenient I mean, let jacoco check if already instrumented, but if so do not throw an exception and instead simply do not instrument. I think in such case the worse that could happen is there would not be coverage information from that test.

**Comment by marchof** [comment]
What version of JaCoCo are you using? Since version 0.7.1 JaCoCo ignores re-defined classes.

Also JaCoCo should already behave "lenient": The exception is just dumped to the console but should not prevent class loading.

**Comment by david-mas** [comment]
It's the maven plugin version 0.6.2.201302030002. I'll check with the latest and report back.

**Comment by david-mas** [comment]
Update: after setting version to 0.7.2.201409121644, I'm getting the same errors as #272. So closing as this is a duplicate.
