### ISSUE TITLE
IllegalStateException: Incompatible execution data for class org/junit/runner/Description

### ISSUE THREAD

**Issue by don-vip** [jacoco/jacoco#286]
Hi,
We're using Jacoco on JOSM project. We switched from Jacoco 0.7.2 to 0.7.3 in this commit:
https://josm.openstreetmap.de/changeset/8090/josm/
Since, I have a Sonar analysis that fails every time with the same error:
http://donvip.fr/jenkins/job/JOSM-Plugins-Sonar/211/console

    java.lang.IllegalStateException: Incompatible execution data for class org/junit/runner/Description with id c3b4a36e785ee4be.
	at org.jacoco.core.data.ExecutionData.assertCompatibility(ExecutionData.java:181)
	at org.jacoco.core.data.ExecutionData.merge(ExecutionData.java:144)
	at org.jacoco.core.data.ExecutionData.merge(ExecutionData.java:117)
	at org.jacoco.core.data.ExecutionDataStore.put(ExecutionDataStore.java:53)
	at org.jacoco.core.data.ExecutionDataStore.visitClassExecution(ExecutionDataStore.java:175)
	at org.jacoco.core.data.ExecutionDataReader.readExecutionData(ExecutionDataReader.java:149)
	at org.jacoco.core.data.ExecutionDataReader.readBlock(ExecutionDataReader.java:113)
	at org.jacoco.core.data.ExecutionDataReader.read(ExecutionDataReader.java:87)
	at org.sonar.plugins.jacoco.JaCoCoOverallSensor.loadSourceFiles(JaCoCoOverallSensor.java:124)
	at org.sonar.plugins.jacoco.JaCoCoOverallSensor.mergeReports(JaCoCoOverallSensor.java:99)
	at org.sonar.plugins.jacoco.JaCoCoOverallSensor.analyse(JaCoCoOverallSensor.java:90)
	at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:79)

Jacoco calls Junit from Ant as follows:

    <junit printsummary="yes" fork="true" forkmode="once" dir="${basedir}">

(See https://trac.openstreetmap.org/browser/subversion/applications/editors/josm/plugins/build-common.xml#L443 )

I have no idea what's wrong but it looks like somewhat a regression or a change of behaviour between 0.7.2 and 0.7.3.

**Comment by marchof** [comment]
With 0.7.3 we're actually missing a probe at the beginning of a try/catch block when the first instruction of the block is only reached via jump instruction. Validation test: https://gist.github.com/marchof/d0f53b31f1bd3ca4dfa6

**Comment by marchof** [comment]
@don-vip The problem should be fixed on trunk. Can you please re-test with 0.7.4-SNAPSHOT?

**Comment by don-vip** [comment]
Sure :)

**Comment by don-vip** [comment]
I confirm: the problem is fixed! Thanks for the quick fix :)
