### ISSUE TITLE
Jacoco breaks under TeamCity with Java 8

### ISSUE THREAD

**Issue by tmaus** [jacoco/jacoco#347]
Hi guys, 

running into " java.lang.StackOverflowError" but only @ TeamCity. 
It does not break on command line. 

Setup:
TeamCity:  8+9
OS: Linux
Java 8
Jacoco latest build 

Any idea how to take it from here ?

Log snippet:

TeamCity server version is 9.0.4 (build 32407)
[16:32:02]Skip checking for changes - changes are already collected
[16:32:02]Agent time zone: Asia/Singapore
[16:32:02]Agent is running under JRE: 1.8.0_51-b16
[16:32:02]Clearing temporary directory: /opt/TeamCity/buildAgent/temp/buildTmp
[16:32:02]Publishing internal artifacts
[16:32:02][Publishing internal artifacts] Sending using WebPublisher
[16:32:02][Publishing internal artifacts] Sending using ArtifactsCachePublisher
[16:32:02]Using vcs information from agent file: 1b68ef1080e32798.xml
[16:32:02]Clean build enabled: removing old files from /opt/TeamCity/buildAgent/work/1b68ef1080e32798
[16:32:02]Checkout directory: /opt/TeamCity/buildAgent/work/1b68ef1080e32798
[16:32:02]Updating sources: server side checkout
[16:32:02][Updating sources] Will perform clean checkout. Reason: "Clean all files before build" turned on
[16:32:02][Updating sources] Transferring cached clean patch for VCS root: OPSB-36
[16:32:02][Updating sources] Building incremental patch over the cached patch
[16:32:03][Updating sources] Repository sources transferred: 1.05 MB total
[16:32:03][Updating sources] Removing /opt/TeamCity/buildAgent/work/1b68ef1080e32798
[16:32:03][Updating sources] Updating /opt/TeamCity/buildAgent/work/1b68ef1080e32798
[16:32:03]##teamcity[buildStatisticValue key='buildStageDuration:sourcesUpdate' value='849.0']
[16:32:03]Step 1/1: Gradle (19s)
[16:32:03][Step 1/1] ##teamcity[buildStatisticValue key='buildStageDuration:firstStepPreparation' value='34.0']
[16:32:03][Step 1/1] ##teamcity[buildStatisticValue key='buildStageDuration:buildStepRUNNER_4' value='0.0']
[16:32:03][Step 1/1] Starting: bash /opt/TeamCity/buildAgent/work/1b68ef1080e32798/gradlew --init-script /opt/TeamCity/buildAgent/plugins/gradle-runner/scripts/init.gradle -s clean build test
[16:32:03][Step 1/1] in directory: /opt/TeamCity/buildAgent/work/1b68ef1080e32798
[16:32:05][Step 1/1] Starting Gradle in TeamCity build 37
[16:32:09][Step 1/1] :clean
[16:32:09][Step 1/1] :compileJava
[16:32:10][Step 1/1] :processResources
[16:32:10][Step 1/1] :classes
[16:32:10][Step 1/1] :jar
[16:32:10][Step 1/1] :findMainClass
[16:32:10][Step 1/1] :startScripts
[16:32:11][Step 1/1] :distTar
[16:32:11][Step 1/1] :distZip (1s)
[16:32:12][Step 1/1] :bootRepackage
[16:32:13][Step 1/1] :assemble
[16:32:14][Step 1/1] Download https://repo1.maven.org/maven2/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946.pom
[16:32:14][Step 1/1] Download https://repo1.maven.org/maven2/org/jacoco/org.jacoco.build/0.7.5.201505241946/org.jacoco.build-0.7.5.201505241946.pom
[16:32:15][Step 1/1] Download https://repo1.maven.org/maven2/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946.jar
[16:32:15][Step 1/1] :compileTestJava
[16:32:16][:compileTestJava] Note: Some input files use unchecked or unsafe operations.
[16:32:16][:compileTestJava] Note: Recompile with -Xlint:unchecked for details.
[16:32:16][Step 1/1] :processTestResources UP-TO-DATE
[16:32:16][Step 1/1] :testClasses
[16:32:16][Step 1/1] :test (3s)
[16:32:17][:test] Exception in thread "main" java.lang.reflect.InvocationTargetException
[16:32:17][:test] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:32:17][:test] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:32:17][:test] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:32:17][:test] 	at java.lang.reflect.Method.invoke(Method.java:497)
[16:32:17][:test] 	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
[16:32:17][:test] 	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
[16:32:17][:test] Caused by: java.lang.StackOverflowError
[16:32:17][:test] 	at java.util.HashMap.hash(HashMap.java:338)
[16:32:17][:test] 	at java.util.HashMap.get(HashMap.java:556)
[16:32:17][:test] 	at org.jacoco.agent.rt.internal_b0d6a23.core.data.ExecutionDataStore.get(ExecutionDataStore.java:130)
[16:32:17][:test] 	at org.jacoco.agent.rt.internal_b0d6a23.core.runtime.RuntimeData.getExecutionData(RuntimeData.java:120)
[16:32:17][:test] 	at org.jacoco.agent.rt.internal_b0d6a23.core.runtime.RuntimeData.getProbes(RuntimeData.java:148)
[16:32:17][:test] 	at org.jacoco.agent.rt.internal_b0d6a23.core.runtime.RuntimeData.equals(RuntimeData.java:162)
[16:32:17][:test] 	at org.jacoco.agent.rt.internal_b0d6a23.core.data.ExecutionData.$jacocoInit(ExecutionData.java)
[16:32:17][:test] 	at org.jacoco.agent.rt.internal_b0d6a23.core.data.ExecutionData.<init>(ExecutionData.java)
[16:32:17][:test] 	at org.jacoco.agent.rt.internal_b0d6a23.core.data.ExecutionDataStore.get(ExecutionDataStore.java:132)
[16:32:17][:test] 	at org.jacoco.agent.rt.internal_b0d6a23.core.runtime.RuntimeData.getExecutionData(RuntimeData.java:120)
[16:32:17][:test] 	at org.jacoco.agent.rt.internal_b0d6a23.core.runtime.RuntimeData.getProbes(RuntimeData.java:148)

**Comment by marchof** [comment]
This happens if two JaCoCo agents from different JaCoCo agents are configured.

**Comment by Godin** [comment]
@marchof question of two conflicting agents seems quite recurring - I'm wondering, if we can improve error-reporting in such case?

**Comment by marchof** [comment]
Currently the fully qualified package name is the indicator that a class is part of the JaCoCo runtime and must not be instrumented. As we shade the package name with a revision specific hash value one version of JaCoCo does not recognice another version of JaCoCo. This also allows to run JaCoCo code coverage on JaCoCo itself.
