### ISSUE TITLE
Ant report tool should help users to work around "Can't add different class with same name" fatal error

### ISSUE THREAD

**Issue by ben-spiller** [jacoco/jacoco#352]
It's understandable (and explained clearly in the FAQ, thanks) why the "Can't add different class with same name" IllegalStateException is sometimes thrown. However despite this it's very difficult at present for a user to cope with it when it does occur(and I've seen more than one user mention this has caused them pain on the forums), not least because it's very hard to even track down where the conflicting occurrences of the class have come from, and there are often third party dependencies involved which are hard or impossible for the user to resolve themselves.

Two things that would help enormously are:

- if the error message could mention both of the jars/directories that contain the problematic class, as it's very difficult and timeconsuming to find where the conflict could be otherwise

- if there was an option to just treat it as a warning not an error that prevents the whole reporting being generated. A lot of the time you don't even care about getting coverage info for the class that suffers from this problem, but you do want the rest of the report. And it could be extremely difficult to fix since sometimes the duplicated classes are in third party jars that you unavoidably depend upon. So an option to just ignore the error, or just ignore the problematic class, would be greatly appreciated by eclemma users.

The current error message is just "Error while creating report" but you can get a little more info (though only about one of the two jars that caused the conflict) by enabling ant's verbose logging:

java_coverage_build.xml:47: Error while creating report
at org.jacoco.ant.ReportTask.execute(ReportTask.java:501)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
at org.apache.tools.ant.Task.perform(Task.java:348)
at org.apache.tools.ant.Target.execute(Target.java:357)
at org.apache.tools.ant.Target.performTasks(Target.java:385)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1337)
at org.apache.tools.ant.Project.executeTarget(Project.java:1306)
at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
at org.apache.tools.ant.Project.executeTargets(Project.java:1189)
at org.apache.tools.ant.Main.runBuild(Main.java:758)
at org.apache.tools.ant.Main.startAnt(Main.java:217)
at org.apache.tools.ant.launch.Launcher.run(Launcher.java:257)
at org.apache.tools.ant.launch.Launcher.main(Launcher.java:104)
Caused by: java.io.IOException: Error while analyzing class XXXXXXXXXXXXXXX
at org.jacoco.core.analysis.Analyzer.analyzerError(Analyzer.java:150)
at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:144)
at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:175)
at org.jacoco.core.analysis.Analyzer.analyzeZip(Analyzer.java:246)
at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:178)
at org.jacoco.ant.ReportTask.createBundle(ReportTask.java:570)
at org.jacoco.ant.ReportTask.createReport(ReportTask.java:542)
at org.jacoco.ant.ReportTask.createReport(ReportTask.java:555)
at org.jacoco.ant.ReportTask.execute(ReportTask.java:495)
... 17 more
Caused by: java.lang.IllegalStateException: Can't add different class with same name: XXXXXXXXXXXXX
at org.jacoco.core.analysis.CoverageBuilder.visitCoverage(CoverageBuilder.java:106)
at org.jacoco.core.analysis.Analyzer$1.visitEnd(Analyzer.java:92)
at org.jacoco.asm.ClassVisitor.visitEnd(ClassVisitor.java:317)
at org.jacoco.core.internal.flow.ClassProbesAdapter.visitEnd(ClassProbesAdapter.java:98)
at org.jacoco.asm.ClassReader.accept(ClassReader.java:697)
at org.jacoco.asm.ClassReader.accept(ClassReader.java:506)
at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:107)
at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:142)
... 24 more
--- Nested Exception ---
java.io.IOException: Error while analyzing class XXXXXXXXXXXXXXX
at org.jacoco.core.analysis.Analyzer.analyzerError(Analyzer.java:150)
at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:144)
at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:175)
at org.jacoco.core.analysis.Analyzer.analyzeZip(Analyzer.java:246)
at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:178)
at org.jacoco.ant.ReportTask.createBundle(ReportTask.java:570)
at org.jacoco.ant.ReportTask.createReport(ReportTask.java:542)
at org.jacoco.ant.ReportTask.createReport(ReportTask.java:555)
at org.jacoco.ant.ReportTask.execute(ReportTask.java:495)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
at org.apache.tools.ant.Task.perform(Task.java:348)
at org.apache.tools.ant.Target.execute(Target.java:357)
at org.apache.tools.ant.Target.performTasks(Target.java:385)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1337)
at org.apache.tools.ant.Project.executeTarget(Project.java:1306)
at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
at org.apache.tools.ant.Project.executeTargets(Project.java:1189)
at org.apache.tools.ant.Main.runBuild(Main.java:758)
at org.apache.tools.ant.Main.startAnt(Main.java:217)
at org.apache.tools.ant.launch.Launcher.run(Launcher.java:257)
at org.apache.tools.ant.launch.Launcher.main(Launcher.java:104)
Caused by: java.lang.IllegalStateException: Can't add different class with same name: com/progress/tools/c
at org.jacoco.core.analysis.CoverageBuilder.visitCoverage(CoverageBuilder.java:106)
at org.jacoco.core.analysis.Analyzer$1.visitEnd(Analyzer.java:92)
at org.jacoco.asm.ClassVisitor.visitEnd(ClassVisitor.java:317)
at org.jacoco.core.internal.flow.ClassProbesAdapter.visitEnd(ClassProbesAdapter.java:98)
at org.jacoco.asm.ClassReader.accept(ClassReader.java:697)
at org.jacoco.asm.ClassReader.accept(ClassReader.java:506)
at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:107)
at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:142)

**Comment by marchof** [comment]
Providing location information for both classes looks reasonable and should be be doable.

Ignoring the situation (or print warnings) is questionable though: In this case coverage is calculated only for a random version of the class.

If you use Ant tasks please consider using groups in the report definition: Class names only have to be unique within groups. if you define groups for you third party libraries you can see coverage separately for the different versions of the classes.

**Comment by ben-spiller** [comment]
Thanks. The reason the ability to ignore would be useful is where the differing versions are in some code (maybe third party) that's hard to exclude (maybe they're in the same jar with some non-duplicated classes you _do_ care about due to a badly designed build process you don't have control over) and you don't care about seeing coverage for the duplicate class, but want to still be able to get on and generate information for the classes that don't suffer this problem

**Comment by ekpatil** [comment]
I also experienced similar problem - 
i had same name class in two different packages but root are same, i.e - 
com.project.services.dto.MyClass.java
com.project.services.entity.MyClass.java

this was failing for rule MISSEDCOUNT. even-though i have added test cases for newly added class - 
com.project.services.entity.MyClass.java.

what I support like- classes should be differentiated with their package names while checking their test cases. so that such problem should not occur. 
again I am not sure about its complexity but this is what expected from user like me.. :)
Thanks.

**Comment by Godin** [comment]
@ekpatil classes are already differentiated using fully qualified name (i.e. including package name), this ticket is about classes that have same fully qualified name but different physical location, e.g. located in different JAR files.

**Comment by walnut-tom** [comment]
java9 modules 都会有这个问题
Multi-Release: true
