### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: org/jacoco/agent/rt/internal_b0d6a23/Offline

### ISSUE THREAD

**Issue by balaji-raj** [jacoco/jacoco#377]
How to rectify it??

The full server log is 

10:40:55,731 INFO  [org.jboss.modules] JBoss Modules version 1.1.1.GA
10:40:58,916 INFO  [org.jboss.msc] JBoss MSC version 1.0.2.GA
10:40:59,166 INFO  [org.jboss.as] JBAS015899: JBoss AS 7.1.1.Final "Brontes" starting
10:41:06,585 INFO  [org.jboss.as.server] JBAS015888: Creating http management service using socket-binding (management-http)
10:41:06,587 INFO  [org.xnio] XNIO Version 3.0.3.GA
10:41:06,651 INFO  [org.xnio.nio] XNIO NIO Implementation Version 3.0.3.GA
10:41:06,727 INFO  [org.jboss.remoting] JBoss Remoting version 3.2.3.GA
10:41:06,822 INFO  [org.jboss.as.configadmin] JBAS016200: Activating ConfigAdmin Subsystem
10:41:06,826 INFO  [org.jboss.as.logging] JBAS011502: Removing bootstrap log handlers
10:41:08,414 INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 27) JBAS010403: Deploying JDBC-co
mpliant driver class org.h2.Driver (version 1.3)
10:41:08,583 INFO  [org.jboss.as.security] (MSC service thread 1-1) JBAS013100: Current PicketBox version=4.0.7.Final
10:41:08,934 INFO  [org.jboss.as.connector] (MSC service thread 1-2) JBAS010408: Starting JCA Subsystem (JBoss IronJacamar 1.0.9.F
inal)
10:41:08,948 INFO  [org.jboss.as.naming] (MSC service thread 1-2) JBAS011802: Starting Naming Service
10:41:09,041 INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 27) JBAS010403: Deploying JDBC-co
mpliant driver class com.tandem.t4jdbc.SQLMXDriver (version 3.11)
10:41:09,149 INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 27) JBAS010403: Deploying JDBC-co
mpliant driver class com.microsoft.sqlserver.jdbc.SQLServerDriver (version 2.0)
10:41:10,683 INFO  [org.jboss.as.mail.extension] (MSC service thread 1-1) JBAS015400: Bound mail session [java:jboss/mail/Default]
10:41:11,102 INFO  [org.apache.coyote.http11.Http11Protocol] (MSC service thread 1-1) Starting Coyote HTTP/1.1 on http-localhost-1
27.0.0.1-80
10:41:12,873 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-1) JBAS010400: Bound data source [java:/N
ET911MSSQLXADS]
10:41:12,873 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-1) JBAS010400: Bound data source [java:/9
11NET_AMERITECH]
10:41:13,685 INFO  [org.jboss.ws.common.management.AbstractServerConfig] (MSC service thread 1-2) JBoss Web Services - Stack CXF S
erver 4.0.2.GA
10:41:14,665 WARN  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-1) JBAS015005: Reliable deployment behaviour is 
not possible when auto-deployment of exploded content is enabled (i.e. deployment without use of ".dodeploy"' marker files). Confi
guration of auto-deployment of exploded content is not recommended in any situation where reliability is desired. Configuring the 
deployment scanner's auto-deploy-exploded setting to "false" is recommended.
10:41:14,668 INFO  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-1) JBAS015012: Started FileSystemDeploymentServi
ce for directory C:\jboss-as-7.1.1.Final\standalone\deployments
10:41:14,689 INFO  [org.jboss.as.remoting] (MSC service thread 1-2) JBAS017100: Listening on localhost/127.0.0.1:4447
10:41:14,707 INFO  [org.jboss.as.remoting] (MSC service thread 1-2) JBAS017100: Listening on /127.0.0.1:9999
10:41:16,342 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015951: Admin console listening on http://127.0.0.1:9990
10:41:16,343 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015874: JBoss AS 7.1.1.Final "Brontes" started in 23897ms - Started
 140 of 226 services (74 services are passive or on-demand)
10:41:17,716 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) JBAS015876: Starting deployment of "911net-web.war"
10:41:17,717 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) JBAS015876: Starting deployment of "911Net.war"
10:41:21,897 INFO  [stdout] (MSC service thread 1-1) 2016-01-28 10:41:21 JRebel: Directory 'C:\intrado\dev-14.1.0\components\911ne
t\target\classes' will be monitored for changes.

10:41:25,422 INFO  [stdout] (MSC service thread 1-1) 2016-01-28 10:41:25 JRebel: Directory 'C:\intrado\dev-14.1.0\components\crdb\
target\classes' will be monitored for changes.

10:41:25,486 INFO  [stdout] (MSC service thread 1-1) 2016-01-28 10:41:25 JRebel: Directory 'C:\intrado\dev-14.1.0\components\tss\t
arget\classes' will be monitored for changes.

10:41:29,592 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-2) JBAS015893: Encountered invalid class name 'org.sprin
gframework.context.ApplicationContext,org.springframework.beans.BeansException' for service type 'org.apache.cxf.bus.factory'
10:41:31,086 INFO  [org.jboss.web] (MSC service thread 1-1) JBAS018210: Registering web context: /911net-web
10:41:32,475 WARN  [org.jboss.as.ee] (MSC service thread 1-1) JBAS011006: Not installing optional component org.apache.cxf.transpo
rt.http.Servlet3ContinuationProvider$Servlet3Continuation due to exception: org.jboss.as.server.deployment.DeploymentUnitProcessin
gException: JBAS011054: Could not find default constructor for class org.apache.cxf.transport.http.Servlet3ContinuationProvider$Se
rvlet3Continuation
	at org.jboss.as.ee.component.ComponentDescription$DefaultComponentConfigurator.configure(ComponentDescription.java:606)
	at org.jboss.as.ee.component.deployers.EEModuleConfigurationProcessor.deploy(EEModuleConfigurationProcessor.java:81)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:113) [jboss-as-server-7.1.1.Fi
nal.jar:7.1.1.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811) [jboss-msc-1.0.2.GA.jar:1.
0.2.GA]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [rt.jar:1.7.0_03]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [rt.jar:1.7.0_03]
	at java.lang.Thread.run(Thread.java:722) [rt.jar:1.7.0_03]

10:41:32,885 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-1) JBAS010403: Deploying JDBC-compliant driver cl
ass com.microsoft.sqlserver.jdbc.SQLServerDriver (version 2.0)
10:41:33,068 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/911Net]] (MSC service thread 1-1) Error co
nfiguring application listener of class com.intrado.net911.web.listener.Net911ContextListener: java.lang.IllegalStateException: JB
AS011048: Failed to construct component instance
	at org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:163) [jboss-as-ee-7.1.1.Final.jar:7.1.
1.Final]
	at org.jboss.as.ee.component.BasicComponent.createInstance(BasicComponent.java:85) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.as.web.deployment.component.WebComponentInstantiator$1.<init>(WebComponentInstantiator.java:57) [jboss-as-web-7.1.1.
Final.jar:7.1.1.Final]
	at org.jboss.as.web.deployment.component.WebComponentInstantiator.getReference(WebComponentInstantiator.java:55) [jboss-as-web-7.
1.1.Final.jar:7.1.1.Final]
	at org.jboss.as.web.deployment.WebInjectionContainer.instantiate(WebInjectionContainer.java:99) [jboss-as-web-7.1.1.Final.jar:7.1
.1.Final]
	at org.jboss.as.web.deployment.WebInjectionContainer.newInstance(WebInjectionContainer.java:78) [jboss-as-web-7.1.1.Final.jar:7.1
.1.Final]
	at org.jboss.as.web.deployment.WebInjectionContainer.newInstance(WebInjectionContainer.java:72) [jboss-as-web-7.1.1.Final.jar:7.1
.1.Final]
	at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:3342) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:3850) [jbossweb-7.0.13.Final.jar:]
	at org.jboss.as.web.deployment.WebDeploymentService.start(WebDeploymentService.java:90) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final
]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [rt.jar:1.7.0_03]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [rt.jar:1.7.0_03]
	at java.lang.Thread.run(Thread.java:722) [rt.jar:1.7.0_03]
Caused by: java.lang.IllegalStateException: Failed to invoke constructor
	at org.jboss.msc.value.ConstructedValue.getValue(ConstructedValue.java:65)
	at org.jboss.as.naming.ValueManagedReferenceFactory.getReference(ValueManagedReferenceFactory.java:49)
	at org.jboss.as.ee.component.ManagedReferenceInterceptorFactory$ManagedReferenceInterceptor.processInvocation(ManagedReferenceInt
erceptorFactory.java:90) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53) [jboss-invocation-1.1.1.Final.jar:1.1.1.Fi
nal]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.as.ee.component.TCCLInterceptor.processInvocation(TCCLInterceptor.java:45) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61) [jboss-invocation-1.1.1.Final.jar:1.1.1.
Final]
	at org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:161) [jboss-as-ee-7.1.1.Final.jar:7.1.
1.Final]
	... 14 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [rt.jar:1.7.0_03]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) [rt.jar:1.7.0_03]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [rt.jar:1.7.0_03]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525) [rt.jar:1.7.0_03]
	at org.jboss.msc.value.ConstructedValue.getValue(ConstructedValue.java:61)
	... 23 more
Caused by: java.lang.NoClassDefFoundError: org/jacoco/agent/rt/internal_b0d6a23/Offline
	at com.intrado.net911.web.listener.Net911ContextListener.$jacocoInit(Net911ContextListener.java) [classes:]
	... 28 more
Caused by: java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_b0d6a23.Offline from [Module "deployment.911Net.war:main
" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:468)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:456)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:120)
	... 29 more

**Comment by marchof** [comment]
For offline instrumentation you need to deploy jacocoagent with your app. See documentation:

http://eclemma.org/jacoco/trunk/doc/offline.html

Please user our mailing list for general questions: https://groups.google.com/forum/?fromgroups=#!forum/jacoco
