### ISSUE TITLE
java.lang.annotation.AnnotationFormatError: Malformed method on an annotation type

### ISSUE THREAD

**Issue by charlesxucheng** [jacoco/jacoco#459]
Stack Trace:
```
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:183)
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:123)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:228)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:230)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:249)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:89)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:193)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'exceptionFactory': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: java.util.Map stars.em.batch.ExceptionFactory.exceptionServices; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ACCOUNT_GROUP_VALIDATION' defined in file [C:\svn_wa\STARS-CurrentSprint\src\Java\exception-manager\bin\stars\em\service\AccountGroupValidationServiceImpl.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [stars.em.repo.AcctGroupRepo]: Error creating bean with name 'acctGroupRepo' defined in file [C:\svn_wa\STARS-CurrentSprint\src\Java\exception-manager\bin\stars\em\repo\AcctGroupRepo.class]: Initialization of bean failed; nested exception is java.lang.IllegalStateException: Failed to introspect annotations on class stars.em.repo.AcctGroupRepo; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'acctGroupRepo' defined in file [C:\svn_wa\STARS-CurrentSprint\src\Java\exception-manager\bin\stars\em\repo\AcctGroupRepo.class]: Initialization of bean failed; nested exception is java.lang.IllegalStateException: Failed to introspect annotations on class stars.em.repo.AcctGroupRepo
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:778)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.test.SpringApplicationContextLoader.loadContext(SpringApplicationContextLoader.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	... 25 more
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: java.util.Map stars.em.batch.ExceptionFactory.exceptionServices; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ACCOUNT_GROUP_VALIDATION' defined in file [C:\svn_wa\STARS-CurrentSprint\src\Java\exception-manager\bin\stars\em\service\AccountGroupValidationServiceImpl.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [stars.em.repo.AcctGroupRepo]: Error creating bean with name 'acctGroupRepo' defined in file [C:\svn_wa\STARS-CurrentSprint\src\Java\exception-manager\bin\stars\em\repo\AcctGroupRepo.class]: Initialization of bean failed; nested exception is java.lang.IllegalStateException: Failed to introspect annotations on class stars.em.repo.AcctGroupRepo; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'acctGroupRepo' defined in file [C:\svn_wa\STARS-CurrentSprint\src\Java\exception-manager\bin\stars\em\repo\AcctGroupRepo.class]: Initialization of bean failed; nested exception is java.lang.IllegalStateException: Failed to introspect annotations on class stars.em.repo.AcctGroupRepo
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 41 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ACCOUNT_GROUP_VALIDATION' defined in file [C:\svn_wa\STARS-CurrentSprint\src\Java\exception-manager\bin\stars\em\service\AccountGroupValidationServiceImpl.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [stars.em.repo.AcctGroupRepo]: Error creating bean with name 'acctGroupRepo' defined in file [C:\svn_wa\STARS-CurrentSprint\src\Java\exception-manager\bin\stars\em\repo\AcctGroupRepo.class]: Initialization of bean failed; nested exception is java.lang.IllegalStateException: Failed to introspect annotations on class stars.em.repo.AcctGroupRepo; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'acctGroupRepo' defined in file [C:\svn_wa\STARS-CurrentSprint\src\Java\exception-manager\bin\stars\em\repo\AcctGroupRepo.class]: Initialization of bean failed; nested exception is java.lang.IllegalStateException: Failed to introspect annotations on class stars.em.repo.AcctGroupRepo
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1147)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1110)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1021)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
	... 43 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'acctGroupRepo' defined in file [C:\svn_wa\STARS-CurrentSprint\src\Java\exception-manager\bin\stars\em\repo\AcctGroupRepo.class]: Initialization of bean failed; nested exception is java.lang.IllegalStateException: Failed to introspect annotations on class stars.em.repo.AcctGroupRepo
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1123)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1021)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:814)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 54 more
Caused by: java.lang.IllegalStateException: Failed to introspect annotations on class stars.em.repo.AcctGroupRepo
	at org.springframework.core.annotation.AnnotatedElementUtils.searchWithGetSemantics(AnnotatedElementUtils.java:605)
	at org.springframework.core.annotation.AnnotatedElementUtils.getMergedAnnotationAttributes(AnnotatedElementUtils.java:323)
	at org.springframework.transaction.annotation.SpringTransactionAnnotationParser.parseTransactionAnnotation(SpringTransactionAnnotationParser.java:42)
	at org.springframework.transaction.annotation.AnnotationTransactionAttributeSource.determineTransactionAttribute(AnnotationTransactionAttributeSource.java:155)
	at org.springframework.transaction.annotation.AnnotationTransactionAttributeSource.findTransactionAttribute(AnnotationTransactionAttributeSource.java:138)
	at org.springframework.transaction.interceptor.AbstractFallbackTransactionAttributeSource.computeTransactionAttribute(AbstractFallbackTransactionAttributeSource.java:157)
	at org.springframework.transaction.interceptor.AbstractFallbackTransactionAttributeSource.getTransactionAttribute(AbstractFallbackTransactionAttributeSource.java:100)
	at org.springframework.transaction.interceptor.TransactionAttributeSourcePointcut.matches(TransactionAttributeSourcePointcut.java:41)
	at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:211)
	at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:248)
	at org.springframework.aop.support.AopUtils.findAdvisorsThatCanApply(AopUtils.java:280)
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findAdvisorsThatCanApply(AbstractAdvisorAutoProxyCreator.java:118)
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findEligibleAdvisors(AbstractAdvisorAutoProxyCreator.java:88)
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.getAdvicesAndAdvisorsForBean(AbstractAdvisorAutoProxyCreator.java:69)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:346)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:298)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1587)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	... 64 more
Caused by: java.lang.annotation.AnnotationFormatError: Malformed method on an annotation type
	at sun.reflect.annotation.AnnotationInvocationHandler.validateAnnotationMethods(AnnotationInvocationHandler.java:384)
	at sun.reflect.annotation.AnnotationInvocationHandler.access$100(AnnotationInvocationHandler.java:42)
	at sun.reflect.annotation.AnnotationInvocationHandler$1.run(AnnotationInvocationHandler.java:289)
	at sun.reflect.annotation.AnnotationInvocationHandler$1.run(AnnotationInvocationHandler.java:286)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.annotation.AnnotationInvocationHandler.getMemberMethods(AnnotationInvocationHandler.java:285)
	at sun.reflect.annotation.AnnotationInvocationHandler.equalsImpl(AnnotationInvocationHandler.java:197)
	at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:64)
	at com.sun.proxy.$Proxy81.equals(Unknown Source)
	at java.util.Arrays$ArrayList.indexOf(Arrays.java:3860)
	at java.util.Arrays$ArrayList.contains(Arrays.java:3868)
	at org.springframework.core.annotation.AnnotatedElementUtils.searchWithGetSemantics(AnnotatedElementUtils.java:643)
	at org.springframework.core.annotation.AnnotatedElementUtils.searchWithGetSemantics(AnnotatedElementUtils.java:600)
	... 82 more
```

### Steps to reproduce
Running the test case with no JaCoco plugin (or running test in Eclipse without Coverage) - Test passes.
Running the same test case with JaCoCo plugin (or running in Eclipse with Coverage) - See trace above.

```
package stars.em.util;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.context.web.WebAppConfiguration;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import stars.em.ApplicationTestConfig;

@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = {ApplicationTestConfig.class})
@WebAppConfiguration
public class DataDumperTest {
	@Autowired 
	DataDumper dumper;
	
	List<TestObject> objs = new ArrayList<>();
	
	@Before
    public void setUp() {
    	objs.add(new TestObject("AA", new BigDecimal("1000")));
    	objs.add(new TestObject("BB", new BigDecimal("2000.00001")));
    }
	
	@Test
	public void testGetAccountBenchmarkFromWS() {
		List<String> names = new ArrayList<>();
		names.add("name");
		names.add("amount");
		dumper.dumpObject(objs, names , "tmp.csv");
	}
}

@Getter
@Setter
@AllArgsConstructor
class TestObject {
	private String name;
	private BigDecimal amount;
}
```

JaCoCo version:   
Eclipse Plugin - EclEmma Java Code Coverage	2.3.3.201602231923	
Also Gradle plugin 'jacoco'

Operating system: Windows 7 Professional
Tool integration: Gradle 3.1, Eclipse Neon.1

### Expected behaviour
No exception

### Actual behaviour
Exception is thrown

**Comment by Godin** [comment]
@charlesxucheng thank you for your report. However steps provided by you to reproduce can not be used as is, since require some additional code around and declaration of dependencies, and so do no guarantee reproduction of the same behavior. Hence question: will it be possible to provide an example of project (e.g. on GitHub) that is easy to execution without additional setup. This will greatly speed up investigations.

**Comment by Godin** [comment]
Okay, here is reproducer
```java
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.reflect.Method;

class AnnotationBug {
  @Retention(RetentionPolicy.RUNTIME)
  @interface Annotation {
    // provoke creation of <clinit>
    Object clinit = new Object();

    int method() default 0;
  }

  @Annotation
  public static void main(String[] args) throws Exception {
    Method method = AnnotationBug.class.getMethod("main", String[].class);
    Annotation annotation = method.getAnnotation(Annotation.class);
    // provoke verification in AnnotationInvocationHandler
    annotation.equals(annotation);
  }
}
```

that causes
```
java.lang.annotation.AnnotationFormatError: Malformed method on an annotation type
```

with JaCoCo 0.7.7
```
$ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

$ javac -source 8 -target 8 AnnotationBug.java

$ java -javaagent:jacocoagent-0.7.7.jar AnnotationBug
```

This already has been fixed in 0.7.8 by #441.
@charlesxucheng  you can use snapshot version to confirm this.
And as a temporary workaround you can find affected annotation and exclude it from instrumentation.

**Comment by charlesxucheng** [comment]
Thank you so much @Godin. We are using Gradle JaCoco plugin for our CI setup. I just tried and it seems that there is no way to specify a particular Snapshot version's POM for that plugin. 

With regard to the workaround suggested, I searched our own annotations and don't find any that matches the criteria, so it could be annotations from libraries we use. 

Can I check if there is any plan for 0.7.8 release? Thanks.

**Comment by Godin** [comment]
> I just tried and it seems that there is no way to specify a particular Snapshot version's POM for that plugin.

```
repositories {
   maven {
     url "https://oss.sonatype.org/content/repositories/snapshots"
   }
}

jacoco {
  toolVersion = "0.7.8-SNAPSHOT"
}
```
supposed to work.

> With regard to the workaround suggested, I searched our own annotations and don't find any that matches the criteria, so it could be annotations from libraries we use.

You can include into instrumentation only classes of your packages - this is essentially equivalent to exclusion of third-party libraries.

> Can I check if there is any plan for 0.7.8 release? 

So far date was not chosen and some other works were planned, however we were not expecting that #441 has functional impacts. Anyway will be good to confirm before talking about release.

**Comment by Godin** [comment]
@marchof and by testing weird corner cases we catch one more JDK bug here :laughing: 

```
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.reflect.Method;

class AnnotationBug {
  @Retention(RetentionPolicy.RUNTIME)
  @interface Annotation {
    // provoke creation of method
    Runnable r = () -> {};
  }

  @Annotation
  public static void m1() {
  }

  @Annotation
  public static void m2() {
  }

  @Annotation
  public static void main(String[] args) throws Exception {
    Annotation a1 = AnnotationBug.class.getMethod("m1").getAnnotation(Annotation.class);
    Annotation a2 = AnnotationBug.class.getMethod("m2").getAnnotation(Annotation.class);
    // provoke verification in AnnotationInvocationHandler
    a1.equals(a2);
  }
}
```

even without JaCoCo
on **JDK 8u31**, **JDK 8u112** and **JDK 9 EA b144** will cause
```
java.lang.annotation.AnnotationFormatError: Malformed method on an annotation type
```

on **JDK 8u11** will cause
```
Exception in thread "main" java.lang.NullPointerException
        at sun.reflect.annotation.AnnotationInvocationHandler.memberValueEquals(AnnotationInvocationHandler.java:233)
```

Submitted JI-9045359.

**Comment by charlesxucheng** [comment]
Thanks @Godin. Tried that and it worked. 

```
repositories {
   maven {
     url "https://oss.sonatype.org/content/repositories/snapshots"
   }
}

jacoco {
  toolVersion = "0.7.8-SNAPSHOT"
}
```

**Comment by Godin** [comment]
At least spring-boot has such annotation - [EnableAutoConfiguration](https://github.com/spring-projects/spring-boot/blob/v1.4.2.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/EnableAutoConfiguration.java#L78)

**Comment by Godin** [comment]
Thus for the completeness of picture: I'm pretty sure that exclusion `org.springframework.**` can be used as a temporary workaround in EclEmma, Gradle, Maven, etc.

**Comment by andrioli** [comment]
@Godin This I guess it compiled as `public static final String` (i.e., in encoded in the constant pool). There is no initializer in this case.

**Comment by Godin** [comment]
@andrioli ouch, you are right. It is quite hard to find which exact annotation causes problem without having a reproducer in hands, so I stop searching. And anyway it seems possible to workaround this by usage of inclusions/exclusions.

**Comment by Godin** [comment]
We will definitely work towards release of JaCoCo. However integration of fix into EclEmma is a bit complicated by the fact that currently EclEmma is in transition to Eclipse Foundation and we were not expecting its release that soon.
