### ISSUE TITLE
Problem with ASM packages Java 1.8

### ISSUE THREAD

**Issue by Kowah** [jacoco/jacoco#461]
Hey guys I just discovered JaCoCo and I tried for 2 hours to execute the first example : CoreTutorial.java and i met problems with ASM.

### Environment
Java 1.8 JDK (java-8-oracle)
IntelliJ idea 2016.2.5
Ubuntu 16.04 LTS

### Here is the StackTrace when I try to execute CoreTutorial

Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
	at CoreTutorial.execute(CoreTutorial.java:112)
	at CoreTutorial.main(CoreTutorial.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

Process finished with exit code 1

### Here is my pom.xml

```
<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>fr.istic.jtm</groupId>
    <artifactId>jtm</artifactId>
    <name>JavaTestMonitoring</name>
    <version>0.1</version>
    <dependencies>
        <!-- https://mvnrepository.com/artifact/org.ow2.asm/asm -->
        <dependency>
            <groupId>org.ow2.asm</groupId>
            <artifactId>asm</artifactId>
            <version>5.1</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.11</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.jacoco/jacoco-maven-plugin -->
        <dependency>
            <groupId>org.jacoco</groupId>
            <artifactId>jacoco</artifactId>
            <version>0.7.7.201606060606</version>
        </dependency>
    </dependencies>
</project>
```

I probably did mistakes in English so please excuse me in advance :/
I'm waiting for your opinion, maybe I forgot something but I'm too much 'inside' it to see what I did wrong.

Thanks in advance !

**Comment by Kowah** [comment]
Ok nevermind, create a module inside another with IntelliJ ask to be very precise with the pom.xml location.

In my case I have a module inside another, and provide a pom.xml only on my first module wasn't enough.

Sorry for that :p
