### ISSUE TITLE
NegativeArraySizeException

### ISSUE THREAD

**Issue by Godin** [jacoco/jacoco#487]
```
java.io.IOException: Error while instrumenting class Example.
Caused by: java.lang.NegativeArraySizeException
	at org.objectweb.asm.Frame.merge(Frame.java:1447)
	at org.objectweb.asm.CurrentFrame.execute(CurrentFrame.java:52)
	at org.objectweb.asm.MethodWriter.visitInsn(MethodWriter.java:747)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1367)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1032)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:708)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:521)
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:1003)
	at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:91)
```

This happens when resizing jump instruction during instrumentation in a class without frames.

Corresponding ASM issue: https://gitlab.ow2.org/asm/asm/issues/317784

**Comment by Godin** [comment]
Fixed by #600
