### ISSUE TITLE
Provide better error message than StackOverflowError in case when two JaCoCo agents of different versions are used

### ISSUE THREAD

**Issue by Godin** [jacoco/jacoco#532]
From time to time we receive questions about `StackOverflowError` which happens when two JaCoCo agents of different versions are used, for example https://groups.google.com/d/msg/jacoco/A1BZvk9A0Fc/pU5EGHyjAAAJ and https://github.com/jacoco/jacoco/issues/507

We even added this question to FAQ in https://github.com/jacoco/jacoco/pull/528

This is easily reproducible as
```
java -XX:MaxJavaStackTraceDepth=-1 \
    -javaagent:jacoco-0.7.8/lib/jacocoagent.jar \
    -javaagent:jacoco-0.7.9/lib/jacocoagent.jar
```

and here is what IMO happens in such situation:

1. first agent starts and adds field `$jacocoAccess` to `java/util/UUID`
2. second agent starts and also tries to add this field by doing
   ```
   instrumentation.addTransformer(transformer);
   Class.forName("java.util.UUID");
   instrumentation.removeTransformer(transformer)
   ```
   but transformer is not applied since class is already defined 

3. second agent sees field that was added by first agent and changes its value to its own
4. second agent triggers initialization of `ExecutionData` that is instrumented by a first agent, but due to a value of field, it starts to communicate with itself leading to `StackOverflowError` - see bottom of stack trace:
   ```
   Exception in thread "main" java.lang.reflect.InvocationTargetException
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
     at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
   Caused by: java.lang.StackOverflowError
     ...
     at org.jacoco.agent.rt.internal_8ff85ea.core.data.ExecutionData.<init>(ExecutionData.java)
     at org.jacoco.agent.rt.internal_8ff85ea.core.data.ExecutionDataStore.get(ExecutionDataStore.java:133)
     at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.RuntimeData.getExecutionData(RuntimeData.java:120)
     at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.RuntimeData.getProbes(RuntimeData.java:148)
     at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.RuntimeData.equals(RuntimeData.java:162)
     at org.jacoco.agent.rt.internal_8ff85ea.core.data.ExecutionData.$jacocoInit(ExecutionData.java)
     at org.jacoco.agent.rt.internal_8ff85ea.core.data.ExecutionData.<init>(ExecutionData.java)
     at org.jacoco.agent.rt.internal_8ff85ea.core.data.ExecutionDataStore.get(ExecutionDataStore.java:133)
     at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.RuntimeData.getExecutionData(RuntimeData.java:120)
     at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.RuntimeData.getProbes(RuntimeData.java:148)
     at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.RuntimeData.equals(RuntimeData.java:162)
     at org.jacoco.agent.rt.internal_8ff85ea.CoverageTransformer.$jacocoInit(CoverageTransformer.java)
     at org.jacoco.agent.rt.internal_8ff85ea.CoverageTransformer.<clinit>(CoverageTransformer.java)
     at org.jacoco.agent.rt.internal_8ff85ea.PreMain.premain(PreMain.java:49)
   ```

While we can't do anything for already released versions, I believe that in a new version of JaCoCo by checking that transformation is really happened or maybe by simply checking that field had `null` value prior to setting new value, we can detect such conflict with agents down to version 0.5.0 (5ff6b2dc7a8a82132fbe3a65e4c86a60a0be8693) and provide better error message than just `StackOverflowError`.

Also starting from version 0.6.2 we have `org.jacoco.agent.rt.RT` that can be used to detect whether agent is already started or not.

As a note: this is not just about `StackOverflowError` - usage of two JaCoCo agents at the same time is a bad idea in general.

**Comment by mkclemens** [comment]
We ran into this issue because we had a build tool where JaCoCo coverage could be selected as an option on the build configuration but we switched to running JaCoCo directly from the Maven build but forgot to remove the JaCoCo option in the build tool. There was no intention to run two JaCoCo agents at all, it was purely an oversight that the configuration in the build tool wasn't updated, but a better error message would probably have made this easier to understand.
