### ISSUE TITLE
Improve Android Studio support

### ISSUE THREAD

**Issue by includecmath** [jacoco/jacoco#562]
JaCoCo version: 0.7.9
Operating system: Android
Tool integration: Gradle

I use jacoco to create code coverage report under manual testing. In Android Studio if I apply plugin: 'jacoco', and turn on testCoverageEnabled true. It can not find dependencies. Throw 
```
java.lang.ClassNotFoundException: org.jacoco.agent.rt.RT  
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jacoco.agent.rt.RT" on path:
Suppressed: java.lang.ClassNotFoundException: org.jacoco.agent.rt.RT
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available 
```
But I add the jacoco as libs,It throw another. 
```
java.lang.reflect.InvocationTargetException at java.lang.reflect.Method.invoke(Native Method)
Caused by: java.lang.IllegalStateException: JaCoCo agent not started.
at org.jacoco.agent.rt.internal_8ff85ea.Agent.getInstance(Agent.java:72)
at org.jacoco.agent.rt.RT.getAgent(RT.java:32)
```
/(ㄒoㄒ)/ code here:
``` java
        File coverageFile = new File(coverageFileSavePath);
        OutputStream output = null;
        try {
            coverageFile.createNewFile();
            output = new FileOutputStream(coverageFileSavePath, true);

            Class<?> jacocoRTClass = Class.forName("org.jacoco.agent.rt.RT");
            Method instanceMethod = jacocoRTClass.getMethod("getAgent");
            Object jacocoAgent = instanceMethod.invoke(null);

            Method executionDataMethod = jacocoAgent.getClass().getMethod("getExecutionData", boolean.class);
            byte[] executeData = (byte[]) executionDataMethod.invoke(jacocoAgent, false);
            output.write(executeData);
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
```
Use Android Studio default gradle task(createDebugAndroidTestCoverageReport) and report for test or androidTest it's success.

**Comment by Godin** [comment]
@includecmath Integration into Android studio as well as Gradle plugin are not developed by us. As stated on page http://www.jacoco.org/jacoco/trunk/doc/integrations.html - we provide only core library, Ant Tasks, Maven plugin. So please contact developers of the integration that you try to use. Thank you for your understanding.
