### ISSUE TITLE
org.jacoco.cli can not be run

### ISSUE THREAD

**Issue by yjqg6666** [jacoco/jacoco#566]
### Steps to reproduce

JaCoCo version: 0.7.10-20170710.141307-8  (0.7.10-SNAPSHOT)
Operating system:  mac os 10.12.5
Tool integration: Other Cli zsh

### Expected behaviour
$ java -jar /src/org.jacoco.cli-0.7.10-20170710.141307-8.jar instrument . --dest .
got running

### Actual behaviour
got error:  no main manifest attribute, in /tmp/org.jacoco.cli-0.7.10-20170710.141307-8.jar
what's the mainClass for the jar? It should be set in the manifest file.

**Comment by yjqg6666** [comment]
jar file downloaded from https://oss.sonatype.org/content/repositories/snapshots/org/jacoco/org.jacoco.cli/0.7.10-SNAPSHOT/org.jacoco.cli-0.7.10-20170710.141307-8.jar

**Comment by yjqg6666** [comment]
I extracted the jar file and found the main class org.jacoco.cli.internal.Main.
tried
* $ java -jar org.jacoco.cli-0.7.10-20170710.141307-8.jar org.jacoco.cli.internal.Main
no main manifest attribute, in org.jacoco.cli-0.7.10-20170710.141307-8.jar
* $ java -cp org.jacoco.cli-0.7.10-20170710.141307-8.jar org.jacoco.cli.internal.Main
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/kohsuke/args4j/CmdLineException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.kohsuke.args4j.CmdLineException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

the dependencies are not included in the jar file.

**Comment by Godin** [comment]
If you'll read http://www.jacoco.org/jacoco/trunk/doc/repo.html , you'll notice that JAR with included dependencies has classifier `nodeps` and hence you use wrong URL. Correct will be https://oss.sonatype.org/content/repositories/snapshots/org/jacoco/org.jacoco.cli/0.7.10-SNAPSHOT/org.jacoco.cli-0.7.10-20170710.141307-8-nodeps.jar And this is exactly the JAR that has `Main-Class` attribute and that is included into JaCoCo ZIP distribution as `jacococli.jar` "JaCoCo Command Line Interface".
