### ISSUE TITLE
android.os.NetworkOnMainThreadException when call TcpClientOutput.createSocket

### ISSUE THREAD

**Issue by vigossjjj** [jacoco/jacoco#571]
Dump the coverage data via TCPClient on Android, Beacuse the StrictMode can not allow createSocket on Main/UI Thread , 
After review the jacoco source code - `TcpClientOutput.java`, see that Socket create on Main Thread, This way is not friendly for android, should do that at new thead. Do you have any workaround?

https://github.com/jacoco/jacoco/blob/fcf9baf81c8223425619c7984b2d74bfb8e8f235/org.jacoco.agent.rt/src/org/jacoco/agent/rt/internal/output/TcpClientOutput.java#L47-L49

jacoco-agent.properties
```java
output=tcpclient
address=192.168.1.103
port=9589
````
ErrorTrace:
```java
W/System.err: android.os.NetworkOnMainThreadException
     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
     at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:110)
     at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
     at libcore.io.IoBridge.connect(IoBridge.java:122)
     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:163)
     at java.net.Socket.startupSocket(Socket.java:592)
     at java.net.Socket.tryAllAddresses(Socket.java:128)
     at java.net.Socket.<init>(Socket.java:178)
     at java.net.Socket.<init>(Socket.java:150)
     at org.jacoco.agent.rt.internal_14f7ee5.output.TcpClientOutput.createSocket(TcpClientOutput.java:85)
     at org.jacoco.agent.rt.internal_14f7ee5.output.TcpClientOutput.startup(TcpClientOutput.java:49)
     at org.jacoco.agent.rt.internal_14f7ee5.Agent.startup(Agent.java:122)
     at org.jacoco.agent.rt.internal_14f7ee5.Agent.getInstance(Agent.java:50)
     at org.jacoco.agent.rt.internal_14f7ee5.Offline.<clinit>(Offline.java:31)
     at com.myapp.SetupBundle.$jacocoInit(SetupBundle.java)
     ...
```

**Comment by Godin** [comment]
> Do you have any workaround?

@vigossjjj use `file` output mode

**Comment by marchof** [comment]
We could easily move socket creation (also for server mode) in the worker thread which processes the actual network operation.

Not sure about the impact when socket is created asynchronously:
* Application starts independently from socket creation. This could produce non deterministic behavior, e.g. application terminates before socket is created.
* Any errors on socket creation will only be logged but will not prevent agent startup

Therefore I'm a bit reluctant to change startup behavior here.

**Comment by Godin** [comment]
@marchof I'm wondering if `android.os.StrictMode` can be tricked by `thread.join()` for synchronous startup? :wink:

@vigossjjj Also wondering which usage scenario requires `tcpclient` output? AFAIK the way in which Android SDK integrates JaCoCo doesn't require this. And given that Android SDK integrates JaCoCo for code coverage on their own, might be better to talk about such scenario with developers of Android SDK rather than implement tricks here. Also as another workaround in addition to simple usage of `file` output mode, I suppose that strict mode can be disabled.

**Comment by marchof** [comment]
@Godin From Andoid docs one can guess that this might not be detected. Anyways, I don't want to add complexity here.
