### ISSUE TITLE
Copying user.dir system property during test fails Jacoco

### ISSUE THREAD

**Issue by asarkar** [jacoco/jacoco#574]
Given a Gradle multimodule project:
a
...b

if we do the following:
```
tasks.withType(Test) {
    systemProperties = System.properties.findAll{ k, v -> k.startsWith("user.dir")}
}
```
and launch the build from project `a` `./gradlew clean test`, the build fails with the following exception.
```
Exception in thread "main" java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_8ff85ea.PreMain
                at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
                at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
                at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:304)
                at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
FATAL ERROR in native method: processing of -javaagent failed
```

It appears that the class is present under `b/build/tmp`, but why is Jacoco relying on `user.dir` to find it?

### Steps to reproduce

JaCoCo version: 0.7.9
Operating system: CentOS 7.2.1511.
Tool integration: Gradle

### Expected behaviour
The build works without dependency on `user.dir`.

### Actual behaviour
Build fails as shown above.

**Comment by marchof** [comment]
@asarkar The code snippet is from your grade build, right? The JaCoCo grade plugin is maintained by the grade project. Please report the issue with them. Thx!

**Comment by asarkar** [comment]
@marchof I understand that Gradle team maintains the plugin but are you sure that this is not an issue with core Jacoco?

**Comment by Godin** [comment]
@asarkar yes, we are sure. Moreover from our FAQ ( http://www.jacoco.org/jacoco/trunk/doc/faq.html ) about this exception:

> ### Why do I get a NoClassDefFoundError or ClassNotFoundException for class org.jacoco.agent[...]Offline?
> 
> If you use offline instrumentation the instrumented classes get a direct dependency on the JaCoCo runtime. Therefore jacocoagent.jar of the same JaCoCo version must be on the classpath and accessible from by the instrumented classes.
