### ISSUE TITLE
ArrayIndexOutOfBoundsException triggered by static methods on interfaces with Consumer<> argument in Java 8

### ISSUE THREAD

**Issue by spatula75** [jacoco/jacoco#614]
### Steps to reproduce

We discovered this when upgrading to Jersey 2.26 which in turn uses HK2 for dependency injection under the hood along with Java 8 lambdas.  They have a method on the interface `org.glassfish.jersey.internal.inject.ForeignDescriptor`:

`static ForeignDescriptor wrap(Object descriptor, Consumer<Object> disposeInstance)`

When this method is called by Jersey's internals, an `ArrayIndexOutOfBoundsException 1` is thrown from an unknown class (presumably something that was instrumented).  When Jacoco is excluded from the build, it is not thrown.

JaCoCo version: 0.7.9
Operating system: MacOS
Tool integration: Maven

### Expected behaviour

ArrayIndexOutOfBoundsException is not thrown when an outside library is executing a static method on an interface that takes a Java 8 `Consumer<Object>` as an argument.

### Actual behaviour

ArrayIndexOutOfBoundsException is thrown when Jacoco is enabled.

**Comment by marchof** [comment]
@spatula75 Can you please provide the full stack trace?

**Comment by spatula75** [comment]
Sure, here's an example.  Note that the stack frame where the exception actually gets thrown isn't included, apparently due to the instrumentation, and when stepping through with a debugger, the debugger just encounters an error in this frame.

```
javax.ws.rs.ProcessingException: A MultiException has 1 exceptions.  They are:
1. java.lang.ArrayIndexOutOfBoundsException: 1

        at org.glassfish.jersey.internal.inject.ForeignDescriptor.wrap(ForeignDescriptor.java:88)
        at org.glassfish.jersey.inject.hk2.RequestContext.findOrCreate(RequestContext.java:84)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:777)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:740)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:718)
        at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getInstance(AbstractHk2InjectionManager.java:174)
        at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getInstance(ImmediateHk2InjectionManager.java:54)
        at org.glassfish.jersey.client.ClientRuntime.lambda$new$0(ClientRuntime.java:115)
        at org.glassfish.jersey.client.RequestProcessingInitializationStage.apply(RequestProcessingInitializationStage.java:102)
        at org.glassfish.jersey.client.RequestProcessingInitializationStage.apply(RequestProcessingInitializationStage.java:66)
        at org.glassfish.jersey.process.internal.Stages$LinkedStage.apply(Stages.java:308)
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:357)
        at xx.xxx.xxx.xxxx.xxxx.FooTest.testFoo(FooTest.java:137)
```

**Comment by spatula75** [comment]
A viable workaround for us, since this is happening due to instrumentation of code that isn't ours, is just to add this to the `prepare-agent` configuration in the Maven plugin:

```
                        <configuration>
                        	<includes>
                        		<include>our.package.prefix.*</include>
                        	</includes>
                        </configuration>

```

**Comment by Godin** [comment]
> executing a static method on an interface that takes a Java 8 `Consumer<Object>` as an argument

I don't think that this analysis is correct - unsuccessfully tried to reproduce by doing exactly this and mimicking Jersey and HK2 based on provided stacktrace:
```
$ ls
jacocoagent-0.7.9.jar

$ cat <<END > Attempt.java
import java.util.function.Consumer;

class Attempt {

  interface ForeignDescriptor {
    static ForeignDescriptor wrap(Object descriptor, Consumer<Object> disposeInstance) {
      return new ForeignDescriptorImpl(descriptor, disposeInstance);
    }
  }

  static class ForeignDescriptorImpl implements ForeignDescriptor {
    ForeignDescriptorImpl(Object descriptor, Consumer<Object> disposeInstance) {
    }
  }

  interface ActiveDescriptor<T> {
    void dispose(T instance);
  }

  static <U> U findOrCreate(ActiveDescriptor<U> activeDescriptor) {
    ForeignDescriptor.wrap(activeDescriptor, obj -> activeDescriptor.dispose((U) obj));
    return (U) "OK";
  }

  public static void main(String[] args) {
    System.out.println(
      findOrCreate(new ActiveDescriptor<Object>() {
        public void dispose(Object instance) {
        }
      })
    );
  }

}
END

$ java -version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

$ javac Attempt.java
Note: Attempt.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

$ java -javaagent:jacocoagent-0.7.9.jar Attempt
OK

$ ls *.exec
jacoco.exec
```

@spatula75 can you please provide reproducer?

**Comment by spatula75** [comment]
It's entirely possible that it takes more to trigger the problem than simply having a static method on an interface.  We were triggering it by actually using the Jersey client inside an integration test that hits an embedded HTTP server.

**Comment by Godin** [comment]
> it takes more to trigger the problem

if takes time (?) to reproduce and not always reproducible (?), then the only idea that comes to my mind that this might be bug in JVM JIT. To check this please make sure that you use latest JVM and please try without JIT in interpreter mode using `-Xint`.

And in any case as it is more complex than originally described, to investigate we definitely need a reproducer.

**Comment by spatula75** [comment]
It's reproduceable 100% of the time from just a handful of method calls into Jersey-Client, but untangling a project that demonstrates the problem is a nontrivial undertaking; as you might imagine, it's wrapped up in our test code, which unfortunately is not open source so I cannot share it as-is.

**Comment by Godin** [comment]
Can imagine. But please take into account that our resources are also limited, to do blind attempts to reproduce/understand nontrivial cases, especially without any experience with Jersey-Client. Thank you for your understanding.

**Comment by spatula75** [comment]
I completely understand and entirely commiserate.  If I can find some time in the next few days, I'll see what I can do.

**Comment by Godin** [comment]
> If I can find some time in the next few days, I'll see what I can do.

@spatula75 thanks in advance. In the meantime could you please provide `jacoco.exec` of failed execution and exact JDK version? Also execution with `-Xint` IMO anyway a good idea just to be sure that this is not something JVM-related.

**Comment by Godin** [comment]
@spatula75 Without the requested information we cannot analyze this. Any chance to get it? will close ticket otherwise.
