### ISSUE TITLE
Unable to exclude encrypted jar getting ClassNotFoundException

### ISSUE THREAD

**Issue by smaurya52** [jacoco/jacoco#661]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce
             <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>com/companyname/*</exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <id>default-prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>default-report</id>
                        <phase>site</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

JaCoCo version:
Operating system:
Tool integration: Maven/Ant/API/Other

### Expected behaviour
Should not take encrypted jar for jacoco analysis.
### Actual behaviour
Giving ClassNotFoundException while try to analyze encrypted jar.

**Comment by marchof** [comment]
@smaurya52 The JaCoCo Maven plugin only works on **class files** in the the `target/classes` directory. Therefore it is unclear to me where an "encrypted JAR" comes into picture.

Can you please provide a full stack trace (`-X` parameter)?

**Comment by smaurya52** [comment]
Sorry for the less information. Here is the error log i am getting while executing the test cases for my project.

java.lang.RuntimeException: ClassNotFoundException(com.companyname.f)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
        at org.junit.contrib.java.lang.system.ExpectedSystemExit$1.evaluate(ExpectedSystemExit.java:130)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
Caused by: java.lang.ClassNotFoundException: Couldn't decrypt class
        at com.zenofx.classguard.bootstrap.ClassGuard.findClassInternal(ClassGuard.java:267)
        at com.zenofx.classguard.bootstrap.ClassGuard.findClass(ClassGuard.java:245)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at com.companyname.getClass(ClassGuardFactory.java:89)
        ... 38 more

**Comment by smaurya52** [comment]
Problem is I am using an encrypted jar library in my project. So whenever i will jacoco plugin from my project test cases are getting executed successfully. But whenever i am trying to add jacoco plugin to get the coverage report it's giving me ClassNotFound exception.

**Comment by Godin** [comment]
@smaurya52 in stack trace

```
java.lang.RuntimeException: ClassNotFoundException(com.companyname.f)
```

while in your configuration

```
<exclude>com/fico/fa/functions/*</exclude>
```

thus why it is not

```
<exclude>com/mycompanyname/*</exclude>
```

?

To make sure that exclusions work in general you can even try

```
<exclude>*</exclude>
```

**Comment by smaurya52** [comment]
@Godin Sorry for the logs.This <exclude>com/mycompanyname/*</exclude> is just copied from different logs.
For a single execution it was same. Also I have tried this <exclude>*<exclude>. Still it is failing in the execution with same ClassNotFoundException.

**Comment by Godin** [comment]
@smaurya52 in presence of inconsistent statements from you hard to believe that you correctly tried `<exclude>*<exclude>` - exclusions are perfectly working and this pattern excludes all classes, i.e. disables instrumentation of all classes.

In absence of complete reproducer, the only wild guess can be that ClassGuard doesn't work at all in presence of any Java agent. And since ClassGuard is a commercial product, please contact its support.

> Also when jacoco agent does instrumentation and execution will it also try to include imported jar libraries in the coverage report ?

JaCoCo Java Agent doesn't perform execution of classes, it only instruments them. And it instruments all classes loaded by JVM that satisfy inclusion and exclusion patterns. Documentation is located at http://www.jacoco.org/jacoco/trunk/doc/agent.html

**Comment by smaurya52** [comment]
@Godin Thank you. This following information helped me.
> In absence of complete reproducer, the only wild guess can be that ClassGuard doesn't work at all in presence of any Java agent. And since ClassGuard is a commercial product, please contact its support.

Now i got that problem is with the ClassGurad as it is not working with java agents.
Thanks again for helping me out.
