### ISSUE TITLE
Java 8 Interface with default Methods not working with Jacoco Enabled

### ISSUE THREAD

**Issue by dineshba** [jacoco/jacoco#690]
We are having an interface with default methods and we implemented that interface in both `Java` and `Kotlin` classes and we provided the implementation for the non default methods.

When we run in debug mode (which doesn't have `testCoverageEnabled = true`) and the app works as expected. But when we run in different config with `testCoverageEnabled = true`, the app is crashing with below error

````
java.lang.NoSuchMethodError: No static method $$triggerInterfaceInit()V in class Lcom/ui/viewholders/CAViewContract$$CC; or its super classes (declaration of 'ui.viewholders.CAViewContract$$CC' appears in /data/app/SMCXbiLYvHb1Kk08Kee__g==/base.apk)
        at home.c.CCFragment.<clinit>(Unknown Source:0)
        at home.HomePageCardProvider.getFragment(HomePageCardProvider.java:17)
        at home.HomeFragment.handleCardFragment(HomeFragment.java:172)
````
JaCoCo version: "0.8.0"
Operating system: Android with minSdk 21

**Comment by marchof** [comment]
@dineshba Indeed JaCoCo adds extra code to interfaces which requires static initialization. But the method `triggerInterfaceInit()V` is not created by JaCoCo. We could try to have a look at, but probably you better report this to the Android project (they also do the JaCoCo integration for their SDK).

In any case a executable reproducer is required for analysis. Please provide e.g. a Github Repo and instructions how to reproduce the issue.
