### ISSUE TITLE
NullPointerException while generating report 

### ISSUE THREAD

**Issue by marianosimone** [jacoco/jacoco#748]
I'm getting random `NullPointerException`s while generating the coverage report for my mixed Java + Kotlin Android project.

I tried getting a reproducible case, but it randomly fails in different classes, and I haven't been able to pin-point a common denominator for all of them. Here's an example stacktrace:

	* Exception is:
	org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':mymodule:unitTestReport'.
		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
		at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
		at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:103)
		at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
		at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
		at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:66)
		at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
		at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
		at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
		at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
		at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
		at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
		at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
		at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
		at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
		at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
		at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
		at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
		at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
		at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
		at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
		at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
		at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
		at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
		at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
		at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
		at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
		at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
		at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
		at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
		at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
		at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	Caused by: : Error while creating report
		at org.jacoco.ant.ReportTask.execute(ReportTask.java:501)
		at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
		at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
		at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:78)
		at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:479)
		at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
		at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:160)
		at org.gradle.api.internal.project.antbuilder.AntBuilderDelegate.nodeCompleted(AntBuilderDelegate.java:118)
		at org.gradle.internal.jacoco.AbstractAntJacocoReport.invokeJacocoReport(AbstractAntJacocoReport.java:56)
		at org.gradle.internal.jacoco.AntJacocoReport$1.execute(AntJacocoReport.java:38)
		at org.gradle.internal.jacoco.AntJacocoReport$1.execute(AntJacocoReport.java:35)
		at org.gradle.internal.jacoco.AbstractAntJacocoReport$1.doCall(AbstractAntJacocoReport.java:46)
		at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
		at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:53)
		at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder$2.execute(DefaultIsolatedAntBuilder.java:152)
		at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder$2.execute(DefaultIsolatedAntBuilder.java:134)
		at org.gradle.api.internal.project.antbuilder.ClassPathToClassLoaderCache.withCachedClassLoader(ClassPathToClassLoaderCache.java:134)
		at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder.execute(DefaultIsolatedAntBuilder.java:128)
		at org.gradle.internal.jacoco.AbstractAntJacocoReport.configureAntReportTask(AbstractAntJacocoReport.java:38)
		at org.gradle.internal.jacoco.AntJacocoReport.execute(AntJacocoReport.java:35)
		at org.gradle.testing.jacoco.tasks.JacocoReport.generate(JacocoReport.java:78)
		at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
		at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
		at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
		at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
		at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
		at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
		at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
		at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
		at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
		at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
		... 32 more
	Caused by: java.io.IOException: Error while analyzing MyClass.class.
		at org.jacoco.core.analysis.Analyzer.analyzerError(Analyzer.java:170)
		at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:142)
		at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:165)
		at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:201)
		at org.jacoco.ant.ReportTask.createBundle(ReportTask.java:570)
		at org.jacoco.ant.ReportTask.createReport(ReportTask.java:542)
		at org.jacoco.ant.ReportTask.execute(ReportTask.java:495)
		... 65 more
	Caused by: java.lang.NullPointerException
		at org.jacoco.core.internal.analysis.filter.AbstractMatcher.skipNonOpcodes(AbstractMatcher.java:158)
		at org.jacoco.core.internal.analysis.filter.AbstractMatcher.next(AbstractMatcher.java:154)
		at org.jacoco.core.internal.analysis.filter.AbstractMatcher.nextIs(AbstractMatcher.java:137)
		at org.jacoco.core.internal.analysis.filter.AbstractMatcher.nextIsNew(AbstractMatcher.java:49)
		at org.jacoco.core.internal.analysis.filter.KotlinWhenFilter$Matcher.match(KotlinWhenFilter.java:54)
		at org.jacoco.core.internal.analysis.filter.KotlinWhenFilter.filter(KotlinWhenFilter.java:43)
		at org.jacoco.core.internal.analysis.filter.Filters.filter(Filters.java:48)
		at org.jacoco.core.internal.analysis.MethodAnalyzer.accept(MethodAnalyzer.java:117)
		at org.jacoco.core.internal.flow.ClassProbesAdapter$2.visitEnd(ClassProbesAdapter.java:89)
		at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1279)
		at org.objectweb.asm.ClassReader.accept(ClassReader.java:679)
		at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
		at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:124)
		at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:140)
		... 70 more

Rolling back to `0.8.1` makes everything work again w/o issues, and IIRC, the snapshots were working OK until [this commit](https://github.com/jacoco/jacoco/commit/82087743dfec23b585e31b8c8c1f9adff5b8288f) was merged.

JaCoCo version: 0.8.2-SNAPSHOT
Operating system: Linux + MacOS
Tool integration: Gradle

**Comment by marchof** [comment]
@marianosimone Thanks for reporting this! Any chance that you provide `MyClass.class` when the build fails?

**Comment by marchof** [comment]
@marianosimone No need to send class file. We identified the problem.

**Comment by Godin** [comment]
@marchof @marianosimone at the same time as I was cooking #749 😆 👍

**Comment by marianosimone** [comment]
Great! Glad to see it being addressed.

I was planning on uploading a couple of class files, but given that the error was so random, I assumed it had more to do with multithreading than the actual code under analysis.

**Comment by Godin** [comment]
@marianosimone even if we quite confident that #749 should fix the problem, could you please try new snapshot that was just deployed?

**Comment by marianosimone** [comment]
So far so good... I'll keep an eye on my CI runs and get back to this ticket if I see it popping up again

Thanks for the quick fix!

**Comment by Godin** [comment]
@marianosimone You're welcome and thank you for testing! FIY #749 was discovered as part of final review before release which we plan to do shortly :wink:
