### ISSUE TITLE
IllegalAccessError with swapInit and clinit in jacoco 0.8.2

### ISSUE THREAD

**Issue by henrik242** [jacoco/jacoco#757]
We get this Error seemingly random places in our Spock tests after upgrading to 0.8.2:
```
    Caused by: java.lang.IllegalAccessError: Update to static final field me.SomeTest.$const$0 attempted from a different method (__$swapInit) than the initializer method <clinit>
        at me.SomeTest.__$swapInit(SomeTest.groovy)
        at me.SomeTest.<clinit>(SomeTest.groovy)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
        at java.base/java.lang.Class.newInstance(Class.java:560)
        at org.spockframework.runtime.BaseSpecRunner.createSpecInstance(BaseSpecRunner.java:104)
```

**Comment by Godin** [comment]
AFAIK field `__$swapInit` is generated by Groovy compiler. And for sure JaCoCo does not update this field. So stack trace and message seem completely unrelated to JaCoCo - see also https://github.com/spockframework/spock/pull/900#issuecomment-420158524

And I have a very strong feeling that at the same time you also changed version of JDK to one that not supported by your version of Spok or Groovy.
