### ISSUE TITLE
Jacoco agent fails when run under Turkish locale

### ISSUE THREAD

**Issue by trejkaz** [jacoco/jacoco#800]
### Steps to reproduce

Run tests with jacoco, and with the following system properties set:

    -Duser.language=tr -Duser.country=TR

JaCoCo version: 0.8.1
Operating system: macOS 10.13
Tool integration: Java 1.8.0_172, Gradle 5.0

### Expected behaviour

I expected the tests to fail, but due to the specific tests themselves, but was hoping that they might just pass.

### Actual behaviour

Jacoco fails instead:

    Exception in thread "main" java.lang.reflect.InvocationTargetException
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
    	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
    Caused by: java.lang.IllegalArgumentException: No enum constant org.jacoco.agent.rt.internal_c13123e.core.runtime.AgentOptions.OutputMode.fıle
    	at java.lang.Enum.valueOf(Enum.java:238)
    	at org.jacoco.agent.rt.internal_c13123e.core.runtime.AgentOptions$OutputMode.valueOf(AgentOptions.java:123)
    	at org.jacoco.agent.rt.internal_c13123e.core.runtime.AgentOptions.getOutput(AgentOptions.java:497)
    	at org.jacoco.agent.rt.internal_c13123e.core.runtime.AgentOptions.validateAll(AgentOptions.java:252)
    	at org.jacoco.agent.rt.internal_c13123e.core.runtime.AgentOptions.<init>(AgentOptions.java:230)
    	at org.jacoco.agent.rt.internal_c13123e.PreMain.premain(PreMain.java:43)
    FATAL ERROR in native method: processing of -javaagent failed
    	... 6 more

### Investigation so far

I have noticed that JaCoCo's source repository does contain calls to `toLowerCase()` without passing a locale, but haven't been able to track down how the value got into this specific stack trace. Gradle itself is still running in English, though, so it would be even more odd if the problem were occurring on their side.

I don't yet know how to run JaCoCo in isolation of Gradle in order to test that.

**Comment by Godin** [comment]
Your exception stack trace indicates that non-existing value `fıle` is passed for option `output`.

Given

`src/main/java/Example.java`
```
public class Example {
  public static void main(String[] args) {
    System.out.println("Hello, World!");
  }
}
```

`src/test/java/ExampleTest.java`
```
public class ExampleTest {
  @org.junit.Test
  public void test() {
    Example.main(new String[0]);
  }
}
```

`build.gradle`
```
apply plugin: 'java'
apply plugin: 'jacoco'

repositories {
  mavenCentral()
}

dependencies {
  testCompile 'junit:junit:4.12'
}
```

Following execution of Gradle with debug output clearly shows that Gradle passes this value

```
$ gradle \
    -Duser.language=tr -Duser.country=TR \
    --no-daemon --info \
    clean test
Starting process 'Gradle Test Executor 1'. Working directory: /private/tmp/j Command: /Users/evgeny.mandrikov/.java-select/versions/jdk-8u152-macosx-x64/bin/java -Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager -Dorg.gradle.native=false -javaagent:build/tmp/expandedArchives/org.jacoco.agent-0.8.1.jar_8059ed6e1ab8b88aac5d9097fad847bb/jacocoagent.jar=destfile=build/jacoco/test.exec,append=true,inclnolocationclasses=false,dumponexit=true,output=fıle,jmx=false -Dfile.encoding=UTF-8 -Duser.country=TR -Duser.language=tr -Duser.variant -ea -cp /Users/evgeny.mandrikov/.gradle/caches/4.10.2/workerMain/gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 1'
Successfully started process 'Gradle Test Executor 1'
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
FATAL ERROR in native method: processing of -javaagent failed
Caused by: java.lang.IllegalArgumentException: No enum constant org.jacoco.agent.rt.internal_c13123e.core.runtime.AgentOptions.OutputMode.fıle
        at java.lang.Enum.valueOf(Enum.java:238)
        at org.jacoco.agent.rt.internal_c13123e.core.runtime.AgentOptions$OutputMode.valueOf(AgentOptions.java:123)
        at org.jacoco.agent.rt.internal_c13123e.core.runtime.AgentOptions.getOutput(AgentOptions.java:497)
        at org.jacoco.agent.rt.internal_c13123e.core.runtime.AgentOptions.validateAll(AgentOptions.java:252)
        at org.jacoco.agent.rt.internal_c13123e.core.runtime.AgentOptions.<init>(AgentOptions.java:230)
        at org.jacoco.agent.rt.internal_c13123e.PreMain.premain(PreMain.java:43)
        ... 6 more
```

Most likely as a result of a following `toLowerCase` call in code of Gradle - https://github.com/gradle/gradle/blob/v5.0.0/subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoTaskExtension.java#L62

----

And JaCoCo agent starts perfectly without Gradle with correct options and with `-Duser.language=tr -Duser.country=TR`

```
$ java \
    -Duser.language=tr -Duser.country=TR \
    -javaagent:jacoco-0.8.1/lib/jacocoagent.jar=output=file,destfile=build/jacoco/test.exec \
    -cp build/classes/java/main \
    Example
Hello, World!
```

----

Therefore please report this to developers of Gradle.

**Comment by trejkaz** [comment]
Okay, it does seem like it's in Gradle's court, or at least that one line of code is definitely bad.

The one thing that doesn't quite add up is that I'm not actually running Gradle in Turkish locale, just the tests themselves. So as far as I know, Gradle is in en_AU, and should just bypass the bug entirely. Obviously it isn't though, for some reason.
