### ISSUE TITLE
Aggregate report for multi-JPMS: Can't add different class with same name: module-info

### ISSUE THREAD

**Issue by vlsi** [jacoco/jacoco#858]
### Steps to reproduce

JaCoCo version: 0.8.3
Tool integration: Gradle 5.2.1

Multiple modules, JacocoReport Gradle task (note, there's no option to configure "exclude file").
Source directory list all the directories of project submodules. Each of them happens to have `module-info.class` which confuses JaCoCo

```kotlin
val jacocoReport by tasks.registering(JacocoReport::class) {
    group = "Coverage reports"
    description = "Generates an aggregate report from all subprojects"
}

allprojects {
    plugins.withType<JacocoPlugin> {
        val testTasks = tasks.withType<Test>()
        testTasks.configureEach {
            extensions.configure<JacocoTaskExtension> {
                // We don't want to collect coverage for third-party classes
                includes?.add("org.apache.jmeter.*")
            }
        }

        jacocoReport {
            // Note: this creates a lazy collection
            // Some of the projects might fail to create a file (e.g. no tests or no coverage),
            // So we check for file existence. Otherwise JacocoMerge would fail
            val execFiles = files(testTasks).filter { it.exists() && it.name.endsWith(".exec") }
            executionData(execFiles)
        }

        // Add each project to combined report
        configure<SourceSetContainer> {
            val mainCode = main.get()
            jacocoReport.configure {
                additionalSourceDirs.from(mainCode.allJava.srcDirs)
                sourceDirectories.from(mainCode.allSource.srcDirs)
                // IllegalStateException: Can't add different class with same name: module-info
                classDirectories.from(mainCode.output)  // <-- this fails
            }
        }
    }
```

### Expected behaviour

`module-info.class` should be just ignored or attributed properly

### Actual behaviour

```
....
Caused by: java.io.IOException: Error while analyzing .../domain/build/classes/kotlin/main/module-info.class.
        at org.jacoco.core.analysis.Analyzer.analyzerError(Analyzer.java:168)
        at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:140)
        at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:163)
        at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:199)
        at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:232)
        at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:227)
        at org.jacoco.ant.ReportTask.createBundle(ReportTask.java:567)
        at org.jacoco.ant.ReportTask.createReport(ReportTask.java:542)
        at org.jacoco.ant.ReportTask.execute(ReportTask.java:495)
        ... 107 more
Caused by: java.lang.IllegalStateException: Can't add different class with same name: module-info
        at org.jacoco.core.analysis.CoverageBuilder.visitCoverage(CoverageBuilder.java:105)
        at org.jacoco.core.analysis.Analyzer$1.visitEnd(Analyzer.java:98)
        at org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:326)
        at org.jacoco.core.internal.flow.ClassProbesAdapter.visitEnd(ClassProbesAdapter.java:98)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:683)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
        at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:122)
        at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:138)
        ... 114 more
```

**Comment by Godin** [comment]
> (note, there's no option to configure "exclude file")
> ...
> ```
> classDirectories.from(mainCode.output) // <-- this is a directory, so module-info.class is inside
> ```

AFAIK exclusion of `class` files for JacocoReport Gradle task is usually done via `classDirectories`, which is `FileCollection` that can contain not just directories, but directly `class` files. So could you please try following

```
classDirectories.from(mainCode.output.asFileTree.matching {
	exclude("module-info.class")
})
```

? Also should be noted that most likely this is related to #817 , so you can also try to downgrade version from `0.8.3` to `0.8.2`

```
configure<JacocoPluginExtension> {
	toolVersion = "0.8.2"
}
```

**Comment by vlsi** [comment]
@Godin , does it really make sense to parse `module-info.class`?

By the way:

```
classDirectories.from(mainCode.output.asFileTree.matching {
	exclude("module-info.class")
})
```
it works!

I did try
```
classDirectories.from(fileTree(mainCode.output) {
	exclude("module-info.class")
})
```
and it fails with 

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':jacocoReport'.
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:46)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.internal.typeconversion.UnsupportedNotationException: Cannot convert the provided notation to a File or URI: main classes.
The following types/formats are supported:
  - A String or CharSequence path, for example 'src/main/java' or '/usr/include'.
  - A String or CharSequence URI, for example 'file:/usr/include'.
  - A File instance.
  - A Path instance.
  - A Directory instance.
  - A RegularFile instance.
  - A URI or URL instance.
        at org.gradle.internal.typeconversion.ErrorHandlingNotationParser.parseNotation(ErrorHandlingNotationParser.java:56)
        at org.gradle.api.internal.file.AbstractFileResolver.convertObjectToFile(AbstractFileResolver.java:117)
        at org.gradle.api.internal.file.AbstractBaseDirFileResolver.doResolve(AbstractBaseDirFileResolver.java:69)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:86)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:65)
        at org.gradle.api.internal.file.collections.DefaultConfigurableFileTree.getDir(DefaultConfigurableFileTree.java:70)
        at org.gradle.api.internal.file.collections.DefaultConfigurableFileTree.visitContents(DefaultConfigurableFileTree.java:142)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveNested(DefaultFileCollectionResolveContext.java:144)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:112)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileCollections(DefaultFileCollectionResolveContext.java:92)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext$FileCollectionConverter.convertInto(DefaultFileCollectionResolveContext.java:164)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:109)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileCollections(DefaultFileCollectionResolveContext.java:92)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext$FileCollectionConverter.convertInto(DefaultFileCollectionResolveContext.java:164)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:109)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileCollections(DefaultFileCollectionResolveContext.java:92)
        at org.gradle.api.internal.file.CompositeFileCollection.getSourceCollections(CompositeFileCollection.java:192)
        at org.gradle.api.internal.file.CompositeFileCollection.visitLeafCollections(CompositeFileCollection.java:204)
        at org.gradle.internal.snapshot.impl.DefaultFileSystemSnapshotter.snapshot(DefaultFileSystemSnapshotter.java:126)
        at org.gradle.internal.fingerprint.impl.AbstractFileCollectionFingerprinter.fingerprint(AbstractFileCollectionFingerprinter.java:47)
        at org.gradle.internal.fingerprint.impl.AbstractPathOnlyFileCollectionFingerprinter.fingerprint(AbstractPathOnlyFileCollectionFingerprinter.java:36)
        at org.gradle.api.internal.tasks.execution.DefaultTaskFingerprinter.fingerprintTaskFiles(DefaultTaskFingerprinter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.createExecutionState(ResolveBeforeExecutionStateTaskExecuter.java:92)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:72)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:93)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:45)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        ... 24 more
```

**Comment by Godin** [comment]
@vlsi `fileTree(mainCode.output)` doesn't work, because argument to [`Project.fileTree`](https://docs.gradle.org/5.2.1/dsl/org.gradle.api.Project.html#org.gradle.api.Project:fileTree(java.lang.Object)) is evaluated as per [`Project.file(java.lang.Object)`](https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:fileTree(java.lang.Object)), which can not convert [`SourceSetOutput SourceSet.getOutput()`](https://docs.gradle.org/5.2.1/javadoc/org/gradle/api/tasks/SourceSet.html#getOutput--). And that's why I proposed [`asFileTree`](https://docs.gradle.org/5.2.1/javadoc/org/gradle/api/file/FileCollection.html#getAsFileTree--).

----

> does it really make sense to parse `module-info.class` ?

While it doesn't make sense, [our API allows to analyze `class` file from `byte` array](https://www.jacoco.org/jacoco/trunk/doc/api/org/jacoco/core/analysis/Analyzer.html#analyzeClass(byte[],%20java.lang.String)), so  in general case prior to / without  parsing we don't know that array contains `module-info.class`. And parsing wasn't causing troubles prior to #817. Anyway thank you for reporting this :thumbsup: :heart:  We'll work on fixing this.

And glad to hear that exclusion works as workaround. BTW be aware that duplicate classes are not allowed because we can't associate them with sources, [JEP-238 (Multi-Release JAR Files)](http://openjdk.java.net/jeps/238) is another source of duplicate classes for which exclusions should be used - #407.

**Comment by vlsi** [comment]
@Godin , it looks like the proper way to approach that would be to to use `structure`/`group` somehow so coverage results are groupped by module and it would (in theory) allow to have classes with the same name in different modules.

This looks promising: https://gist.github.com/aalmiray/e6f54aa4b3803be0bcac#gistcomment-1560310

**Comment by Godin** [comment]
@vlsi yes - different `structure`s / `group`s can contain same class name. And while Gradle Plugin internally uses Ant Task, it doesn't allow to define `structure`s, so indeed for them one need to use Ant Task directly.

> However there's no way to associate `group` with `coverage data`.

In respect to duplicates this is not needed, because `exec` file can contain information about different `class` files with same name and they will be correctly associated with corresponding `class` files during report generation thanks to [`class id`s](https://www.jacoco.org/jacoco/trunk/doc/classids.html).

And in respect to limiting boundaries of one `structure`, i.e. for example when module `x` touches classes of module `y` and you don't want these touches to be shown in report for `y`, then you can limit information recorded into `exec` file during execution of module `x` using [Java agent options `includes` and `excludes`](https://www.jacoco.org/jacoco/trunk/doc/agent.html) and corresponding options of other integrations such as [`includes`/`excludes` options of Ant Tasks `coverage`/`agent`](https://www.jacoco.org/jacoco/trunk/doc/ant.html) or [`includes`/`excludes` options of JacocoTaskExtension in Gradle Plugin](https://docs.gradle.org/current/dsl/org.gradle.testing.jacoco.plugins.JacocoTaskExtension.html).

**Comment by Godin** [comment]
After more thoughts about last use-case, maybe we indeed should consider addition of element `executiondata` into `structure` as enhancement (CC @marchof), which will allow creation of both non-intersecting and intersecting reports from the same `exec` files without tweaks in agent options.
