### ISSUE TITLE
Scala macros crash JaCoCo

### ISSUE THREAD

**Issue by pmwmedia** [jacoco/jacoco#860]
Generating a code coverage report for a Scala project that uses macros, crashes JaCoCo with an exception and no reports are generated. If I remove the macro from my Scala project, JaCoCo will work and generate a code coverage report.

### Steps to reproduce

JaCoCo version: 0.8.3
Operating system: Windows 10
Tool integration: Maven 3.5.5
Example project: [example.zip](https://github.com/jacoco/jacoco/files/2985944/example.zip)

```scala
import scala.language.experimental.macros
import scala.reflect.macros.blackbox

object Calculator {
  
  def add(a: Int, b: Int): Int = macro Calculator.magic
   
  def magic(context: blackbox.Context)(a: context.Expr[Int], b: context.Expr[Int]): context.universe.Tree = {
    import context.universe._
    return q"42"
  }

}
```

```scala
import org.junit.Test
import org.junit.Assert.assertEquals;

class CalculatorTest {
  
  @Test def test() = { assertEquals(42, Calculator.add(1, 1)) }
  
}
```

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>scala-jacoco</artifactId>
  <version>1.0.0-SNAPSHOT</version>

  <dependencies>
    <dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala-library</artifactId>
      <version>2.12.8</version>
    </dependency>
    <dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala-reflect</artifactId>
      <version>2.12.8</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jacoco</groupId>
      <artifactId>org.jacoco.agent</artifactId>
      <version>0.8.3</version>
      <classifier>runtime</classifier>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <sourceDirectory>${project.basedir}/src/main/scala</sourceDirectory>
    <testSourceDirectory>${project.basedir}/src/test/scala</testSourceDirectory>
    <plugins>
      <plugin>
        <groupId>net.alchim31.maven</groupId>
        <artifactId>scala-maven-plugin</artifactId>
        <version>4.0.1</version>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.8.3</version>
        <executions>
          <execution>
            <id>instrumentation</id>
            <goals>
              <goal>instrument</goal>
              <goal>restore-instrumented-classes</goal>
            </goals>
          </execution>
          <execution>
            <id>reporting</id>
            <phase>prepare-package</phase>
            <goals>
              <goal>report</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.22.1</version>
        <configuration>
          <systemPropertyVariables>
            <jacoco-agent.destfile>target/jacoco.exec</jacoco-agent.destfile>
          </systemPropertyVariables>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
```

### Expected behaviour

Generation of a code coverage report and no exception

### Actual behaviour

Exception at the end of the Maven build:

```
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: org/jacoco/agent/rt/internal_1f1cc91/core/data/ExecutionDataWriter
	at org.jacoco.agent.rt.internal_1f1cc91.output.FileOutput.writeExecutionData(FileOutput.java:55)
	at org.jacoco.agent.rt.internal_1f1cc91.Agent.shutdown(Agent.java:137)
	at org.jacoco.agent.rt.internal_1f1cc91.Agent$1.run(Agent.java:54)
Caused by: java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_1f1cc91.core.data.ExecutionDataWriter
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 3 more
```

No code coverage report is created.

**Comment by Godin** [comment]
@pmwmedia I don't know yet what is exactly going on in your example, however [as written in our documentation](https://www.jacoco.org/jacoco/trunk/doc/instrument-mojo.html) - we strongly do not recommend usage of offline instrumentation as it has many drawbacks. And usage of JaCoCo agent (on-the-fly instrumentation)

```diff
 <execution>
-	<id>instrumentation</id>
+	<id>prepare-agent</id>
 	<goals>
-		<goal>instrument</goal>
-		<goal>restore-instrumented-classes</goal>
+		<goal>prepare-agent</goal>
 	</goals>
 </execution>
```

works for this example without any exceptions, producing report.

**Comment by pmwmedia** [comment]
Unfortunately on-the-fly instrumentation doesn't work with PowerMock: https://github.com/powermock/powermock/wiki/Code-coverage-with-JaCoCo

Therefore I depend on offline instrumentation for my project.

**Comment by Godin** [comment]
@pmwmedia according to log of

```
MAVEN_OPTS="-XX:+TraceClassLoading -Djacoco-agent.output=tcpclient -Djacoco-agent.address=127.0.0.1" mvn clean package
```

```
...
[INFO] --- scala-maven-plugin:4.0.1:testCompile (default) @ scala-jacoco ---
...
[Loaded Calculator$ from file:/private/tmp/example/target/classes/]
[Loaded org.jacoco.agent.rt.internal_1f1cc91.Offline from file:/Users/evgeny.mandrikov/.m2/repository/org/jacoco/org.jacoco.agent/0.8.3/org.jacoco.agent-0.8.3-runtime.jar]
...
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:211)
        at org.jacoco.agent.rt.internal_1f1cc91.output.TcpClientOutput.createSocket(TcpClientOutput.java:85)
        at org.jacoco.agent.rt.internal_1f1cc91.output.TcpClientOutput.startup(TcpClientOutput.java:49)
        at org.jacoco.agent.rt.internal_1f1cc91.Agent.startup(Agent.java:122)
        at org.jacoco.agent.rt.internal_1f1cc91.Agent.getInstance(Agent.java:50)
        at org.jacoco.agent.rt.internal_1f1cc91.Offline.<clinit>(Offline.java:31)
        at Calculator$.$jacocoInit(Calculator.scala)
        at Calculator$.<clinit>(Calculator.scala)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers.resolveJavaReflectionRuntime(JavaReflectionRuntimes.scala:28)
        at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers.resolveJavaReflectionRuntime$(JavaReflectionRuntimes.scala:27)
        at scala.reflect.macros.runtime.MacroRuntimes$MacroRuntimeResolver.resolveJavaReflectionRuntime(MacroRuntimes.scala:75)
        at scala.reflect.macros.runtime.MacroRuntimes$MacroRuntimeResolver.resolveRuntime(MacroRuntimes.scala:88)
        at scala.reflect.macros.runtime.MacroRuntimes.$anonfun$standardMacroRuntime$3(MacroRuntimes.scala:50)
...
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1475)
        at scala.tools.nsc.Global$Run.compile(Global.scala:1598)
        at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
        at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
        at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
...
[INFO] Done compiling.
...
```

Execution of instrumented class happens during compilation of tests inside JVM that executes Maven (`Class.forName(..., true, ...)` in [`JavaReflectionRuntimes.scala:28`](https://github.com/scala/scala/blame/v2.12.8/src/compiler/scala/reflect/macros/runtime/JavaReflectionRuntimes.scala#L28) causes class initialization).

JaCoCo saves execution data by means of JVM shutdown hook, so such execution of instrumented class at compilation time results in `NoClassDefFoundError` that you see during shutdown of JVM that executes Maven, because `org.jacoco:org.jacoco.agent:0.8.3:runtime` (required in case of offline instrumentation) is visible to compiler and in classpath of JVM that executes tests, but not in classpath of JVM that executes Maven.

To sum up: on the JaCoCo side everything works as expected.

Inability to use JaCoCo agent due to the fact that PowerMock bypasses all agents - is a question to PowerMock developers.

To avoid execution of instrumented classes during compilation you can execute `instrument` after `test-compile` in `process-test-classes` phase:

```diff
 <execution>
-	<id>instrumentation</id>
+	<id>instrument-classes</id>
+	<-- instrument in jacoco-maven-plugin 0.8.3 bound to process-classes phase by default -->
+	<phase>process-test-classes</phase>
 	<goals>
 		<goal>instrument</goal>
-		<goal>restore-instrumented-classes</goal>
 	</goals>
 </execution>
+<execution>
+	<id>restore-instrumented-classes</id>
+	<-- restore-instrumented-classes in jacoco-maven-plugin 0.8.3 bound to prepare-package phase by default -->
+	<goals>
+		<goal>restore-instrumented-classes</goal>
+	</goals>
+<execution>
```

Note that in this case anyway report won't be generated 

```
[INFO] --- jacoco-maven-plugin:0.8.3:report (reporting) @ scala-jacoco ---
[INFO] Skipping JaCoCo execution due to missing execution data file.
```

which is expected, because test does not execute instrumented code at all - quoting https://docs.scala-lang.org/overviews/macros/overview.html

> The result of the macro implementation is another abstract syntax tree, which will be **inlined at the call site**

**Comment by pmwmedia** [comment]
@Godin Thank you very much! That helps me a lot.
