### ISSUE TITLE
Error while creating report: null: EOFException

### ISSUE THREAD

**Issue by mejmo** [jacoco/jacoco#901]
We are having the similar issue as #546, but I am not sure if it is a problem of surefire or jacoco. We have the newest versions of our tools but the problem still occurs randomly.

### Steps to reproduce

Running maven in docker, openjdk:11-stretch with maven 3.6.1 and jdk11
JaCoCo version: 0.8.4
Operating system: MacOS 
Tool integration: Maven 3.6.1 / Jenkins

### Expected behaviour
- Jacoco processes the jacoco.exec

### Actual behaviour
```
 [ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.4:report (default-report) on project task: An error has occurred in JaCoCo report generation. Error while creating report: null: EOFException -> [Help 1]
```

**Comment by marchof** [comment]
Can you please provide the **full stack** trace? Run Maven with -X

**Comment by mejmo** [comment]
```
[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.4:report (default-report) on project task: An error has occurred in JaCoCo report generation. Error while creating report: null: EOFException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.4:report (default-report) on project task: An error has occurred in JaCoCo report generation.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An error has occurred in JaCoCo report generation.
    at org.jacoco.maven.AbstractReportMojo.execute (AbstractReportMojo.java:167)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.reporting.MavenReportException: Error while creating report: null
    at org.jacoco.maven.AbstractReportMojo.executeReport (AbstractReportMojo.java:183)
    at org.jacoco.maven.AbstractReportMojo.execute (AbstractReportMojo.java:165)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.io.EOFException
    at java.io.DataInputStream.readByte (DataInputStream.java:272)
    at org.jacoco.core.internal.data.CompactDataInput.readBooleanArray (CompactDataInput.java:63)
    at org.jacoco.core.data.ExecutionDataReader.readExecutionData (ExecutionDataReader.java:149)
    at org.jacoco.core.data.ExecutionDataReader.readBlock (ExecutionDataReader.java:115)
    at org.jacoco.core.data.ExecutionDataReader.read (ExecutionDataReader.java:92)
    at org.jacoco.core.tools.ExecFileLoader.load (ExecFileLoader.java:59)
    at org.jacoco.core.tools.ExecFileLoader.load (ExecFileLoader.java:73)
    at org.jacoco.maven.ReportSupport.loadExecutionData (ReportSupport.java:87)
    at org.jacoco.maven.ReportMojo.loadExecutionData (ReportMojo.java:60)
    at org.jacoco.maven.AbstractReportMojo.executeReport (AbstractReportMojo.java:177)
    at org.jacoco.maven.AbstractReportMojo.execute (AbstractReportMojo.java:165)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
```

**Comment by marchof** [comment]
Ok, so this happens due to a truncated (or not fully written) exec file. So the problem is when your exec file is written. This situation typically occurs when the Java process is not properly shut down (or has been killed). We also learned from users that this happens within docker file system.

**Comment by mejmo** [comment]
I am writing the file to the filesystem on the host through volume mount. So its not docker file system in fact.

**Comment by Godin** [comment]
@mejmo Given that your host OS is macOS, then AFAIK on this host Docker images will run inside of Linux virtual machine, so mount of the host filesystem involves at least communication with this virtual machine thru Docker components, which maybe not functioning properly and there are [examples](https://github.com/boot2docker/osx-installer/issues/100) that [this can happen](https://stackoverflow.com/questions/56066775/docker-container-cant-run-jacoco-agent-with-java-12/56119766#56119766). And as @marchof said - there can be other reasons such as improper non-graceful JVM termination, or even broken disk. There is nothing special in a way JaCoCo Agent writes to the file - it [uses ordinary JVM shutdown hook](https://github.com/jacoco/jacoco/blob/v0.8.4/org.jacoco.agent.rt/src/org/jacoco/agent/rt/internal/Agent.java#L51) and [ordinary `OutputStream`](https://github.com/jacoco/jacoco/blob/v0.8.4/org.jacoco.agent.rt/src/org/jacoco/agent/rt/internal/output/FileOutput.java#L53), and this code is used for years by many users in many different environments, so please believe our 10-years experience that the reason is not in JaCoCo. We nor have reproducer from you, nor access to your environment, so please understand that we can't say more than what was already said here and not going to try blind guesses - please investigate your setup in your environment.

For your further investigations you can try to build and use JaCoCo with following modification in agent to produce debug messages about writing to a file - https://github.com/Godin/jacoco/commit/4ea27714c994f73995a17d61cf88697f9c3cfebb :

```diff --git c/org.jacoco.agent.rt/src/org/jacoco/agent/rt/internal/output/FileOutput.java w/org.jacoco.agent.rt/src/org/jacoco/agent/rt/internal/output/FileOutput.java
index dde78609..50f4eed3 100644
--- c/org.jacoco.agent.rt/src/org/jacoco/agent/rt/internal/output/FileOutput.java
+++ w/org.jacoco.agent.rt/src/org/jacoco/agent/rt/internal/output/FileOutput.java
@@ -40,6 +40,7 @@ public class FileOutput implements IAgentOutput {
 			throws IOException {
 		this.data = data;
 		this.destFile = new File(options.getDestfile()).getAbsoluteFile();
+		System.err.println("JaCoCo: file " + destFile + " exists? " + destFile.exists());
 		this.append = options.getAppend();
 		final File folder = destFile.getParentFile();
 		if (folder != null) {
@@ -50,12 +51,15 @@ public class FileOutput implements IAgentOutput {
 	}
 
 	public void writeExecutionData(final boolean reset) throws IOException {
+		System.err.println("JaCoCo: start writing to " + destFile);
 		final OutputStream output = openFile();
 		try {
 			final ExecutionDataWriter writer = new ExecutionDataWriter(output);
 			data.collect(writer, writer, reset);
+			System.err.println("JaCoCo: done writing to " + destFile);
 		} finally {
 			output.close();
+			System.err.println("JaCoCo: done closing " + destFile);
 		}
 	}
```

**Comment by mejmo** [comment]
You are right, I absolutely forgot that Mac OS docker is using another layer between guest and host.

However, now I am trying to do workaround (before trying your patch for debugging @Godin). I am trying to use `tcpclient` option, but I am getting `NullPointerException`. 

```
nc -l 0.0.0.0 10001 > /tmp/testing &
mvn clean test -Djacoco.output=tcpclient -Djacoco.address=127.0.0.1 -Djacoco.port=10001 -Djacoco.reset=true -Djacoco.append=true
```

Exception:
```
java.lang.NullPointerException
	at org.jacoco.agent.rt.internal_035b120.output.TcpClientOutput.writeExecutionData(TcpClientOutput.java:72)
	at org.jacoco.agent.rt.internal_035b120.Agent.shutdown(Agent.java:137)
	at org.jacoco.agent.rt.internal_035b120.Agent$1.run(Agent.java:54)
```

Probably the `connection` is null because startup() fails, where it sets this singleton. However, on host system it works. These problems are related just for the setup docker+macOS.

**Comment by mejmo** [comment]
Ok I think I have the solution:

netcat has different ports for different Unix types. My docker image is based on debian stretch. So basically I am opening tcpserver which waits for connection, jacoco writes data there, I delete the generated file and copy the one got from tcpserver. Little bit hacky, bit it does the job and `EOFException` does not occur anymore.

You need to adjust to your maven workflow, we are calling `jacoco:report` in the package phase.

```
nc -l -p 10001 > /tmp/jacoco.exec &
mvn clean test -Djacoco.output=tcpclient -Djacoco.address=127.0.0.1 -Djacoco.port=10001 -Djacoco.reset=true -Djacoco.append=true
rm target/jacoco.exec && cp /tmp/jacoco.exec /target/jacoco.exec
mvn package
```

**Comment by Godin** [comment]
> Probably the `connection` is `null` because `startup()` fails

Indeed execution of

```
java -javaagent:jacoco-0.8.4/lib/jacocoagent.jar=output=tcpclient,address=NonexistentHostname --version
```

leads to

```
java.net.UnknownHostException: NonexistentHostname
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
        at java.base/java.net.Socket.connect(Socket.java:591)
        at java.base/java.net.Socket.connect(Socket.java:540)
        at java.base/java.net.Socket.<init>(Socket.java:436)
        at java.base/java.net.Socket.<init>(Socket.java:213)
        at org.jacoco.agent.rt.internal_035b120.output.TcpClientOutput.createSocket(TcpClientOutput.java:85)
        at org.jacoco.agent.rt.internal_035b120.output.TcpClientOutput.startup(TcpClientOutput.java:49)
        at org.jacoco.agent.rt.internal_035b120.Agent.startup(Agent.java:122)
        at org.jacoco.agent.rt.internal_035b120.Agent.getInstance(Agent.java:50)
        at org.jacoco.agent.rt.internal_035b120.PreMain.premain(PreMain.java:49)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
java 11.0.3 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.3+12-LTS, mixed mode)
java.lang.NullPointerException
        at org.jacoco.agent.rt.internal_035b120.output.TcpClientOutput.writeExecutionData(TcpClientOutput.java:72)
        at org.jacoco.agent.rt.internal_035b120.Agent.shutdown(Agent.java:137)
        at org.jacoco.agent.rt.internal_035b120.Agent$1.run(Agent.java:54)
```

However [in case of exception at Agent startup this exception also will be shown](https://github.com/jacoco/jacoco/blob/v0.8.4/org.jacoco.agent.rt/src/org/jacoco/agent/rt/internal/Agent.java#L127) as in example above.

----

> These problems are related just for the setup docker

Setup and debugging of Docker is not in the scope of JaCoCo project and its issue tracker.

**Comment by jamesmehorter** [comment]
I was running into this issue when running `mvn clean install` inside a docker container. The fix for me was to define `JAVA_HOME` on my host machine prior to running the container:

```
$ export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
```
