### ISSUE TITLE
NPE in KotlinWhenStringFilter

### ISSUE THREAD

**Issue by marchof** [jacoco/jacoco#940]
### Steps to reproduce

JaCoCo version: master (commit 8b586a98803923f11a9b05fe214fa25c2c23207f) 
Operating system: OSX
Tool integration: CLI

Run

    java -jar jacococli.jar report --classfiles NPE.zip

on the attached class file.

### Expected behaviour

Command terminates without exception.

### Actual behaviour

```
Exception in thread "main" java.io.IOException: Error while analyzing NPE.zip@$value$ReadableByteChannel.class.
	at org.jacoco.core.analysis.Analyzer.analyzerError(Analyzer.java:161)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:133)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:156)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:192)
	at org.jacoco.core.analysis.Analyzer.analyzeZip(Analyzer.java:264)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:195)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:225)
	at org.jacoco.cli.internal.commands.Report.analyze(Report.java:109)
	at org.jacoco.cli.internal.commands.Report.execute(Report.java:83)
	at org.jacoco.cli.internal.Main.execute(Main.java:89)
	at org.jacoco.cli.internal.Main.main(Main.java:104)
Caused by: java.lang.NullPointerException
	at org.jacoco.core.internal.analysis.MethodCoverageCalculator.ignore(MethodCoverageCalculator.java:159)
	at org.jacoco.core.internal.analysis.filter.KotlinWhenStringFilter$Matcher.match(KotlinWhenStringFilter.java:98)
	at org.jacoco.core.internal.analysis.filter.KotlinWhenStringFilter.filter(KotlinWhenStringFilter.java:37)
	at org.jacoco.core.internal.analysis.filter.Filters.filter(Filters.java:57)
	at org.jacoco.core.internal.analysis.ClassAnalyzer.addMethodCoverage(ClassAnalyzer.java:118)
	at org.jacoco.core.internal.analysis.ClassAnalyzer.access$2(ClassAnalyzer.java:113)
	at org.jacoco.core.internal.analysis.ClassAnalyzer$1.accept(ClassAnalyzer.java:107)
	at org.jacoco.core.internal.flow.ClassProbesAdapter$2.visitEnd(ClassProbesAdapter.java:89)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1287)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:688)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:115)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:131)
	... 9 more
```
[NPE.zip](https://github.com/jacoco/jacoco/files/3636164/NPE.zip)

**Comment by marchof** [comment]
I run into this while trying to reproduce an issue reported to our mailing list: https://groups.google.com/forum/?fromgroups=#!topic/jacoco/cx9sTR3KMr4

**Comment by marchof** [comment]
The NPE happens because `KotlinWhenStringFilter` calls

    IFilterOutput.ignore(AbstractInsnNode fromInclusive, AbstractInsnNode toInclusive)

where `toInclusive` is before `fromInclusive`. In this case `MethodCoverageCalculator` iterates over the end of the method.

**Comment by Godin** [comment]
> KotlinWhenStringFilter calls `IFilter.output` where `toInclusive` is before `fromInclusive`

this happens for the following weird bytecode

```
         0: aload_1
         1: invokevirtual #121                // Method java/lang/String.hashCode:()I
         4: lookupswitch  { // 0
                 default: 16
            }
        16:
```

because following loop is not executed

https://github.com/jacoco/jacoco/blob/8b586a98803923f11a9b05fe214fa25c2c23207f/org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinWhenStringFilter.java#L73

and hence cursor doesn't move

```
final AbstractInsnNode s = cursor;
...
for (int i = 0; i < hashCodes; i++) {
  ...
}
output.ignore(s.getNext(), cursor);
```

**Comment by Godin** [comment]
Following weird Java code causes the same NPE

```
class Example {
	private static void example(String s) {
		switch (s.hashCode()) {
			default:
				break;
		}
	}
}
```

**Comment by Godin** [comment]
And we can have similar NPE in `StringSwitchEcjFilter` - #944
