### ISSUE TITLE
Jmockit is not working with JDK 11

### ISSUE THREAD

**Issue by MumtazRashid** [jacoco/jacoco#950]
I am using jmockit 1.8 version and JDK 11 but it throwing me blow execption : 

Caused by: java.lang.IllegalStateException: JMockit requires a Java 6+ VM
	at mockit.internal.startup.AgentInitialization.loadAgentFromLocalJarFile(AgentInitialization.java:23)
	at mockit.internal.startup.Startup.verifyInitialization(Startup.java:213)
	at mockit.MockUp.<clinit>(MockUp.java:88)
	... 2 more

Root cause: java.lang.IllegalStateException: JMockit requires a Java 6+ VM
	at mockit.internal.startup.AgentInitialization.loadAgentFromLocalJarFile(AgentInitialization.java:23)
	at mockit.internal.startup.Startup.verifyInitialization(Startup.java:213)
	at mockit.MockUp.<clinit>(MockUp.java:88)

How can we resolve it, it is working fine with jdk8.

**Comment by marchof** [comment]
This is the bug tracker of JaCoCo. Please report to JMockit.

**Comment by MumtazRashid** [comment]
sure

**Comment by MumtazRashid** [comment]
na
