### ISSUE TITLE
jacoco api  Error while analyzing xxxx.class.

### ISSUE THREAD

**Issue by wzl-coder** [jacoco/jacoco#958]
When I use java api  analyzer.analyzeAll(); 
An error has occurred

```
java.io.IOException: Error while analyzing xxxx.class.
	at org.jacoco.core.analysis.Analyzer.analyzerError(Analyzer.java:161)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:133)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:156)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:192)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:225)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:220)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:220)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:220)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:220)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:220)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:220)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalStateException: Cannot process instrumented  xxx. Please supply original non-instrumented classes.
	at org.jacoco.core.internal.instr.InstrSupport.assertNotInstrumented(InstrSupport.java:237)
	at org.jacoco.core.internal.analysis.ClassAnalyzer.visitField(ClassAnalyzer.java:126)
	at org.objectweb.asm.ClassVisitor.visitField(ClassVisitor.java:287)
	at org.objectweb.asm.ClassReader.readField(ClassReader.java:906)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:683)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:115)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:131)
	... 40 more
```

How can I solve this error? thanks

**Comment by Godin** [comment]
As clearly stated in the error message

> Caused by: java.lang.IllegalStateException: Cannot process instrumented  xxx. Please supply original non-instrumented classes.

You are trying to analyze classes that were instrumented by JaCoCo, whereas **analysis requires original non-instrumented classes**.

**Comment by calvarez-ov** [comment]
LOL. Our android test suite was working yesterday.

Today we changed some strings. No code changes.

Then we ended up with failures due to an issue with [mockk](https://github.com/mockk/mockk/pull/472). This issue (in mockk) only appears since the new robolectric 4.4. Though it's not robolectric's fault, a robolectric maintainer fixed it. But mockk hasn't released a new version with the fix yet....

In the huge stack trace in our failed test, which contains errors like "cannot cast class a.b.WTF to a.b.WTF" (the mock issue), I also see this:
> Caused by: java.lang.IllegalStateException: Cannot process instrumented xxx. Please supply original non-instrumented classes.

So I google that, hoping to make sense of this fragile cocktail of librairies which don't seem to work well together, and I find this issue that states that this error message is "clear".

Clearly, I need a vacation.

**Comment by Sudip7** [comment]
Hello @Godin , although it's a closed issue, would like to know; what should one do to avoid/suppress these type errors.

**Comment by marchof** [comment]
@Sudip7 

Exactly what the error message says: "Please supply original non-instrumented classes."

**Comment by Godin** [comment]
@Sudip7 exactly as explained in the error message:

> **Please supply original non-instrumented classes.**

E.g. if you use https://www.jacoco.org/jacoco/trunk/doc/instrument-mojo.html then also make sure to use https://www.jacoco.org/jacoco/trunk/doc/restore-instrumented-classes-mojo.html

**Comment by Sudip7** [comment]
Thank you for replying. I found one reference: https://javalibs.com/plugin/org.jacoco/jacoco-maven-plugin
Here is my current project use

```
<plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.8.3</version>
        <executions>
          <execution>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
          <execution>
            <id>report</id>
            <phase>prepare-package</phase>
            <goals>
              <goal>report</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

I try to add suggestion by following above link appended below execution

```
<execution>
      <id>default-instrument</id>
      <goals>
        <goal>instrument</goal>
      </goals>
    </execution>
    <execution>
      <id>default-restore-instrumented-classes</id>
      <goals>
        <goal>restore-instrumented-classes</goal>
      </goals>
    </execution>
```
but it's still not working. Please advise

**Comment by marchof** [comment]
@Sudip7 JaCoCo agent instruments classes on-the-fly. Don't combine it with instrument goal.

**Comment by Sudip7** [comment]
@marchof i haven't added the instrument related goal yet. We are just using jacoco maven plugin for reporting goal but still getting error as said above. I am trying to suppress or resolve those error.

**Comment by udaybuie** [comment]
i was also facing the same error, seems prepare agent is also instrumenting the classes. putting below exclusion criteria worked for me.

                 <execution>
                        <id>prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                        <configuration>
                            <excludes>
                                <excludes>*</excludes>
                            </excludes>
                        </configuration>
                    </execution>

**Comment by wyztix** [comment]
I know I'm bringing this back from the dead, but there is still no clear answer.

In my case, the issue was caused by the quarkus-jacoco dependency. When added to Maven, it uses JaCoCo runtime agent and instrument the tests. This was the core reason for the exception. If you are using pom.xml, you can look at the workaround in the quarkus documentation (https://quarkus.io/guides/tests-with-coverage#setting-up-jacoco).

For those running the tests from command line, you can simply add -Djacoco.exclClassLoaders="*QuarkusClassLoader" before the goals.

**Comment by SG2607** [comment]
I am facing the same error. Can anyone help ? How to resolve the errro "Error while analyzing xxxx.class." ?
and can we generate jacoco report without providing --classfiles ?
