### ISSUE TITLE
 An error has occurred in JaCoCo Aggregate report generation.: Error while creating report: null: EOFException

### ISSUE THREAD

**Issue by zlp19860220** [jacoco/jacoco#980]
hi,guys~~i got this error when i use mvn test with jacoco plugin,how to deal with it?
and there is no aggregate report in xxx/target/site

```
17:14:35 Please refer to /usr/local/timevale/jenkins/workspace/ut-coverage-footstone/deploy/target/surefire-reports for the individual test results.
17:14:35 Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
17:14:35 Error occurred in starting fork, check output in log
**17:14:35 org.apache.maven.surefire.booter.SurefireBooterForkException: Error occurred in starting fork, check output in log**
17:14:35 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:623)
17:14:35 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:283)
17:14:35 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)
17:14:35 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1161)
17:14:35 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1002)
17:14:35 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:848)
17:14:35 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
17:14:35 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
17:14:35 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
17:14:35 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
17:14:35 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
17:14:35 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
17:14:35 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
17:14:35 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
17:14:35 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
17:14:35 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
17:14:35 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
17:14:35 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
17:14:35 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
17:14:35 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
17:14:35 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:14:35 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:14:35 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:14:35 	at java.lang.reflect.Method.invoke(Method.java:498)
17:14:35 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
17:14:35 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
17:14:35 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
17:14:35 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
17:14:35 
17:14:35 [INFO] 
17:14:35 [INFO] --- jacoco-maven-plugin:0.8.0:report-aggregate (report) @ footstone-deploy ---
17:14:35 [DEBUG] Configuring mojo org.jacoco:jacoco-maven-plugin:0.8.0:report-aggregate from plugin realm ClassRealm[plugin>org.jacoco:jacoco-maven-plugin:0.8.0, parent: sun.misc.Launcher$AppClassLoader@7852e922]
17:14:35 [DEBUG] Configuring mojo 'org.jacoco:jacoco-maven-plugin:0.8.0:report-aggregate' with basic configurator -->
17:14:35 [DEBUG]   (f) outputDirectory = /usr/local/timevale/jenkins/workspace/ut-coverage-footstone/deploy/target/site/jacoco-aggregate
17:14:35 [DEBUG]   (f) outputEncoding = UTF-8
17:14:35 [DEBUG]   (f) skip = false
17:14:35 [DEBUG]   (f) sourceEncoding = UTF-8
17:14:35 [DEBUG]   (f) title = footstone/deploy
17:14:35 [DEBUG] -- end configuration --
17:14:35 [INFO] Loading execution data file /usr/local/timevale/jenkins/workspace/ut-coverage-footstone/deploy/target/jacoco.exec
17:14:35 [INFO] ------------------------------------------------------------------------
17:14:35 [INFO] Reactor Summary:
17:14:35 [INFO] 
17:14:35 [INFO] footstone/Parent 1.0.0 ............................. SUCCESS [  0.046 s]
17:14:35 [INFO] footstone/util ..................................... SUCCESS [  5.121 s]
17:14:35 [INFO] footstone/dal ...................................... SUCCESS [  2.382 s]
17:14:35 [INFO] footstone/facade ................................... SUCCESS [  0.966 s]
17:14:35 [INFO] footstone/integration .............................. SUCCESS [ 16.199 s]
17:14:35 [INFO] footstone/model .................................... SUCCESS [ 14.252 s]
17:14:35 [INFO] footstone/service .................................. SUCCESS [ 17.226 s]
17:14:35 [INFO] footstone/shared ................................... SUCCESS [  0.377 s]
17:14:35 [INFO] footstone/service-impl ............................. SUCCESS [  3.437 s]
17:14:35 [INFO] footstone-rpc-service-facade ....................... SUCCESS [  2.043 s]
17:14:35 [INFO] footstone-rpc-service-impl ......................... SUCCESS [  3.248 s]
17:14:35 [INFO] footstone/task ..................................... SUCCESS [  1.556 s]
17:14:35 [INFO] footstone/deploy 1.0.0 ............................. FAILURE [13:19 min]
17:14:35 [INFO] ------------------------------------------------------------------------
17:14:35 [INFO] BUILD FAILURE
17:14:35 [INFO] ------------------------------------------------------------------------
17:14:35 [INFO] Total time: 14:27 min
17:14:35 [INFO] Finished at: 2019-12-05T17:14:35+08:00
17:14:35 [INFO] ------------------------------------------------------------------------
**17:14:35 [ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.0:report-aggregate (report) on project footstone-deploy: An error has occurred in JaCoCo Aggregate report generation.: Error while creating report: null: EOFException -> [Help 1]**
**17:14:35 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.0:report-aggregate (report) on project footstone-deploy: An error has occurred in JaCoCo Aggregate report generation.**
17:14:35     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
17:14:35     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
17:14:35     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
17:14:35     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
17:14:35     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
17:14:35     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
17:14:35     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
17:14:35     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
17:14:35     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
17:14:35     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
17:14:35     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
17:14:35     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
17:14:35     at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
17:14:35     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
17:14:35     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
17:14:35     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
17:14:35     at java.lang.reflect.Method.invoke (Method.java:498)
17:14:35     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
17:14:35     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
17:14:35     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
17:14:35     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
**17:14:35 Caused by: org.apache.maven.plugin.MojoExecutionException: An error has occurred in JaCoCo Aggregate report generation.**
17:14:35     at org.jacoco.maven.AbstractReportMojo.execute (AbstractReportMojo.java:167)
17:14:35     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
17:14:35     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
17:14:35     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
17:14:35     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
17:14:35     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
17:14:35     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
17:14:35     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
17:14:35     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
17:14:35     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
17:14:35     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
17:14:35     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
17:14:35     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
17:14:35     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
17:14:35     at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
17:14:35     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
17:14:35     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
17:14:35     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
17:14:35     at java.lang.reflect.Method.invoke (Method.java:498)
17:14:35     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
17:14:35     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
17:14:35     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
17:14:35     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
**17:14:35 Caused by: org.apache.maven.reporting.MavenReportException: Error while creating report: null**
17:14:35     at org.jacoco.maven.AbstractReportMojo.executeReport (AbstractReportMojo.java:183)
17:14:35     at org.jacoco.maven.AbstractReportMojo.execute (AbstractReportMojo.java:165)
17:14:35     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
17:14:35     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
17:14:35     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
17:14:35     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
17:14:35     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
17:14:35     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
17:14:35     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
17:14:35     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
17:14:35     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
17:14:35     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
17:14:35     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
17:14:35     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
17:14:35     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
17:14:35     at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
17:14:35     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
17:14:35     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
17:14:35     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
17:14:35     at java.lang.reflect.Method.invoke (Method.java:498)
17:14:35     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
17:14:35     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
17:14:35     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
17:14:35     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
**17:14:35 Caused by: java.io.EOFException**
17:14:35     at java.io.DataInputStream.readUnsignedShort (DataInputStream.java:340)
17:14:35     at java.io.DataInputStream.readUTF (DataInputStream.java:589)
17:14:35     at java.io.DataInputStream.readUTF (DataInputStream.java:564)
17:14:35     at org.jacoco.core.data.ExecutionDataReader.readExecutionData (ExecutionDataReader.java:148)
17:14:35     at org.jacoco.core.data.ExecutionDataReader.readBlock (ExecutionDataReader.java:115)
17:14:35     at org.jacoco.core.data.ExecutionDataReader.read (ExecutionDataReader.java:92)
17:14:35     at org.jacoco.core.tools.ExecFileLoader.load (ExecFileLoader.java:59)
17:14:35     at org.jacoco.core.tools.ExecFileLoader.load (ExecFileLoader.java:73)
17:14:35     at org.jacoco.maven.ReportSupport.loadExecutionData (ReportSupport.java:87)
17:14:35     at org.jacoco.maven.ReportAggregateMojo.loadExecutionData (ReportAggregateMojo.java:117)
17:14:35     at org.jacoco.maven.ReportAggregateMojo.loadExecutionData (ReportAggregateMojo.java:106)
17:14:35     at org.jacoco.maven.AbstractReportMojo.executeReport (AbstractReportMojo.java:177)
17:14:35     at org.jacoco.maven.AbstractReportMojo.execute (AbstractReportMojo.java:165)
17:14:35     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
17:14:35     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
17:14:35     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
17:14:35     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
17:14:35     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
17:14:35     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
17:14:35     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
17:14:35     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
17:14:35     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
17:14:35     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
17:14:35     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
17:14:35     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
17:14:35     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
17:14:35     at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
17:14:35     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
17:14:35     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
17:14:35     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
17:14:35     at java.lang.reflect.Method.invoke (Method.java:498)
17:14:35     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
17:14:35     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
17:14:35     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
17:14:35     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
...
```

**Comment by Godin** [comment]
`EOFException` indicates that exec file is truncated, i.e. wasn't fully written by an agent. Agent writes exec file at JVM shutdown using `Runtime.addShutdownHook()` API. So please remove existing files and make sure that JVM terminates gracefully and shutdown hooks are executed when you execute your test.

**Comment by LunaOfWhu** [comment]
hi Godin，we are meeting the similar matter, we executed unit test, and produced jacoco exec file,  A exception is thrown when we try to load exec file with function execFileLoader.load(new File(execfile)), i guess that's because exec file is corrupted and was produced incorrectly when maven build process failed and then exited. I would like to know if jacoco exec file is forgotten to be closed when build process failed?  sorry, i am not so sure about that, I'll appreciate that if you coule give us a guidance about how to  solve this problem.

**Comment by marchof** [comment]
@kennymacleod I don't like the idea having a build which creates random (coverage) results. If you want to measure code coverage you need to have a reliable, reproducible test setup.
