### ISSUE TITLE
Error while instrumenting even with @lombok.Generated annotation

### ISSUE THREAD

**Issue by lfarkas** [jacoco/jacoco#983]
we've got an enum like this:
```
@lombok.Generated
public enum Lang implements ILang {
```
AFAIK the docs said in this case it's not instrumented.

But during build still got this error:
```
net.vidux.control.LicenseManagerTest_setLicenseDataTest STANDARD_ERROR
    java.lang.instrument.IllegalClassFormatException: Error while instrumenting net/vidux/language/Lang.
        at org.jacoco.agent.rt.internal_43f5073.CoverageTransformer.transform(CoverageTransformer.java:94)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at net.vidux.configuration.model.LicenseData$LicenseOption.<clinit>(LicenseData.java:59)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.powermock.modules.agent.PowerMockClassRedefiner.redefine(PowerMockClassRedefiner.java:36)
        at org.powermock.modules.agent.support.PowerMockAgentTestInitializer.redefine(PowerMockAgentTestInitializer.java:62)
        at org.powermock.modules.agent.support.PowerMockAgentTestInitializer.redefineClassesToPrepare(PowerMockAgentTestInitializer.java:57)
        at org.powermock.modules.agent.support.PowerMockAgentTestInitializer.redefineClasses(PowerMockAgentTestInitializer.java:44)
        at org.powermock.modules.agent.support.PowerMockAgentTestInitializer.initialize(PowerMockAgentTestInitializer.java:34)
        at org.powermock.modules.junit4.rule.PowerMockRule.apply(PowerMockRule.java:47)
        at org.junit.runners.BlockJUnit4ClassRunner.withMethodRules(BlockJUnit4ClassRunner.java:365)
        at org.junit.runners.BlockJUnit4ClassRunner.withRules(BlockJUnit4ClassRunner.java:355)
        at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:278)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: java.io.IOException: Error while instrumenting net/vidux/language/Lang.
        at org.jacoco.agent.rt.internal_43f5073.core.instr.Instrumenter.instrumentError(Instrumenter.java:159)
        at org.jacoco.agent.rt.internal_43f5073.core.instr.Instrumenter.instrument(Instrumenter.java:109)
        at org.jacoco.agent.rt.internal_43f5073.CoverageTransformer.transform(CoverageTransformer.java:92)
        ... 64 more
    Caused by: org.jacoco.agent.rt.internal_43f5073.asm.MethodTooLargeException: Method too large: net/vidux/language/Lang.<clinit> ()V
        at org.jacoco.agent.rt.internal_43f5073.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2087)
        at org.jacoco.agent.rt.internal_43f5073.asm.ClassWriter.toByteArray(ClassWriter.java:447)
        at org.jacoco.agent.rt.internal_43f5073.core.instr.Instrumenter.instrument(Instrumenter.java:90)
        at org.jacoco.agent.rt.internal_43f5073.core.instr.Instrumenter.instrument(Instrumenter.java:107)
        ... 65 more
Running test: Test test_setLicenseDataFields_maintanence(net.vidux.control.LicenseManagerTest_setLicenseDataTest)
```

**Comment by Godin** [comment]
> AFAIK the docs said in this case it's not instrumented.

Don't know to which doc you refer - **filtering takes place at a time of generation of report**, not at a time of instrumentation.

----

> we've got an enum like this
> ```
> @lombok.Generated
> public enum Lang implements ILang {
> ```

Code provided by you is not sufficient to reproduce exception

`Lang.java`

```
public enum Lang implements ILang {
}

interface ILang {
}
```

can be successfully instrumented

```
$ mkdir classes

$ javac -version
javac 11.0.2

$ javac Lang.java -d classes

$ java -jar jacoco-0.8.5/lib/jacococli.jar instrument classes --dest instrumented
[INFO] 2 classes instrumented to /tmp/j/instrumented.
```

Could you please provide **complete reproducer** or at least `net/vidux/language/Lang.class` file?

----

However exception message

```
Caused by: org.jacoco.agent.rt.internal_43f5073.asm.MethodTooLargeException: Method too large: net/vidux/language/Lang.<clinit> ()V
```

indicates that your code is too big to be instrumented and exceeds JVM limit after instrumentation - see https://docs.oracle.com/javase/specs/jvms/se13/html/jvms-4.html#jvms-4.7.3 , which states

> The value of code_length must be greater than zero (as the code array must not be empty) and **less than 65536**.

See also corresponding check in ASM library that throws this exception - https://gitlab.ow2.org/asm/asm/blob/ASM_7_2/asm/src/main/java/org/objectweb/asm/MethodWriter.java#L2085

How many constants do you have in your `enum`?

----

To not hit this JVM limit either reduce amount of code, or exclude it from instrumentation. In case of Maven and on-the-fly instrumentation last one can be done using configuration property `excludes` - see https://www.jacoco.org/jacoco/trunk/doc/prepare-agent-mojo.html#excludes

**Comment by lfarkas** [comment]
it's a rather large file with a lot's of enum. and as we're not able to split the code i try to exclude it from instrumentation. can you tel me how can i do it with gradle? i can't find any documentation about gradle exclude possibilities or may be i didn't try hard enough.
thanks in advance.

**Comment by Godin** [comment]
> it's a rather large file with a lot's of enum.

Out of curiosity - how many enum constants do you have exactly? more than 2500? 😱

----

> can you tel me how can i do it with gradle? i can't find any documentation about gradle exclude possibilities or may be i didn't try hard enough.

[Gradle Plugin](https://github.com/gradle/gradle/tree/v6.0.1/subprojects/jacoco) is not developed by us. [Its documentation](https://docs.gradle.org/6.0.1/userguide/jacoco_plugin.html) mentions [`excludes` property](https://docs.gradle.org/6.0.1/dsl/org.gradle.testing.jacoco.plugins.JacocoTaskExtension.html#org.gradle.testing.jacoco.plugins.JacocoTaskExtension:excludes) to configure corresponding [option of agent](https://www.jacoco.org/jacoco/trunk/doc/agent.html). For example

```
test {
  jacoco {
    excludes = ['net.vidux.language.Lang']
  }
}
```

**Comment by lfarkas** [comment]
> > it's a rather large file with a lot's of enum.
> 
> Out of curiosity - how many enum constants do you have exactly? more than 2500? 

2610:-)

> > can you tel me how can i do it with gradle? i can't find any documentation about gradle exclude possibilities or may be i didn't try hard enough.
> 
> [Gradle Plugin](https://github.com/gradle/gradle/tree/v6.0.1/subprojects/jacoco) is not developed by us. [Its documentation](https://docs.gradle.org/6.0.1/userguide/jacoco_plugin.html) mentions [`excludes` property](https://docs.gradle.org/6.0.1/dsl/org.gradle.testing.jacoco.plugins.JacocoTaskExtension.html#org.gradle.testing.jacoco.plugins.JacocoTaskExtension:excludes) to configure corresponding [option of agent](https://www.jacoco.org/jacoco/trunk/doc/agent.html). For example
> 
> ```
> test {
>   jacoco {
>     excludes = ['net.vidux.language.Lang']
>   }
> }
> ```

thanks.
