### ISSUE TITLE
java.io.IOException: Invalid execution data file.

### ISSUE THREAD

**Issue by xiaozuoliao** [jacoco/jacoco#998]
我在启动一个服务时，指定了jacocoagent.jar 然后启动：
java -javaagent:/Users/ying.chen/Desktop/docker/jacocoagent.jar=includes=*,output=tcpserver,port=8886,address=10.111.155.197,append=false -jar  target/JacocoPlatform-0.0.1-SNAPSHOT.jar

dump数据正常，且能拿到覆盖率数据
只是在服务运行期间会输出错误日志：

java.io.IOException: Invalid execution data file.
at org.jacoco.agent.rt.internal_28bab1d.core.data.ExecutionDataReader.read(ExecutionDataReader.java:89)
at org.jacoco.agent.rt.internal_28bab1d.output.TcpConnection.run(TcpConnection.java:59)
at org.jacoco.agent.rt.internal_28bab1d.output.TcpServerOutput$1.run(TcpServerOutput.java:63)
at java.lang.Thread.run(Thread.java:748)

**Comment by Godin** [comment]
As stated in the template that you ignored:
in absence of **complete executable example** 
we have no idea how to reproduce your problem

<img width="747" alt="template" src="https://user-images.githubusercontent.com/138671/72797784-140b1480-3c42-11ea-8f87-c4bd0f70d7bb.png">
